import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const compiler = resolve(process.argv[2] ?? "target/release/tsuzuri");
const temporary = mkdtempSync(join(tmpdir(), "tsuzuri-docgen-"));
const cli = (args, expected = 0) => {
  const result = spawnSync(compiler, args, {
    encoding: "utf8", timeout: 120000,
    env: { ...process.env, TSUZURI_CLANG: join(temporary, "missing-clang"), TSUZURI_WASM_LD: join(temporary, "missing-linker") },
  });
  if (result.error) throw result.error;
  assert.equal(result.status, expected, `${args.join(" ")}\n${result.stdout}\n${result.stderr}`);
  return result;
};
const snapshot = (directory) => Object.fromEntries(readdirSync(directory).sort().map((name) => [name, readFileSync(join(directory, name), "utf8")]));
const diagnostic = (result) => result.stderr.trim().split("\n").map((line) => JSON.parse(line)).find((message) => message.severity === "error");

try {
  const input = join(temporary, "sources");
  const output = join(temporary, "output", "api");
  mkdirSync(join(input, "Geometry"), { recursive: true });
  const main = "/// Doubles a value.\n/// ```tsuzuri\n/// twice 21\n/// ```\ndef twice :: (Add<'a>, Copy<'a>) => 'a -> 'a\nfn twice value = value + value\nprivate def hidden :: i64\nfn hidden = 0\n/// Answer.\nconst answer: i64 = 42\n";
  writeFileSync(join(input, "Main.tz"), main);
  writeFileSync(join(input, "Geometry", "Point.tz"), "/// Coordinates.\nrecord Point { x: f64, y: f64 }\n");
  writeFileSync(join(input, "Builder.tc"), "/// Returns a value.\ndef Return :: 'a -> 'a\nfn Return value = value\n");
  writeFileSync(join(input, "Protocols.tt"), "/// Measures values.\nclass Measure<'a> {\n/// Gets the size.\ndef size :: ref 'a -> i64\n}\n");
  cli(["doc", input, "-o", output, "--json"]);
  const first = snapshot(output);
  assert.deepEqual(Object.keys(first), [".tsuzuri-docs", "Builder.md", "Geometry.Point.md", "Main.md", "Protocols.md", "index.md"]);
  assert.equal(first[".tsuzuri-docs"], "generated by tsuzuri doc\n");
  assert.equal(first["index.md"], "# Modules\n\n- [Builder](Builder.md)\n- [Geometry::Point](Geometry.Point.md)\n- [Main](Main.md)\n- [Protocols](Protocols.md)\n");
  assert.equal(first["Main.md"], "# Main\n\n## `twice`\n\n```tsuzuri\ndef twice :: (Add<'a>, Copy<'a>) => 'a -> 'a\n```\n\nDoubles a value.\n```tsuzuri\ntwice 21\n```\n\n## `answer`\n\n```tsuzuri\nconst answer: i64\n```\n\nAnswer.\n\n");
  assert.equal(first["Geometry.Point.md"], "# Geometry::Point\n\n## `Point`\n\n```tsuzuri\nrecord Point {\n  x: f64\n  y: f64\n}\n```\n\nCoordinates.\n\n");
  assert.match(first["Protocols.md"], /### `Measure.size`[\s\S]*Gets the size\./);
  assert.doesNotMatch(first["Main.md"], /hidden/);
  for (const source of [input, join(input, "Main.tz"), join(input, "Builder.tc"), join(input, "Protocols.tt")]) {
    cli(["doc", source, "--output", output]);
    assert.deepEqual(snapshot(output), first);
  }
  writeFileSync(join(input, "Main.tz"), "def invalid :: i64\nfn invalid = true\n");
  assert.equal(diagnostic(cli(["doc", input, "-o", output, "--json"], 1)).code, "E1003");
  assert.deepEqual(snapshot(output), first);
  writeFileSync(join(input, "Main.tz"), `${main}\n/// dangling\n`);
  assert.equal(diagnostic(cli(["doc", input, "-o", output, "--json"], 1)).code, "E0002");
  assert.deepEqual(snapshot(output), first);
  writeFileSync(join(input, "Main.tz"), main);
  const unowned = join(temporary, "unowned");
  mkdirSync(unowned);
  writeFileSync(join(unowned, "keep.txt"), "user data");
  assert.equal(diagnostic(cli(["doc", input, "-o", unowned, "--json"], 1)).code, "E2003");
  assert.equal(readFileSync(join(unowned, "keep.txt"), "utf8"), "user data");
  writeFileSync(join(input, ".tsuzuri-docs"), "generated by tsuzuri doc\n");
  assert.equal(diagnostic(cli(["doc", input, "-o", input, "--json"], 1)).code, "E2003");
  assert.equal(readFileSync(join(input, "Main.tz"), "utf8"), main);
  for (const flags of [["--target", "native"], ["--emit", "llvm"], ["--cpu", "generic"], ["-O0"], ["-g"]]) {
    assert.equal(diagnostic(cli(["doc", input, "-o", output, "--json", ...flags], 2)).code, "E2000");
  }
  assert.equal(diagnostic(cli(["doc", input, "--json"], 2)).code, "E2000");
  assert.deepEqual(snapshot(output), first);
  assert.ok(readdirSync(join(temporary, "output")).every((name) => !name.startsWith(".tsuzuri-")));
  const stdOutput = join(temporary, "standard-library");
  cli(["doc", resolve("std"), "-o", stdOutput, "--json"]);
  assert.ok(existsSync(join(stdOutput, "Array.md")));
  assert.match(readFileSync(join(stdOutput, "Array.md"), "utf8"), /sum_pairwise/);
  const maybe = readFileSync(join(stdOutput, "Maybe.md"), "utf8");
  assert.match(maybe, /^# Maybe\n\nNamespace: `std`\n/);
  assert.match(maybe, /union Maybe/);
  assert.match(maybe, /## `Return`/);
  const asyncPage = readFileSync(join(stdOutput, "Async.md"), "utf8");
  assert.match(asyncPage, /^# Async\n\nNamespace: `std`\n\nBuilder alias: `async`\n\n/);
  console.log("docgen: deterministic public Markdown, hierarchy, builders/classes, protected publication, compiler-free std generation passed");
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
