// The Unicode cases of the `unicode` suite in tests/features.mjs (D09 Phase 2). Expected values come from the
// official UCD test files (committed in compact form in tests/unicode-ucd.mjs, which
// `node tests/unicode-cases.mjs --write <UCD 17.0.0 directory>` regenerates) and from V8 (Node with Unicode 17.0):
// `\p{...}` for categories, `String.prototype.normalize`, `toUpperCase`/`toLowerCase` and `Intl.Segmenter`.
// tests/features.mjs never copies the compiler's output.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const dataPath = join(root, "tests/unicode-ucd.mjs");
const SOURCES = {
  "NormalizationTest.txt": "5019ffd530751a741900c849c0e010332f142a3612234639bd200b82138a87db",
  "auxiliary/GraphemeBreakTest.txt": "e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec",
  "auxiliary/WordBreakTest.txt": "1de23a75f37904abc7d206239ee8d34f8fdf0fb4ab32a7174dfbabbde25419b2",
  "CaseFolding.txt": "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183",
};
export const LAST = 0x10ffff;
// The codespace is tested in chunks: [start, start + CHUNK) for every chunk.
export const CHUNK = 0x11000;
export const FORMS = ["NFC", "NFD", "NFKC", "NFKD"];

const MOD = 1000000007n;
const mix = (hash, value) => (hash * 31n + BigInt(value) + 1n) % MOD;
const hashUnits = (units) => units.reduce(mix, mix(0n, units.length));
export const utf16 = (text) => Array.from({ length: text.length }, (_, index) => text.charCodeAt(index));
export const utf8 = (text) => [...Buffer.from(text, "utf8")];

/// The text that the fixture's `chunk` builds: every scalar of [start, stop) with `step`, each followed by a space.
export function chunkText(start, stop, step) {
  const parts = [];
  for (let code = start; code < stop; code += step) {
    if (code >= 0xd800 && code <= 0xdfff) continue;
    parts.push(String.fromCodePoint(code), " ");
  }
  return parts.join("");
}

// Scalars of a test are passed as 5 i64 arguments with three 21-bit slots each (code + 1; 0 ends the list).
export function pack(codes) {
  assert.ok(codes.length <= 15, `${codes.length} scalars`);
  const args = [0n, 0n, 0n, 0n, 0n];
  codes.forEach((code, index) => { args[Math.floor(index / 3)] += BigInt(code + 1) << BigInt(21 * (index % 3)); });
  return args;
}

const offsetsMask = (offsets) => offsets.reduce((mask, offset) => mask | (1n << BigInt(offset)), 0n);
function unitOffsets(codes, boundaries, encode) {
  const offsets = [];
  let offset = 0;
  codes.forEach((code, index) => {
    if (boundaries.has(index)) offsets.push(offset);
    offset += encode(String.fromCodePoint(code)).length;
  });
  offsets.push(offset);
  return offsets;
}

function readUcd(directory, name) {
  const bytes = readFileSync(join(directory, name));
  assert.equal(createHash("sha256").update(bytes).digest("hex"), SOURCES[name], `${name}: not the pinned Unicode 17.0.0 file`);
  return bytes.toString("utf8");
}

function segmentationTests(text) {
  return text.split("\n").map((line) => line.replace(/#.*/, "").trim()).filter(Boolean).map((line) => {
    const codes = [];
    const breaks = [];
    for (const token of line.split(/\s+/)) {
      if (token === "÷") breaks.push(codes.length);
      else if (token !== "×") codes.push(parseInt(token, 16));
    }
    return [codes, breaks];
  });
}

// A palette of the scalars of the tests and each test as base-36 palette indices of `width` digits.
function compact(rows, width) {
  const palette = [...new Set(rows.flatMap((row) => row.flat()))].sort((a, b) => a - b);
  const digits = (codes) => codes.map((code) => palette.indexOf(code).toString(36).padStart(width, "0")).join("");
  return [palette, digits];
}

function expand(palette, digits, width) {
  const codes = [];
  for (let index = 0; index < digits.length; index += width) codes.push(palette[parseInt(digits.slice(index, index + width), 36)]);
  return codes;
}

function write(directory) {
  const lines = [];
  const header = Object.entries(SOURCES).map(([name, digest]) => `//   ${name} ${digest}`).join("\n");
  lines.push(`// Generated by \`node tests/unicode-cases.mjs --write <UCD 17.0.0 directory>\` from these Unicode 17.0.0 files (SHA-256):\n${header}\n// Do not edit.`);
  for (const [name, file] of [["grapheme", "auxiliary/GraphemeBreakTest.txt"], ["word", "auxiliary/WordBreakTest.txt"]]) {
    const tests = segmentationTests(readUcd(directory, file));
    const [palette, digits] = compact(tests.map(([codes]) => codes), 2);
    lines.push(`export const ${name}Palette = [${palette.join(",")}];`);
    lines.push(`export const ${name}Tests = ${JSON.stringify(tests.map(([codes, breaks]) => `${digits(codes)}:${breaks.reduce((mask, index) => mask + 2 ** index, 0).toString(36)}`).join(","))};`);
  }
  // NormalizationTest.txt: Parts 0, 3 and 5 whole, every 8th line of Parts 2 and 4, as c1..c5. Part 1 (single
  // scalars) is covered by the whole-codespace chunks, whose V8 reference the check below ties to the file.
  let part = "";
  const rows = [];
  let count = 0;
  for (const line of readUcd(directory, "NormalizationTest.txt").split("\n")) {
    if (line.startsWith("@Part")) { part = line.slice(5, 6); count = 0; continue; }
    const data = line.replace(/#.*/, "").trim();
    if (!data) continue;
    const columns = data.split(";").slice(0, 5).map((column) => column.trim().split(" ").map((digits) => parseInt(digits, 16)));
    const source = String.fromCodePoint(...columns[0]);
    FORMS.forEach((form, index) => assert.deepEqual([...source.normalize(form)].map((char) => char.codePointAt(0)), columns[index + 1], `V8 ${form} of ${data}`));
    if (part === "0" || part === "3" || part === "5" || ((part === "2" || part === "4") && count++ % 8 === 0)) rows.push(columns);
  }
  const [palette, digits] = compact(rows, 3);
  lines.push(`export const normalizationPalette = [${palette.join(",")}];`);
  // A column equal to an earlier one is written as that column's number.
  const encodeRow = (columns) => columns.map((column, index) => {
    const same = columns.slice(0, index).findIndex((earlier) => earlier.join() === column.join());
    return same >= 0 ? String(same) : digits(column);
  }).join("|");
  lines.push(`export const normalizationTests = ${JSON.stringify(rows.map(encodeRow).join(","))};`);
  // Full case folding (statuses C and F) of each codespace chunk, as the fixture's `case_chunk` hashes it.
  const folding = new Map();
  for (const line of readUcd(directory, "CaseFolding.txt").split("\n")) {
    const fields = line.replace(/#.*/, "").split(";").map((field) => field.trim());
    if (fields.length < 3 || (fields[1] !== "C" && fields[1] !== "F")) continue;
    folding.set(parseInt(fields[0], 16), String.fromCodePoint(...fields[2].split(" ").map((digits) => parseInt(digits, 16))));
  }
  const folds = [];
  for (let start = 0; start <= LAST; start += CHUNK) {
    const text = [...chunkText(start, Math.min(start + CHUNK, LAST + 1), 1)].map((char) => folding.get(char.codePointAt(0)) ?? char).join("");
    folds.push(hashUnits(utf16(text)));
  }
  lines.push(`export const foldHashes = [${folds.map((hash) => `${hash}n`).join(", ")}];`);
  writeFileSync(dataPath, `${lines.join("\n")}\n`);
  console.log(`wrote ${dataPath}: ${readFileSync(dataPath).length} bytes; V8 matches all of NormalizationTest.txt`);
}

// A deterministic generator for the V8 cases.
function generator(seed) {
  let state = BigInt(seed);
  return () => {
    state = (state * 6364136223846793005n + 1442695040888963407n) & ((1n << 64n) - 1n);
    return Number(state >> 33n);
  };
}

const NORMALIZATION_POOL = [0x41, 0x61, 0x65, 0x6f, 0x75, 0xc5, 0xe9, 0x1e0a, 0x1e63, 0x212b, 0x2126, 0x0958, 0x0f73,
  0x0f75, 0x0f81, 0x0300, 0x0301, 0x0302, 0x0303, 0x0307, 0x0308, 0x030a, 0x0323, 0x0327, 0x0328, 0x0345, 0x05b0,
  0x05b9, 0x0591, 0x0f71, 0x0f72, 0x0f74, 0x0f80, 0x1d16e, 0x1d165, 0x1d16f, 0x1100, 0x1101, 0x1161, 0x1162, 0x11a8,
  0x11a9, 0xac00, 0xac01, 0xd7a3, 0x3131, 0xfb01, 0x2460, 0x00bd, 0x00a0, 0x2000, 0xfdfa, 0x3300, 0x0344, 0x0340,
  0x0b47, 0x0b3e, 0x0b57, 0x09c7, 0x09be, 0x1100 + 18, 0x0626, 0x0654, 0x0655, 0x1fb6, 0x03b1, 0x0391, 0x1f00, 0x0342,
  0x05d0, 0x05b7, 0xfb2e, 0x2adc, 0x0338, 0x003d, 0x226e, 0x0110000 - 1, 0x1f600, 0x0, 0x20, 0x2028];
const GRAPHEME_POOL = [0x41, 0x0d, 0x0a, 0x01, 0x0301, 0x200d, 0x1f1ef, 0x1f1f5, 0x1f1fa, 0x1f1f8, 0x0600, 0x0903,
  0x1100, 0x1161, 0x11a8, 0xac00, 0xac01, 0x1f468, 0x1f469, 0x1f466, 0x1f3fb, 0x2764, 0xfe0f, 0x0915, 0x094d, 0x0937,
  0x093f, 0x0924, 0x0930, 0x0e01, 0x0e33, 0x1f600, 0x00ad, 0x0020, 0x0644, 0x0627, 0x200c, 0x1f3f4, 0xe0067, 0xe007f];
const CASE_POOL = [0x3a3, 0x3c3, 0x3c2, 0x391, 0x41, 0x61, 0x20, 0x2e, 0x27, 0x0301, 0x0345, 0xdf, 0x1e9e, 0x130, 0x131,
  0x69, 0x49, 0xfb01, 0x1f80, 0x1f88, 0x149, 0x1c5, 0x1c4, 0x1c6, 0x2d, 0x30, 0xad, 0x2019, 0x10400, 0x10428];

/// The cases of the suite, from the committed UCD data (`import * as ucd from "./unicode-ucd.mjs"`).
export function expectedCases(ucd) {
  const cases = [];
  const units = (text, encode) => encode(text);
  const hashText = (hash, text, encode) => units(text, encode).reduce(mix, mix(hash, units(text, encode).length));
  const offsets = (codes, breaks, encode) => offsetsMask(unitOffsets(codes, breaks, encode));
  // `kinds`: 0 lowercase then uppercase, 1 titlecase, 3 case folding; the fixture hashes UTF-16, then UTF-8.
  const caseHash = (results, utf8Too) => results.reduce((hash, text) => utf8Too ? hashText(hashText(hash, text, utf16), text, utf8) : hashText(hash, text, utf16), 0n);
  const normalizeHash = (text) => FORMS.reduce((hash, form) => {
    const result = text.normalize(form);
    const flag = result === text ? 3 : 0;
    return mix(hashText(hashText(hash, result, utf16), result, utf8), flag);
  }, 0n);
  const segmentsHash = (codes, breaks, pieces) => {
    let hash = mix(mix(0n, offsets(codes, breaks, utf16)), offsets(codes, breaks, utf8));
    hash = mix(hash, pieces.length);
    for (const piece of pieces) hash = hashText(hash, piece, utf16);
    for (const piece of pieces) hash = hashText(hash, piece, utf8);
    return hash;
  };
  const piecesOf = (codes, breaks) => {
    const pieces = [];
    codes.forEach((code, index) => {
      if (breaks.has(index) || pieces.length === 0) pieces.push("");
      pieces[pieces.length - 1] += String.fromCodePoint(code);
    });
    return pieces;
  };
  // Categories of every scalar, from V8's `\p{...}`.
  const categories = ["Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No", "Pc", "Pd", "Ps", "Pe", "Pi", "Pf",
    "Po", "Sm", "Sc", "Sk", "So", "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co", "Cn"].map((name) => [name, new RegExp(`^\\p{${name}}$`, "u")]);
  for (let start = 0; start <= LAST; start += CHUNK) {
    const stop = Math.min(start + CHUNK, LAST + 1);
    let hash = 0n;
    for (let code = start; code < stop; code++) {
      if (code >= 0xd800 && code <= 0xdfff) continue;
      const char = String.fromCodePoint(code);
      hash = utf16(categories.find(([, re]) => re.test(char))[0]).reduce(mix, hash);
    }
    cases.push(["category_chunk", [BigInt(start)], hash]);
    // Every scalar in every normalization form and case conversion (V8), each followed by a space; the UTF-8
    // entry points take every 9th scalar.
    const text = chunkText(start, stop, 1);
    const sparse = chunkText(start, stop, 9);
    cases.push(["normalize_chunk", [BigInt(start), 1n, 0n], FORMS.reduce((hash, form) => hashText(hash, text.normalize(form), utf16), 0n)]);
    cases.push(["normalize_chunk", [BigInt(start), 9n, 1n], FORMS.reduce((hash, form) => hashText(hash, sparse.normalize(form), utf8), 0n)]);
    cases.push(["case_chunk", [0n, BigInt(start), 1n], caseHash([text.toLowerCase(), text.toUpperCase()], false)]);
    cases.push(["case_chunk", [3n, BigInt(start), 1n], ucd.foldHashes[start / CHUNK]]);
  }
  // UCD conformance tests.
  for (const [which, palette, tests] of [[0n, ucd.graphemePalette, ucd.graphemeTests], [1n, ucd.wordPalette, ucd.wordTests]]) {
    for (const test of tests.split(",")) {
      const [digits, mask] = test.split(":");
      const codes = expand(palette, digits, 2);
      const breaks = new Set();
      const bits = parseInt(mask, 36);
      for (let index = 0; index <= codes.length; index++) if (Math.floor(bits / 2 ** index) % 2 === 1) breaks.add(index);
      assert.ok(breaks.has(0) && breaks.has(codes.length));
      cases.push(["segments_packed", [which, ...pack(codes)], segmentsHash(codes, breaks, piecesOf(codes, breaks))]);
    }
  }
  for (const test of ucd.normalizationTests.split(",")) {
    const columns = [];
    for (const digits of test.split("|")) columns.push(digits.length === 1 ? columns[Number(digits)] : expand(ucd.normalizationPalette, digits, 3));
    if (columns[0].length > 15) continue;
    const source = String.fromCodePoint(...columns[0]);
    const expected = FORMS.reduce((hash, _, index) => {
      const result = String.fromCodePoint(...columns[index + 1]);
      return mix(hashText(hashText(hash, result, utf16), result, utf8), result === source ? 3 : 0);
    }, 0n);
    cases.push(["normalize_packed", pack(columns[0]), expected]);
  }
  // V8 on random sequences.
  const next = generator(20261007);
  const sequence = (pool) => Array.from({ length: 1 + next() % 15 }, () => next() % 5 === 0 ? (next() % 0x110000) : pool[next() % pool.length])
    .map((code) => code >= 0xd800 && code <= 0xdfff ? 0x41 : code);
  const segmenter = new Intl.Segmenter("und", { granularity: "grapheme" });
  for (let index = 0; index < 300; index++) {
    const text = String.fromCodePoint(...sequence(NORMALIZATION_POOL));
    cases.push(["normalize_packed", pack([...text].map((char) => char.codePointAt(0))), normalizeHash(text)]);
    const graphemeCodes = sequence(GRAPHEME_POOL);
    const graphemeText = String.fromCodePoint(...graphemeCodes);
    const breaks = new Set();
    let position = 0;
    const starts = new Set([...segmenter.segment(graphemeText)].map((segment) => segment.index));
    graphemeCodes.forEach((code, scalar) => { if (starts.has(position)) breaks.add(scalar); position += String.fromCodePoint(code).length; });
    breaks.add(graphemeCodes.length);
    cases.push(["segments_packed", [0n, ...pack(graphemeCodes)], segmentsHash(graphemeCodes, breaks, [...segmenter.segment(graphemeText)].map((segment) => segment.segment))]);
    const caseText = String.fromCodePoint(...sequence(CASE_POOL));
    cases.push(["case_packed", [0n, ...pack([...caseText].map((char) => char.codePointAt(0)))], caseHash([caseText.toLowerCase(), caseText.toUpperCase()], true)]);
  }
  // Titlecase, written by hand from Unicode §3.13 (toTitlecase with UAX #29 words) and SpecialCasing.txt.
  for (const [input, expected] of [
    ["hello world", "Hello World"], ["HELLO wORLD", "Hello World"], ["ǆemal ǅ", "ǅemal ǅ"], ["ßa", "Ssa"], ["ﬁsh", "Fish"],
    ["o'neil can't", "O'neil Can't"], ["ΣΑΣ σας", "Σας Σας"], ["1st 2nd", "1St 2Nd"], ["ŉ", "ʼN"], ["ᾀ ᾈ", "ᾈ ᾈ"],
    ["", ""], ["  a\tb", "  A\tB"], ["x.y", "X.y"], ["\u0345a", "\u0399A"], ["a\u0301b c", "A\u0301b C"], ["ΌΣΟΣ.", "Όσος."],
  ]) {
    cases.push(["case_packed", [1n, ...pack([...input].map((char) => char.codePointAt(0)))], caseHash([expected], true)]);
  }
  return cases;
}

if (process.argv.includes("--write")) {
  const directory = process.argv[process.argv.indexOf("--write") + 1];
  assert.ok(directory, "usage: node tests/unicode-cases.mjs --write <UCD 17.0.0 directory>");
  write(directory);
} else if (process.argv[1] === fileURLToPath(import.meta.url)) {
  assert.ok(existsSync(dataPath), "run node tests/unicode-cases.mjs --write <UCD directory>");
  console.log(`unicode cases: ${expectedCases(await import(dataPath)).length} expectations`);
}
