//! `tsuzuri bindgen` (E11): Tsuzuri declarations generated from a C header.
//!
//! The driver runs Clang and passes its JSON AST to [`generate`]. Everything in this
//! module is a pure function of its input, so the same Clang, header, and include
//! directories always give the same bytes. A declaration is generated only when its C
//! ABI provably matches the Tsuzuri host ABI: Clang's type spelling, with typedefs
//! expanded, must match a fixed table exactly, and only LP64 targets are accepted.
//! Every other declaration of the header becomes a `// skipped` line and a `W2002`
//! warning instead of a guess.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::{OsStr, OsString};
use std::ops::Range;
use std::path::PathBuf;

use serde_json::Value;

/// The first line of every generated file; bindgen overwrites only files that start with it.
pub const MARKER: &str = "// Generated by tsuzuri bindgen. Do not edit.";
/// The most bytes bindgen reads from one Clang invocation.
pub const MAX_AST_BYTES: usize = 256 * 1024 * 1024;
const MAX_TYPEDEF_DEPTH: usize = 32;
const MAX_TYPE_NESTING: usize = 32;
const OPTIONS: &str = "bindgen accepts only -o, --include-dir, and --json";

/// `tsuzuri bindgen HEADER -o OUTPUT.tz [--include-dir DIR]... [--json]`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Arguments {
    pub header: PathBuf,
    pub output: PathBuf,
    /// Passed to Clang as `-I DIR` in this order; they only resolve includes.
    pub include_dirs: Vec<PathBuf>,
    pub json: bool,
}

/// Parses the arguments after `bindgen`. The error is an `E2000` message.
pub fn parse_arguments(arguments: &[OsString]) -> Result<Arguments, String> {
    let mut headers = Vec::new();
    let mut output = None;
    let mut include_dirs = Vec::new();
    let mut json = false;
    let mut paths_only = false;
    let mut rest = arguments.iter();
    while let Some(argument) = rest.next() {
        if !paths_only {
            match argument.to_str() {
                Some("--") => {
                    paths_only = true;
                    continue;
                }
                Some("--json") => {
                    json = true;
                    continue;
                }
                Some("-o" | "--output") => {
                    if output.is_some() {
                        return Err("output specified more than once".into());
                    }
                    output = Some(PathBuf::from(rest.next().ok_or("--output needs a value")?));
                    continue;
                }
                Some("--include-dir") => {
                    include_dirs.push(PathBuf::from(
                        rest.next().ok_or("--include-dir needs a value")?,
                    ));
                    continue;
                }
                Some(value) if value.starts_with('-') => return Err(OPTIONS.into()),
                _ => {}
            }
        }
        headers.push(PathBuf::from(argument));
    }
    let [header] = <[PathBuf; 1]>::try_from(headers)
        .map_err(|_| "bindgen requires exactly one header path".to_owned())?;
    let output = output.ok_or("bindgen requires -o OUTPUT.tz")?;
    if output.extension() != Some(OsStr::new("tz")) {
        return Err("bindgen output must have the .tz extension".into());
    }
    let module = output.file_stem().and_then(OsStr::to_str).unwrap_or("");
    if !module.starts_with(|first: char| first.is_ascii_uppercase())
        || !module
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    {
        return Err(format!(
            "bindgen output '{}' is not a module file name; start it with an uppercase ASCII letter followed by letters, digits, or '_', as in Zlib.tz",
            output.display()
        ));
    }
    Ok(Arguments {
        header,
        output,
        include_dirs,
        json,
    })
}

/// What the generated header comment records about the input.
pub struct HeaderInfo<'a> {
    /// The absolute path passed to Clang; a declaration belongs to the header when
    /// Clang's AST places it in this file.
    pub path: &'a str,
    pub file_name: &'a str,
    /// SHA-256 of the header's bytes in lowercase hex.
    pub sha256: &'a str,
    /// The first line of `clang --version`.
    pub clang_version: &'a str,
    /// The output of `clang -dumpmachine`.
    pub target: &'a str,
}

/// A header declaration that bindgen did not convert, reported as `W2002`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Skipped {
    /// The C name.
    pub name: String,
    pub reason: String,
    /// The byte range of the declaration's name in the header.
    pub offset: usize,
    pub length: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Generated {
    pub text: String,
    pub skipped: Vec<Skipped>,
}

/// Whether bindgen accepts Clang's target triple: 64-bit x86 and ARM with 64-bit
/// `long` and pointers (LP64), which excludes Windows (LLP64) and the ILP32 ABIs.
pub fn lp64_target(triple: &str) -> bool {
    let architecture = triple.split('-').next().unwrap_or("");
    matches!(architecture, "x86_64" | "aarch64" | "arm64")
        && !["windows", "mingw", "cygwin", "uefi", "gnux32", "ilp32"]
            .iter()
            .any(|system| triple.contains(system))
}

/// Converts the JSON AST of `clang -Xclang -ast-dump=json` for the header into a
/// Tsuzuri module. `Err` means the AST does not have the shape Clang writes.
pub fn generate(ast: &Value, header: &HeaderInfo) -> Result<Generated, String> {
    let nodes = ast
        .get("inner")
        .and_then(Value::as_array)
        .ok_or("the translation unit has no 'inner' array")?;
    let declarations = header_declarations(nodes, header.path)?;
    let tables = Tables::new(nodes);
    let mut emitter = Emitter::new(&tables, header.target);
    emitter.collect_types(&declarations);
    for (index, declaration) in declarations.iter().enumerate() {
        if declaration.owned {
            emitter.declaration(index, declaration)?;
        }
    }
    Ok(emitter.finish(header))
}

// ---------------------------------------------------------------------------
// Which declarations belong to the header

/// A top-level declaration and where its name is.
struct Declaration<'a> {
    node: &'a Value,
    kind: &'a str,
    owned: bool,
    offset: usize,
    length: usize,
}

/// Clang writes a location's `file` only when it differs from the previously written
/// location, so the file of each declaration is known only by visiting every location
/// in the order Clang printed them: `loc` (spelling, then expansion), `range` (begin,
/// then end), then the children. `serde_json` objects do not keep key order, so the
/// order is fixed here rather than taken from the map.
fn header_declarations<'a>(nodes: &'a [Value], path: &str) -> Result<Vec<Declaration<'a>>, String> {
    let mut tracker = Tracker::default();
    let mut declarations = Vec::with_capacity(nodes.len());
    for node in nodes {
        let kind = node
            .get("kind")
            .and_then(Value::as_str)
            .ok_or("a declaration of the translation unit has no 'kind'")?;
        tracker.location(node.get("loc"));
        // A declaration expanded from a macro belongs to the file of the expansion.
        let file = tracker.current;
        tracker.range(node.get("range"));
        tracker.children(node);
        let (offset, length) = position(node);
        declarations.push(Declaration {
            node,
            kind,
            owned: file == Some(path) && !flag(node, "isImplicit"),
            offset,
            length,
        });
    }
    Ok(declarations)
}

#[derive(Default)]
struct Tracker<'a> {
    current: Option<&'a str>,
}

impl<'a> Tracker<'a> {
    fn location(&mut self, location: Option<&'a Value>) {
        let Some(location) = location else {
            return;
        };
        let spelling = location.get("spellingLoc");
        let expansion = location.get("expansionLoc");
        if spelling.is_none() && expansion.is_none() {
            self.bare(location);
        }
        for part in [spelling, expansion].into_iter().flatten() {
            self.bare(part);
        }
    }

    fn bare(&mut self, location: &'a Value) {
        // `includedFrom` also has a `file`, but Clang does not count it as written.
        if let Some(file) = location.get("file").and_then(Value::as_str) {
            self.current = Some(file);
        }
    }

    fn range(&mut self, range: Option<&'a Value>) {
        if let Some(range) = range {
            self.location(range.get("begin"));
            self.location(range.get("end"));
        }
    }

    fn children(&mut self, node: &'a Value) {
        for key in ["array_filler", "inner"] {
            for child in node
                .get(key)
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                // serde_json limits nesting to 128, which bounds this recursion.
                self.location(child.get("loc"));
                self.range(child.get("range"));
                self.children(child);
            }
        }
    }
}

/// The byte range of a node's name: the expansion of a macro, else the location itself.
fn position(node: &Value) -> (usize, usize) {
    let Some(location) = node.get("loc") else {
        return (0, 0);
    };
    let location = location.get("expansionLoc").unwrap_or(location);
    let number = |key| {
        location
            .get(key)
            .and_then(Value::as_u64)
            .and_then(|value| usize::try_from(value).ok())
            .unwrap_or(0)
    };
    (number("offset"), number("tokLen"))
}

fn flag(node: &Value, key: &str) -> bool {
    node.get(key).and_then(Value::as_bool) == Some(true)
}

fn text<'a>(node: &'a Value, key: &str) -> Option<&'a str> {
    node.get(key).and_then(Value::as_str)
}

fn name(node: &Value) -> &str {
    text(node, "name").unwrap_or("")
}

fn kind(node: &Value) -> &str {
    text(node, "kind").unwrap_or("")
}

/// The spelled and desugared C type of a node.
fn node_type(node: &Value) -> (&str, Option<&str>) {
    let ty = node.get("type");
    let spelled = ty.and_then(|ty| text(ty, "qualType")).unwrap_or("");
    let desugared = ty.and_then(|ty| text(ty, "desugaredQualType"));
    (spelled, desugared)
}

fn children(node: &Value) -> impl Iterator<Item = &Value> {
    node.get("inner")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
}

fn has_attribute(node: &Value, kinds: &[&str]) -> bool {
    children(node).any(|child| kinds.contains(&kind(child)))
}

/// Attributes that change a struct's or a field's layout from the natural C layout.
const LAYOUT_ATTRIBUTES: &[&str] = &["AlignedAttr", "PackedAttr", "MaxFieldAlignmentAttr"];

// ---------------------------------------------------------------------------
// C types as Clang spells them

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct Qualifiers {
    constant: bool,
    volatile: bool,
}

impl Qualifiers {
    fn union(self, other: Self) -> Self {
        Self {
            constant: self.constant || other.constant,
            volatile: self.volatile || other.volatile,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum CType {
    /// Specifiers without qualifiers: a builtin such as `unsigned long`, a tag such
    /// as `struct point`, or a typedef name.
    Named(String),
    /// A pointer and the qualifiers of what it points to.
    Pointer(Box<CType>, Qualifiers),
    /// A prototyped, non-variadic function type: its result and parameters.
    Function(Box<CType>, Vec<CType>),
    /// Anything else, including spellings this parser does not understand.
    Unsupported,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Token<'a> {
    Word(&'a str),
    Symbol(char),
}

fn tokenize(text: &str) -> Vec<(usize, Token<'_>)> {
    let bytes = text.as_bytes();
    let word = |byte: u8| byte.is_ascii_alphanumeric() || byte == b'_' || byte == b'$';
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index].is_ascii_whitespace() {
            index += 1;
        } else if word(bytes[index]) {
            let start = index;
            while index < bytes.len() && word(bytes[index]) {
                index += 1;
            }
            tokens.push((start, Token::Word(&text[start..index])));
        } else if text[index..].starts_with("...") {
            tokens.push((index, Token::Word("...")));
            index += 3;
        } else {
            let character = text[index..].chars().next().unwrap_or('?');
            tokens.push((index, Token::Symbol(character)));
            index += character.len_utf8();
        }
    }
    tokens
}

/// The index of the `)` that closes the `(` at `open`.
fn matching(tokens: &[(usize, Token<'_>)], open: usize) -> Option<usize> {
    let mut depth = 0usize;
    for (index, (_, token)) in tokens.iter().enumerate().skip(open) {
        match token {
            Token::Symbol('(') => depth += 1,
            Token::Symbol(')') => {
                depth -= 1;
                if depth == 0 {
                    return Some(index);
                }
            }
            _ => {}
        }
    }
    None
}

/// Parses a whole type spelling: specifiers, pointers with their qualifiers, and at
/// most one function-pointer declarator `R (*)(P, ...)`. The qualifiers returned
/// are those of the type itself (top level).
fn parse_type(text: &str) -> Option<(CType, Qualifiers)> {
    parse_tokens(&tokenize(text), 0)
}

fn parse_tokens(tokens: &[(usize, Token<'_>)], nesting: usize) -> Option<(CType, Qualifiers)> {
    if nesting > MAX_TYPE_NESTING {
        return None;
    }
    let mut parser = TypeParser {
        tokens,
        position: 0,
        nesting,
    };
    let parsed = parser.whole()?;
    (parser.position == tokens.len()).then_some(parsed)
}

struct TypeParser<'t, 'a> {
    tokens: &'t [(usize, Token<'a>)],
    position: usize,
    nesting: usize,
}

impl<'a> TypeParser<'_, 'a> {
    fn peek(&self) -> Option<Token<'a>> {
        self.tokens.get(self.position).map(|(_, token)| *token)
    }

    fn eat(&mut self, symbol: char) -> bool {
        let found = self.peek() == Some(Token::Symbol(symbol));
        self.position += usize::from(found);
        found
    }

    fn whole(&mut self) -> Option<(CType, Qualifiers)> {
        let (mut ty, mut qualifiers) = self.specifiers()?;
        while self.eat('*') {
            ty = CType::Pointer(Box::new(ty), qualifiers);
            qualifiers = self.qualifiers()?;
        }
        if self.eat('(') {
            // Only `(*)` with optional qualifiers: blocks `(^)` and nested
            // declarators are not supported.
            if !self.eat('*') {
                return None;
            }
            let pointer = self.qualifiers()?;
            if !self.eat(')') || !self.eat('(') {
                return None;
            }
            let parameters = self.parameters()?;
            let function = if parameters.prototype && !parameters.variadic {
                CType::Function(Box::new(ty), parameters.list)
            } else {
                CType::Unsupported
            };
            ty = CType::Pointer(Box::new(function), Qualifiers::default());
            qualifiers = pointer;
        }
        Some((ty, qualifiers))
    }

    fn specifiers(&mut self) -> Option<(CType, Qualifiers)> {
        let mut words = Vec::new();
        let mut qualifiers = Qualifiers::default();
        while let Some(Token::Word(word)) = self.peek() {
            self.position += 1;
            match word {
                "const" => qualifiers.constant = true,
                "volatile" => qualifiers.volatile = true,
                "restrict" | "__restrict" | "_Nonnull" | "_Nullable" | "_Null_unspecified"
                | "_Nullable_result" => {}
                "struct" | "union" | "enum" => {
                    // An anonymous tag is spelled `struct (unnamed struct at ...)`.
                    let Some(Token::Word(tag)) = self.peek() else {
                        return None;
                    };
                    self.position += 1;
                    words.push(format!("{word} {tag}"));
                }
                _ => words.push(word.to_owned()),
            }
        }
        (!words.is_empty()).then(|| (CType::Named(words.join(" ")), qualifiers))
    }

    /// The qualifiers after a `*`, which apply to the pointer itself.
    fn qualifiers(&mut self) -> Option<Qualifiers> {
        let mut qualifiers = Qualifiers::default();
        while let Some(Token::Word(word)) = self.peek() {
            match word {
                "const" => qualifiers.constant = true,
                "volatile" => qualifiers.volatile = true,
                "restrict" | "__restrict" | "_Nonnull" | "_Nullable" | "_Null_unspecified"
                | "_Nullable_result" => {}
                _ => return None,
            }
            self.position += 1;
        }
        Some(qualifiers)
    }

    /// The parameter list after its `(`, through the closing `)`.
    fn parameters(&mut self) -> Option<Parameters> {
        let mut depth = 0usize;
        let mut pieces = Vec::new();
        let mut start = self.position;
        loop {
            let (_, token) = *self.tokens.get(self.position)?;
            self.position += 1;
            match token {
                Token::Symbol('(' | '[') => depth += 1,
                Token::Symbol(')') if depth == 0 => {
                    pieces.push(start..self.position - 1);
                    break;
                }
                Token::Symbol(')' | ']') => depth = depth.checked_sub(1)?,
                Token::Symbol(',') if depth == 0 => {
                    pieces.push(start..self.position - 1);
                    start = self.position;
                }
                _ => {}
            }
        }
        Some(parameter_list(self.tokens, pieces, self.nesting))
    }
}

struct Parameters {
    list: Vec<CType>,
    /// `false` for `()`, which declares no prototype in C17.
    prototype: bool,
    variadic: bool,
}

fn parameter_list(
    tokens: &[(usize, Token<'_>)],
    mut pieces: Vec<Range<usize>>,
    nesting: usize,
) -> Parameters {
    let piece = |range: &Range<usize>| &tokens[range.clone()];
    if pieces.len() == 1 && pieces[0].is_empty() {
        return Parameters {
            list: Vec::new(),
            prototype: false,
            variadic: false,
        };
    }
    if pieces.len() == 1 && matches!(piece(&pieces[0]), [(_, Token::Word("void"))]) {
        pieces.clear();
    }
    let variadic = pieces
        .last()
        .is_some_and(|last| matches!(piece(last), [(_, Token::Word("..."))]));
    if variadic {
        pieces.pop();
    }
    Parameters {
        list: pieces
            .iter()
            .map(|range| {
                parse_tokens(piece(range), nesting + 1).map_or(CType::Unsupported, |(ty, _)| ty)
            })
            .collect(),
        prototype: true,
        variadic,
    }
}

/// A function declaration's type `R (P1, P2) attributes`, split into its parts.
struct FunctionShape {
    /// The spelling of the result type; `Err` holds the spelling of a function-pointer
    /// or block result, which is never supported.
    result: Result<String, String>,
    prototype: bool,
    /// The names in trailing `__attribute__((...))` groups; `?` marks other text.
    attributes: Vec<String>,
}

fn function_shape(text: &str) -> Option<FunctionShape> {
    let tokens = tokenize(text);
    let mut attributes = Vec::new();
    // Clang prints some calling conventions before the type (`__attribute__((x)) int
    // (int)`) and others after the parameter list.
    let mut result_start = 0;
    let mut open = 0;
    loop {
        match tokens.get(open)?.1 {
            Token::Word("__attribute__") => {
                let (name, end) = attribute_group(&tokens, open)?;
                attributes.push(name);
                if open == result_start {
                    result_start = end + 1;
                }
                open = end + 1;
            }
            // The parameter list is the first `(` that does not spell an anonymous tag.
            Token::Symbol('(')
                if open > 0
                    && matches!(tokens[open - 1].1, Token::Word("struct" | "union" | "enum")) =>
            {
                open = matching(&tokens, open)? + 1;
            }
            Token::Symbol('(') => break,
            _ => open += 1,
        }
    }
    let close = matching(&tokens, open)?;
    if matches!(
        tokens.get(open + 1).map(|token| token.1),
        Some(Token::Symbol('*' | '^'))
    ) {
        // `int (*(int))(void)` returns `int (*)(void)`: drop the function's own
        // parameter list, which directly follows the `*` and its qualifiers.
        let mut inner = open + 2;
        while matches!(tokens.get(inner).map(|token| token.1), Some(Token::Word(_))) {
            inner += 1;
        }
        let spelled = match tokens.get(inner) {
            Some((from, Token::Symbol('('))) => {
                let end = matching(&tokens, inner)?;
                format!("{}{}", &text[..*from], &text[tokens[end].0 + 1..])
            }
            _ => text.to_owned(),
        };
        return Some(FunctionShape {
            result: Err(spelled.trim().to_owned()),
            prototype: true,
            attributes,
        });
    }
    let mut index = close + 1;
    while index < tokens.len() {
        let Some((name, end)) = attribute_group(&tokens, index) else {
            attributes.push("?".to_owned());
            break;
        };
        attributes.push(name);
        index = end + 1;
    }
    let result_text = match tokens.get(result_start) {
        Some((from, _)) if result_start < open => &text[*from..tokens[open].0],
        _ => "",
    };
    Some(FunctionShape {
        result: Ok(result_text.trim().to_owned()),
        prototype: close != open + 1,
        attributes,
    })
}

/// The name in an `__attribute__((name...))` group at `start` and the index of its last `)`.
fn attribute_group(tokens: &[(usize, Token<'_>)], start: usize) -> Option<(String, usize)> {
    let group = matches!(tokens.get(start)?.1, Token::Word("__attribute__"))
        && tokens.get(start + 1)?.1 == Token::Symbol('(')
        && tokens.get(start + 2)?.1 == Token::Symbol('(');
    if !group {
        return None;
    }
    let end = matching(tokens, start + 1)?;
    let name = match tokens.get(start + 3)?.1 {
        Token::Word(name) => name.to_owned(),
        Token::Symbol(_) => "?".to_owned(),
    };
    Some((name, end))
}

/// Replaces Clang's `(unnamed struct at /abs/path:1:2)` with `(unnamed struct)`, so
/// generated text and warnings never contain absolute paths.
fn scrub(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = ["(unnamed ", "(anonymous "]
        .iter()
        .filter_map(|marker| rest.find(marker))
        .min()
    {
        let Some(end) = rest[start..].find(')').map(|end| start + end) else {
            break;
        };
        let inside = &rest[start..end];
        result.push_str(&rest[..start]);
        result.push_str(inside.split(" at ").next().unwrap_or(inside));
        result.push(')');
        rest = &rest[end + 1..];
    }
    result.push_str(rest);
    result
}

// ---------------------------------------------------------------------------
// Tables built from every file of the translation unit

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Scalar {
    Bool,
    I8,
    I8u,
    I16,
    I16u,
    I32,
    I32u,
    I64,
    I64u,
    F32,
    F64,
}

impl Scalar {
    /// The C builtin types bindgen converts, spelled as Clang prints them. Plain
    /// `char` is not one of them: its signedness depends on the target.
    fn of(name: &str) -> Option<Self> {
        Some(match name {
            "_Bool" => Self::Bool,
            "signed char" => Self::I8,
            "unsigned char" => Self::I8u,
            "short" => Self::I16,
            "unsigned short" => Self::I16u,
            "int" => Self::I32,
            "unsigned int" => Self::I32u,
            // LP64: `long` is 64 bits.
            "long" | "long long" => Self::I64,
            "unsigned long" | "unsigned long long" => Self::I64u,
            "float" => Self::F32,
            "double" => Self::F64,
            _ => return None,
        })
    }

    fn name(self) -> &'static str {
        match self {
            Self::Bool => "bool",
            Self::I8 => "i8",
            Self::I8u => "i8u",
            Self::I16 => "i16",
            Self::I16u => "i16u",
            Self::I32 => "i32",
            Self::I32u => "i32u",
            Self::I64 => "i64",
            Self::I64u => "i64u",
            Self::F32 => "f32",
            Self::F64 => "f64",
        }
    }

    /// The Tsuzuri type in each position. A `_Bool` result becomes `i8u` because C
    /// guarantees only its low 8 bits, while a Tsuzuri `bool` result reads all 32. ABI
    /// records widen `bool` and narrow integers to 32 bits, so fields take only 32- and
    /// 64-bit scalars, which C lays out the same way.
    fn in_role(self, role: Role) -> Option<&'static str> {
        match (self, role) {
            (Self::Bool, Role::Result) => Some("i8u"),
            (Self::Bool | Self::I8 | Self::I8u | Self::I16 | Self::I16u, Role::Field) => None,
            _ => Some(self.name()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Role {
    Parameter,
    Result,
    Field,
}

struct Typedef<'a> {
    spelled: &'a str,
    desugared: Option<&'a str>,
    /// An alignment or packing attribute changes the type's layout, which its
    /// spelling does not show.
    poisoned: bool,
}

struct Tables<'a> {
    typedefs: BTreeMap<&'a str, Typedef<'a>>,
    /// `enum TAG` (or `enum NAME` for an anonymous enum named by a typedef) → whether
    /// the enum is an `int`: every constant fits in i32, with no fixed underlying type
    /// and no packing.
    enums: BTreeMap<String, bool>,
    /// Anonymous struct, union, and enum declarations by id → the typedef that names
    /// them and where that name is.
    anonymous: BTreeMap<&'a str, (&'a str, (usize, usize))>,
    /// The ids of the implicit declarations Clang makes for library builtins.
    builtins: BTreeSet<&'a str>,
}

impl<'a> Tables<'a> {
    fn new(nodes: &'a [Value]) -> Self {
        let mut tables = Self {
            typedefs: BTreeMap::new(),
            enums: BTreeMap::new(),
            anonymous: BTreeMap::new(),
            builtins: nodes
                .iter()
                .filter(|node| kind(node) == "FunctionDecl" && flag(node, "isImplicit"))
                .filter_map(|node| text(node, "id"))
                .collect(),
        };
        for node in nodes.iter().filter(|node| kind(node) == "TypedefDecl") {
            let (spelled, desugared) = node_type(node);
            tables.typedefs.entry(name(node)).or_insert(Typedef {
                spelled,
                desugared,
                poisoned: has_attribute(node, LAYOUT_ATTRIBUTES),
            });
            let owned = children(node)
                .next()
                .and_then(|elaborated| elaborated.get("ownedTagDecl"));
            if let Some(tag) = owned
                && name(tag).is_empty()
                && let Some(id) = text(tag, "id")
            {
                tables
                    .anonymous
                    .entry(id)
                    .or_insert((name(node), position(node)));
            }
        }
        for node in nodes.iter().filter(|node| kind(node) == "EnumDecl") {
            let enumerators = tables.enumerators(node);
            // A forward declaration has no constants.
            let Some(key) = tables.enum_key(node).filter(|_| !enumerators.is_empty()) else {
                continue;
            };
            let int = node.get("fixedUnderlyingType").is_none()
                && !has_attribute(node, &["PackedAttr"])
                && enumerators.iter().all(|enumerator| {
                    enumerator
                        .value
                        .is_some_and(|value| i32::try_from(value).is_ok())
                });
            // Two enums spelled the same way (a tag and an anonymous enum's typedef)
            // are ambiguous, so neither converts.
            tables
                .enums
                .entry(key)
                .and_modify(|known| *known = false)
                .or_insert(int);
        }
        tables
    }

    fn enum_key(&self, node: &Value) -> Option<String> {
        let tag = match name(node) {
            "" => self.anonymous.get(text(node, "id")?)?.0,
            tag => tag,
        };
        Some(format!("enum {tag}"))
    }

    /// The constants of an enum with their values. C numbers a constant without an
    /// initializer as the previous one plus 1 (the first is 0); an initializer is a
    /// `ConstantExpr` with its value, maybe converted by an `ImplicitCastExpr` to the
    /// enumerator's type. Any other initializer leaves the value, and the values that
    /// follow from it, unknown.
    fn enumerators(&self, node: &'a Value) -> Vec<Enumerator<'a>> {
        let mut previous = Some(-1i128);
        let mut enumerators = Vec::new();
        for constant in children(node).filter(|child| kind(child) == "EnumConstantDecl") {
            let value = match children(constant).next() {
                None => previous.and_then(|value| value.checked_add(1)),
                Some(initializer) => self.constant_value(initializer, 0),
            };
            previous = value;
            enumerators.push(Enumerator {
                node: constant,
                value,
            });
        }
        enumerators
    }

    fn constant_value(&self, node: &Value, depth: usize) -> Option<i128> {
        match kind(node) {
            "ConstantExpr" => text(node, "value")?.parse().ok(),
            "ImplicitCastExpr"
                if depth < MAX_TYPE_NESTING
                    && matches!(text(node, "castKind"), Some("IntegralCast" | "NoOp")) =>
            {
                let value = self.constant_value(children(node).next()?, depth + 1)?;
                let (spelled, desugared) = node_type(node);
                let (ty, _) = self.c_type(spelled, desugared);
                let CType::Named(target) = ty else {
                    return None;
                };
                convert(value, &target)
            }
            _ => None,
        }
    }

    /// The type of a declaration with typedefs expanded: the spelling Clang printed,
    /// or its desugared spelling when this parser cannot read the printed one
    /// (`typeof`, for example).
    fn c_type(&self, spelled: &str, desugared: Option<&str>) -> (CType, Qualifiers) {
        let parsed = parse_type(spelled).or_else(|| desugared.and_then(parse_type));
        match parsed {
            Some((ty, qualifiers)) => self.resolve(ty, qualifiers, 0),
            None => (CType::Unsupported, Qualifiers::default()),
        }
    }

    /// Expands typedef names, at most `MAX_TYPEDEF_DEPTH` in a chain. The qualifiers of
    /// an expanded typedef join those of the place that names it.
    fn resolve(&self, ty: CType, qualifiers: Qualifiers, depth: usize) -> (CType, Qualifiers) {
        match ty {
            CType::Named(name) => match self.typedefs.get(name.as_str()) {
                None => (CType::Named(name), qualifiers),
                Some(typedef) if typedef.poisoned || depth >= MAX_TYPEDEF_DEPTH => {
                    (CType::Unsupported, qualifiers)
                }
                Some(typedef) => {
                    // An anonymous tag's typedef desugars to its own name.
                    let parsed = parse_type(typedef.spelled).or_else(|| {
                        typedef
                            .desugared
                            .filter(|desugared| *desugared != name)
                            .and_then(parse_type)
                    });
                    match parsed {
                        Some((inner, more)) => {
                            self.resolve(inner, qualifiers.union(more), depth + 1)
                        }
                        None => (CType::Unsupported, qualifiers),
                    }
                }
            },
            CType::Pointer(pointee, pointee_qualifiers) => {
                let (pointee, pointee_qualifiers) =
                    self.resolve(*pointee, pointee_qualifiers, depth);
                (
                    CType::Pointer(Box::new(pointee), pointee_qualifiers),
                    qualifiers,
                )
            }
            CType::Function(result, parameters) => {
                let result = self.resolve(*result, Qualifiers::default(), depth).0;
                let parameters = parameters
                    .into_iter()
                    .map(|parameter| self.resolve(parameter, Qualifiers::default(), depth).0)
                    .collect();
                (CType::Function(Box::new(result), parameters), qualifiers)
            }
            CType::Unsupported => (CType::Unsupported, qualifiers),
        }
    }

    /// The Tsuzuri scalar for a builtin or an `int` enum.
    fn scalar(&self, ty: &CType, role: Role) -> Option<&'static str> {
        let CType::Named(name) = ty else {
            return None;
        };
        if let Some(scalar) = Scalar::of(name) {
            return scalar.in_role(role);
        }
        (name.starts_with("enum ") && self.enums.get(name.as_str()) == Some(&true)).then_some("i32")
    }
}

struct Enumerator<'a> {
    node: &'a Value,
    value: Option<i128>,
}

/// C's conversion of an integer constant to an integer type (wrapping, as Clang does).
fn convert(value: i128, target: &str) -> Option<i128> {
    let (bits, signed) = match target {
        "signed char" => (8, true),
        "unsigned char" | "_Bool" => (8, false),
        "short" => (16, true),
        "unsigned short" => (16, false),
        "int" => (32, true),
        "unsigned int" => (32, false),
        "long" | "long long" => (64, true),
        "unsigned long" | "unsigned long long" => (64, false),
        _ => return None,
    };
    let modulus = 1i128 << bits;
    let wrapped = value.rem_euclid(modulus);
    Some(if signed && wrapped >= modulus / 2 {
        wrapped - modulus
    } else {
        wrapped
    })
}

// ---------------------------------------------------------------------------
// Names

fn ascii_identifier(name: &str) -> bool {
    let mut bytes = name.bytes();
    bytes
        .next()
        .is_some_and(|first| first == b'_' || first.is_ascii_alphabetic())
        && bytes.all(|byte| byte == b'_' || byte.is_ascii_alphanumeric())
}

/// `glClearColor` → `gl_clear_color`: an underscore before each uppercase letter that
/// follows a lowercase letter or a digit, then ASCII lowercase.
fn snake_case(name: &str) -> String {
    let mut result = String::with_capacity(name.len() + 4);
    let mut previous: Option<char> = None;
    for character in name.chars() {
        if character.is_ascii_uppercase()
            && previous
                .is_some_and(|previous| previous.is_ascii_lowercase() || previous.is_ascii_digit())
        {
            result.push('_');
        }
        result.push(character.to_ascii_lowercase());
        previous = Some(character);
    }
    result
}

/// `point_t` → `PointT`, `SDL_Rect` → `SDLRect`; a `C` prefix when the result would
/// not start with an uppercase letter.
fn pascal_case(name: &str) -> String {
    let mut result: String = name
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            let first = characters.next().map(|first| first.to_ascii_uppercase());
            first.into_iter().chain(characters).collect::<String>()
        })
        .collect();
    if !result.starts_with(|first: char| first.is_ascii_uppercase()) {
        result.insert(0, 'C');
    }
    result
}

/// Whether the lexer reads `name` as a plain identifier rather than a keyword.
fn plain_identifier(name: &str) -> bool {
    crate::lexer::lex(name).is_ok_and(|tokens| {
        matches!(
            tokens.as_slice(),
            [first, ..] if first.kind == crate::syntax::TokenKind::Ident(name.to_owned())
        ) && tokens.len() == 2
    })
}

/// A function or constant name the checker accepts: keywords, `_`, and the
/// unqualified builtins (`sqrt`, `abs`, ...) get a trailing `_`.
fn value_name(name: String) -> String {
    if !plain_identifier(&name)
        || name == "_"
        || crate::check::Builtin::ALL
            .iter()
            .any(|builtin| builtin.name() == name)
    {
        name + "_"
    } else {
        name
    }
}

/// A record, alias, or extern type name the checker accepts.
fn type_name(name: String) -> String {
    if !plain_identifier(&name) || crate::check::reserved_type_name(&name) {
        name + "_"
    } else {
        name
    }
}

fn field_name(name: &str) -> String {
    value_name(snake_case(name))
}

/// Comment text with every character outside 0x20–0x7E replaced by `?`, so a file name,
/// a type, or a version cannot start a new line of generated code.
fn sanitize(text: &str) -> String {
    text.chars()
        .map(|character| {
            if (' '..='~').contains(&character) {
                character
            } else {
                '?'
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Output

/// The decision for a declaration that defines a Tsuzuri type, made before any line
/// is written because functions may name a struct declared after them.
enum TypeDecision {
    Line(String),
    /// The C name, the reason, and where to report it when not at the declaration.
    Skip(String, String, Option<(usize, usize)>),
}

struct Emitter<'t, 'a> {
    tables: &'t Tables<'a>,
    /// The prefix the object format adds to C symbols (`_` on Mach-O).
    symbol_prefix: &'static str,
    values: BTreeSet<String>,
    types: BTreeSet<String>,
    /// `TAG` → the generated record of `struct TAG`.
    records: BTreeMap<&'a str, String>,
    decisions: BTreeMap<usize, TypeDecision>,
    lines: Vec<String>,
    skipped: Vec<Skipped>,
}

impl<'t, 'a> Emitter<'t, 'a> {
    fn new(tables: &'t Tables<'a>, target: &str) -> Self {
        Self {
            tables,
            symbol_prefix: if target.contains("apple") || target.contains("darwin") {
                "_"
            } else {
                ""
            },
            values: BTreeSet::new(),
            types: BTreeSet::new(),
            records: BTreeMap::new(),
            decisions: BTreeMap::new(),
            lines: Vec::new(),
            skipped: Vec::new(),
        }
    }

    /// Names the types of the header in header order: records and type aliases share
    /// one namespace, and a later declaration that collides is skipped.
    fn collect_types(&mut self, declarations: &[Declaration<'a>]) {
        for (index, declaration) in declarations.iter().enumerate() {
            if !declaration.owned {
                continue;
            }
            let decision = match declaration.kind {
                "RecordDecl" => self.record(declaration.node),
                "TypedefDecl" => self.alias(declaration.node),
                _ => None,
            };
            if let Some(decision) = decision {
                self.decisions.insert(index, decision);
            }
        }
    }

    fn record(&mut self, node: &'a Value) -> Option<TypeDecision> {
        if !flag(node, "completeDefinition") {
            return None;
        }
        let tag = name(node);
        let skip = |name: &str, reason: &str| {
            Some(TypeDecision::Skip(name.to_owned(), reason.to_owned(), None))
        };
        if text(node, "tagUsed") == Some("union") {
            let shown = if tag.is_empty() {
                "(anonymous union)"
            } else {
                tag
            };
            return skip(shown, "C union");
        }
        if text(node, "tagUsed") != Some("struct") {
            return None;
        }
        if tag.is_empty() {
            // Reported at the typedef that names it, if any.
            let named = text(node, "id").and_then(|id| self.tables.anonymous.get(id));
            return Some(TypeDecision::Skip(
                named
                    .map_or("(anonymous struct)", |(name, _)| name)
                    .to_owned(),
                "anonymous struct; give the struct a tag".to_owned(),
                named.map(|(_, at)| *at),
            ));
        }
        if !ascii_identifier(tag) {
            return skip(tag, "name is not an ASCII C identifier");
        }
        if has_attribute(node, LAYOUT_ATTRIBUTES) {
            return skip(tag, "struct has a packing or alignment attribute");
        }
        let fields: Vec<_> = children(node)
            .filter(|child| kind(child) == "FieldDecl")
            .collect();
        if fields.is_empty() {
            return skip(tag, "struct has no fields");
        }
        let field_label = |field: &Value| match name(field) {
            "" => "(anonymous)".to_owned(),
            name => name.to_owned(),
        };
        if let Some(field) = fields.iter().find(|field| flag(field, "isBitfield")) {
            return skip(tag, &format!("bit-field '{}'", field_label(field)));
        }
        if let Some(field) = fields
            .iter()
            .find(|field| has_attribute(field, LAYOUT_ATTRIBUTES))
        {
            return skip(
                tag,
                &format!(
                    "field '{}' has an alignment or packing attribute",
                    field_label(field)
                ),
            );
        }
        let mut converted = Vec::new();
        for field in &fields {
            let (spelled, desugared) = node_type(field);
            let (ty, _) = self.tables.c_type(spelled, desugared);
            let Some(scalar) = self.tables.scalar(&ty, Role::Field) else {
                return skip(
                    tag,
                    &format!(
                        "field '{}' has unsupported type '{}'",
                        field_label(field),
                        scrub(spelled)
                    ),
                );
            };
            converted.push((name(field), scalar));
        }
        let mut names = BTreeSet::new();
        let mut rendered = Vec::new();
        for (field, scalar) in converted {
            if !ascii_identifier(field) {
                return skip(
                    tag,
                    &format!("field '{field}' is not an ASCII C identifier"),
                );
            }
            let converted = field_name(field);
            if !names.insert(converted.clone()) {
                return skip(
                    tag,
                    &format!("field '{field}' collides with an earlier field as '{converted}'"),
                );
            }
            rendered.push(format!("{converted}: {scalar}"));
        }
        let record = type_name(pascal_case(tag));
        if !self.types.insert(record.clone()) {
            return skip(
                tag,
                &format!("name '{record}' collides with an earlier declaration"),
            );
        }
        self.records.insert(tag, record.clone());
        Some(TypeDecision::Line(format!(
            "record {record} {{ {} }}",
            rendered.join(", ")
        )))
    }

    /// A type alias for a typedef that resolves to a scalar; other typedefs produce
    /// nothing, because signatures use the resolved types.
    fn alias(&mut self, node: &'a Value) -> Option<TypeDecision> {
        let typedef = name(node);
        let (ty, _) = self.tables.c_type(typedef, None);
        let CType::Named(resolved) = ty else {
            return None;
        };
        let scalar = Scalar::of(&resolved)?.name();
        if !ascii_identifier(typedef) {
            return Some(TypeDecision::Skip(
                typedef.to_owned(),
                "name is not an ASCII C identifier".to_owned(),
                None,
            ));
        }
        let alias = type_name(pascal_case(typedef));
        if !self.types.insert(alias.clone()) {
            return Some(TypeDecision::Skip(
                typedef.to_owned(),
                format!("name '{alias}' collides with an earlier declaration"),
                None,
            ));
        }
        Some(TypeDecision::Line(format!("type {alias} = {scalar}")))
    }

    fn declaration(&mut self, index: usize, declaration: &Declaration<'a>) -> Result<(), String> {
        let node = declaration.node;
        let at = (declaration.offset, declaration.length);
        match declaration.kind {
            "RecordDecl" | "TypedefDecl" => match self.decisions.remove(&index) {
                Some(TypeDecision::Line(line)) => self.lines.push(line),
                Some(TypeDecision::Skip(name, reason, place)) => {
                    self.skip(&name, reason, place.unwrap_or(at))
                }
                None => {}
            },
            "EnumDecl" => self.constants(node),
            "FunctionDecl" => self.function(node, at)?,
            "VarDecl" => self.skip(name(node), "global variable".into(), at),
            _ => {}
        }
        Ok(())
    }

    fn constants(&mut self, node: &'a Value) {
        for enumerator in self.tables.enumerators(node) {
            let constant = name(enumerator.node);
            let at = position(enumerator.node);
            if !ascii_identifier(constant) {
                self.skip(constant, "name is not an ASCII C identifier".into(), at);
                continue;
            }
            let Some(value) = enumerator.value else {
                self.skip(
                    constant,
                    "enumerator value is not an integer constant in the clang AST".into(),
                    at,
                );
                continue;
            };
            if i32::try_from(value).is_err() {
                self.skip(
                    constant,
                    format!("enumerator value {value} does not fit in i32"),
                    at,
                );
                continue;
            }
            let tsuzuri = value_name(constant.to_owned());
            if !self.values.insert(tsuzuri.clone()) {
                self.skip(
                    constant,
                    format!("name '{tsuzuri}' collides with an earlier declaration"),
                    at,
                );
                continue;
            }
            self.lines.push(format!("const {tsuzuri}: i32 = {value}"));
        }
    }

    fn function(&mut self, node: &'a Value, at: (usize, usize)) -> Result<(), String> {
        // A redeclaration produces nothing. Clang declares library builtins such as
        // `sqrt` implicitly at their first mention, so a header's own declaration of
        // one names that implicit declaration as its previous one and still counts.
        if text(node, "previousDecl")
            .is_some_and(|previous| !self.tables.builtins.contains(previous))
        {
            return Ok(());
        }
        let symbol = name(node);
        match self.function_line(node, symbol) {
            Ok(line) => self.lines.push(line),
            Err(reason) => self.skip(symbol, reason, at),
        }
        Ok(())
    }

    /// The `extern` line for a function, or why it cannot have one. The checks run in
    /// the order of the `W2002` reasons in the language reference.
    fn function_line(&mut self, node: &'a Value, symbol: &str) -> Result<String, String> {
        if text(node, "storageClass") == Some("static") {
            return Err("function has internal linkage (static)".into());
        }
        if flag(node, "inline") {
            return Err("inline function has no guaranteed external definition".into());
        }
        if flag(node, "variadic") {
            return Err("variadic function".into());
        }
        let (spelled, _) = node_type(node);
        let shape = function_shape(spelled)
            .ok_or_else(|| format!("function type '{}' is not understood", scrub(spelled)))?;
        if !shape.prototype {
            return Err("function has no prototype".into());
        }
        if !ascii_identifier(symbol) {
            return Err("name is not an ASCII C identifier".into());
        }
        if crate::abi::RESERVED_SYMBOL_PREFIXES
            .iter()
            .any(|prefix| symbol.starts_with(prefix))
        {
            return Err("symbol uses the reserved tz_, tsuzuri, or __ prefix".into());
        }
        if crate::abi::RESERVED_HOST_SYMBOLS.contains(&symbol) {
            return Err("symbol is reserved by the Tsuzuri runtime".into());
        }
        if symbol.len() > 255 {
            return Err("symbol is longer than 255 bytes".into());
        }
        // An asm label or `overloadable` gives the function another symbol.
        let renamed =
            match text(node, "mangledName") {
                Some(mangled) => (mangled != format!("{}{symbol}", self.symbol_prefix))
                    .then(|| mangled.to_owned()),
                None => has_attribute(node, &["AsmLabelAttr", "OverloadableAttr"])
                    .then(|| "?".to_owned()),
            };
        if let Some(mangled) = renamed {
            return Err(format!(
                "symbol is renamed to '{}' by an asm label or overloading",
                sanitize(&mangled)
            ));
        }
        if let Some(attribute) = shape
            .attributes
            .iter()
            .find(|attribute| !matches!(attribute.as_str(), "noreturn" | "__noreturn__"))
        {
            return Err(format!(
                "function type has the attribute '{attribute}', which may change its calling convention"
            ));
        }
        let mut parameters = Vec::new();
        for (index, parameter) in children(node)
            .filter(|child| kind(child) == "ParmVarDecl")
            .enumerate()
        {
            let number = index + 1;
            if has_attribute(parameter, &["PassObjectSizeAttr"]) {
                return Err(format!(
                    "parameter {number} has the pass_object_size attribute, which adds a hidden argument"
                ));
            }
            let (spelled, desugared) = node_type(parameter);
            parameters.push(self.parameter(spelled, desugared).ok_or_else(|| {
                format!(
                    "parameter {number} has unsupported type '{}'",
                    scrub(spelled)
                )
            })?);
        }
        let result = match &shape.result {
            Ok(spelled) => self.result(spelled),
            Err(_) => None,
        }
        .ok_or_else(|| {
            let (Ok(spelled) | Err(spelled)) = &shape.result;
            format!("result has unsupported type '{}'", scrub(spelled))
        })?;
        let tsuzuri = value_name(snake_case(symbol));
        if !self.values.insert(tsuzuri.clone()) {
            return Err(format!(
                "name '{tsuzuri}' collides with an earlier declaration"
            ));
        }
        Ok(render_function(symbol, &tsuzuri, &parameters, &result))
    }

    fn parameter(&self, spelled: &str, desugared: Option<&str>) -> Option<String> {
        let (ty, _) = self.tables.c_type(spelled, desugared);
        if let Some(scalar) = self.tables.scalar(&ty, Role::Parameter) {
            return Some(scalar.to_owned());
        }
        // `const struct TAG *` borrows a generated record. Without `const` the host
        // could write into the temporary copy the ABI passes, so it is not converted.
        if let CType::Pointer(pointee, qualifiers) = &ty
            && qualifiers.constant
            && !qualifiers.volatile
            && let CType::Named(pointee) = pointee.as_ref()
            && let Some(tag) = pointee.strip_prefix("struct ")
            && let Some(record) = self.records.get(tag)
        {
            return Some(format!("ref {record}"));
        }
        None
    }

    fn result(&self, spelled: &str) -> Option<String> {
        let (ty, _) = self.tables.c_type(spelled, None);
        if ty == CType::Named("void".into()) {
            return Some("unit".into());
        }
        self.tables.scalar(&ty, Role::Result).map(str::to_owned)
    }

    fn skip(&mut self, name: &str, reason: String, (offset, length): (usize, usize)) {
        self.lines.push(format!(
            "// skipped {}: {}",
            sanitize(name),
            sanitize(&reason)
        ));
        self.skipped.push(Skipped {
            name: name.to_owned(),
            reason,
            offset,
            length,
        });
    }

    fn finish(self, header: &HeaderInfo) -> Generated {
        let mut text = format!(
            "{MARKER}\n// header: {} sha256={}\n// clang: {}\n// target: {}\n",
            sanitize(header.file_name),
            sanitize(header.sha256),
            sanitize(header.clang_version),
            sanitize(header.target),
        );
        if !self.lines.is_empty() {
            text.push('\n');
            for line in &self.lines {
                text.push_str(line);
                text.push('\n');
            }
        }
        Generated {
            text,
            skipped: self.skipped,
        }
    }
}

/// The one place that spells an E12 link-named extern declaration.
fn render_function(symbol: &str, name: &str, parameters: &[String], result: &str) -> String {
    let mut signature: Vec<&str> = if parameters.is_empty() {
        vec!["unit"]
    } else {
        parameters.iter().map(String::as_str).collect()
    };
    signature.push(result);
    format!(
        "extern \"{symbol}\" def {name} :: {}",
        signature.join(" -> ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parsed(text: &str) -> CType {
        parse_type(text).map_or(CType::Unsupported, |(ty, _)| ty)
    }

    #[test]
    fn parses_clang_type_spellings() {
        let named = |name: &str| CType::Named(name.into());
        let constant = Qualifiers {
            constant: true,
            volatile: false,
        };
        assert_eq!(parsed("unsigned long"), named("unsigned long"));
        assert_eq!(parse_type("const int"), Some((named("int"), constant)));
        assert_eq!(
            parsed("const struct point *const"),
            CType::Pointer(Box::new(named("struct point")), constant)
        );
        assert_eq!(
            parsed("int * _Nonnull"),
            CType::Pointer(Box::new(named("int")), Qualifiers::default())
        );
        assert_eq!(
            parsed("int (*)(int, const char *)"),
            CType::Pointer(
                Box::new(CType::Function(
                    Box::new(named("int")),
                    vec![
                        named("int"),
                        CType::Pointer(Box::new(named("char")), constant)
                    ]
                )),
                Qualifiers::default()
            )
        );
        for unsupported in [
            "int (^)(int)",
            "int [4]",
            "struct (unnamed struct at /h/a.h:1:1)",
            "__attribute__((__vector_size__(4 * sizeof(int)))) int",
            "typeof (sizeof (0))",
        ] {
            assert!(parse_type(unsupported).is_none(), "{unsupported}");
        }
        assert_eq!(
            parsed("int (*)(int, ...)"),
            CType::Pointer(Box::new(CType::Unsupported), Qualifiers::default())
        );
    }

    #[test]
    fn splits_function_types() {
        let shape = function_shape("struct opaque *(void)").unwrap();
        assert_eq!(shape.result, Ok("struct opaque *".into()));
        assert!(shape.prototype && shape.attributes.is_empty());
        let shape = function_shape("void (int) __attribute__((noreturn))").unwrap();
        assert_eq!(shape.attributes, ["noreturn"]);
        let shape = function_shape("__attribute__((preserve_most)) int (int)").unwrap();
        assert_eq!(shape.result, Ok("int".into()));
        assert_eq!(shape.attributes, ["preserve_most"]);
        assert!(!function_shape("int ()").unwrap().prototype);
        assert_eq!(
            function_shape("int (*(int))(void)").unwrap().result,
            Err("int (*)(void)".into())
        );
        let anonymous = function_shape("struct (unnamed struct at /h/a.h:1:1) (void)").unwrap();
        assert_eq!(
            anonymous.result,
            Ok("struct (unnamed struct at /h/a.h:1:1)".into())
        );
        assert_eq!(
            scrub("struct (unnamed struct at /h/a.h:1:1) *"),
            "struct (unnamed struct) *"
        );
    }

    #[test]
    fn converts_enum_initializer_values_like_c() {
        assert_eq!(convert(4294967295, "int"), Some(-1));
        assert_eq!(convert(-1, "unsigned int"), Some(4294967295));
        assert_eq!(convert(5, "long double"), None);
    }
}
