//! Typed host bindings generated from the public ABI (E13).
//!
//! Every generator reads one descriptor table of the module's exports, host imports and records,
//! so the bindings of all host languages agree with `--emit header` and with the C-ABI wrappers
//! of `src/llvm_abi.rs`. The JavaScript glue embeds the table and resolves it once when it loads;
//! the conversions live in `src/runtime/bindings.mjs`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::{Map, Value, json};

use crate::abi::Buffer;
use crate::check::{CheckedFunction, CheckedModule, HostImport, Type, TypedExprKind};
use crate::llvm::fixed_length;
use crate::llvm::host_abi::{handle_c_name, record_layout, record_name};

#[path = "bindings_native.rs"]
mod native;
pub use native::{cpp, csharp, python};

/// The version of the descriptor table and of the runtime contract of the generated files.
pub const ABI_VERSION: u32 = 1;

/// The runtime that every JavaScript glue appends after its table.
const RUNTIME_CORE: &str = include_str!("runtime/bindings-core.mjs");
/// The `load` of one instance.
const RUNTIME_SINGLE: &str = include_str!("runtime/bindings.mjs");
/// The `load` of a thread pool on Web Workers (`--wasm-feature threads`).
const RUNTIME_THREADS: &str = include_str!("runtime/bindings-threads.mjs");

/// Which JavaScript glue `--emit bindings-js` writes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum JsFlavor {
    /// One instance; calls return their results.
    Single,
    /// A module of `--wasm-feature threads` on Web Workers; calls return promises.
    Threads,
}

/// The traps, the same in every flavor of the TypeScript declarations.
const TRAP_DECLARATIONS: &str = r#"export interface TrapInfo { reason: "trap" | "stack"; site: number; kind?: string; path?: string; line?: number; column?: number }
export interface TrapSite { id: number; kind: string; path: string; span: { line: number; column: number } }
export declare class TsuzuriTrap extends Error { readonly trap: TrapInfo }
"#;

/// The rest of the fixed declarations of one instance, after the generated interfaces.
const DECLARATIONS: &str = r#"export interface Borrowed<T> { readonly length: number; view(): T }
export interface Bindings {
  readonly exports: Exports;
  withBorrowed<R>(kind: "i64", length: number, callback: (buffer: Borrowed<BigInt64Array>) => R): R;
  withBorrowed<R>(kind: "f64", length: number, callback: (buffer: Borrowed<Float64Array>) => R): R;
  withBorrowed<R>(kind: "ubyte", length: number, callback: (buffer: Borrowed<Uint8Array>) => R): R;
  ready(): Promise<void>;
}
"#;

/// The first line of a generated file, after the comment marker of its language.
fn banner(comment: &str) -> String {
    format!(
        "{comment} Generated by Tsuzuri {}. Bindings ABI {ABI_VERSION}. Do not edit.\n",
        env!("CARGO_PKG_VERSION")
    )
}

/// The `export def` functions in name order.
fn exports(module: &CheckedModule) -> Vec<&CheckedFunction> {
    let mut exports: Vec<_> = module
        .functions
        .iter()
        .filter(|function| function.exported)
        .collect();
    exports.sort_by(|left, right| left.name.cmp(&right.name));
    exports
}

/// The host imports that the exports and the entry reach, by WASM import name. A name names one
/// import: an explicit symbol has one module and type (E12), and implicit names contain a dot.
fn imports(module: &CheckedModule) -> BTreeMap<&str, (&HostImport, &CheckedFunction)> {
    let roots: Vec<_> = module
        .functions
        .iter()
        .enumerate()
        .filter(|(id, function)| function.exported || module.entry == Some(*id))
        .map(|(id, _)| id)
        .collect();
    crate::llvm::reachable_functions(module, Some(&roots), false)
        .into_iter()
        .filter_map(|id| {
            let function = &module.functions[id];
            match &function.body.kind {
                TypedExprKind::HostCall(import, _) => {
                    Some((import.wasm_name.as_str(), (import.as_ref(), function)))
                }
                _ => None,
            }
        })
        .collect()
}

/// The ABI parameters of an import or a callback: `unit` has no C or WASM parameter.
fn host_parameters(parameters: &[Type]) -> impl Iterator<Item = (usize, &Type)> {
    parameters
        .iter()
        .enumerate()
        .filter(|(_, ty)| **ty != Type::Unit)
}

/// The descriptor of an ABI type in the table.
fn descriptor(ty: &Type, module: &CheckedModule) -> Value {
    match ty {
        Type::Integer(bits, signed) => json!(format!("i{bits}{}", if *signed { "" } else { "u" })),
        Type::Binary(bits) => json!(format!("f{bits}")),
        Type::Bool => json!("bool"),
        Type::Unit => json!("unit"),
        Type::Handle(name) => json!(format!("handle:{}", handle_c_name(name))),
        Type::Record(..) => json!(format!("record:{}", record_name(ty, module))),
        Type::FixedArray(element, _) => {
            json!(["array", descriptor(element, module), fixed_length(ty)])
        }
        Type::Function(parameters, result) => json!([
            "callback",
            host_parameters(parameters)
                .map(|(_, ty)| descriptor(ty, module))
                .collect::<Vec<_>>(),
            descriptor(result, module)
        ]),
        Type::Reference(inner, false) => match Buffer::of(inner) {
            Some(buffer) => json!(format!("slice:{}", buffer.name())),
            None => descriptor(inner, module),
        },
        _ => match Buffer::of(ty) {
            Some(buffer) => json!(format!("buffer:{}", buffer.name())),
            None => unreachable!("ABI type checked"),
        },
    }
}

/// The record types of the signatures, nested records included, by `record_name`.
fn records(module: &CheckedModule) -> BTreeMap<String, Type> {
    fn visit(ty: &Type, module: &CheckedModule, records: &mut BTreeMap<String, Type>) {
        match ty {
            Type::Reference(inner, _) => visit(inner, module, records),
            Type::Record(id, arguments)
                if records
                    .insert(record_name(ty, module), ty.clone())
                    .is_none() =>
            {
                for field in module.types().record_fields(*id, arguments) {
                    visit(&field, module, records);
                }
            }
            _ => {}
        }
    }
    let mut records = BTreeMap::new();
    for function in signatures(module) {
        for ty in function
            .signature
            .parameters
            .iter()
            .chain([&function.signature.result])
        {
            visit(ty, module, &mut records);
        }
    }
    records
}

/// The handle types of the signatures, callbacks included, by C name.
fn handles(module: &CheckedModule) -> BTreeSet<String> {
    fn visit(ty: &Type, handles: &mut BTreeSet<String>) {
        match ty {
            Type::Handle(name) => {
                handles.insert(handle_c_name(name));
            }
            Type::Reference(inner, _) => visit(inner, handles),
            Type::Function(parameters, result) => {
                parameters.iter().for_each(|ty| visit(ty, handles));
                visit(result, handles);
            }
            _ => {}
        }
    }
    let mut handles = BTreeSet::new();
    for function in signatures(module) {
        for ty in function
            .signature
            .parameters
            .iter()
            .chain([&function.signature.result])
        {
            visit(ty, &mut handles);
        }
    }
    handles
}

/// The functions whose signatures the bindings describe: the exports, then the reached imports.
fn signatures(module: &CheckedModule) -> Vec<&CheckedFunction> {
    let mut functions = exports(module);
    functions.extend(imports(module).into_values().map(|(_, function)| function));
    functions
}

/// The fields of a record with their byte offsets in the normalized C layout of `record_layout`.
fn fields(ty: &Type, module: &CheckedModule) -> Vec<(String, usize, Type)> {
    let Type::Record(id, arguments) = ty else {
        unreachable!("ABI record checked")
    };
    let mut offset = 0usize;
    module.records[*id]
        .fields
        .iter()
        .zip(module.types().record_fields(*id, arguments))
        .map(|((name, _), field)| {
            let (size, alignment) = record_layout(&field, module);
            offset = offset.div_ceil(alignment) * alignment;
            let entry = (name.clone(), offset, field);
            offset += size;
            entry
        })
        .collect()
}

/// The descriptor table: `abi`, `hostAbi`, the exports `[name, parameters, result]` and imports
/// `[name, module, parameters, result]` in byte order of their names, and the records by name.
pub fn table(module: &CheckedModule) -> Value {
    let exports: Vec<_> = exports(module)
        .into_iter()
        .map(|function| {
            json!([
                function.name,
                function
                    .signature
                    .parameters
                    .iter()
                    .map(|ty| descriptor(ty, module))
                    .collect::<Vec<_>>(),
                descriptor(&function.signature.result, module)
            ])
        })
        .collect();
    let imports: Vec<_> = imports(module)
        .into_iter()
        .map(|(name, (import, function))| {
            json!([
                name,
                import.wasm_module,
                host_parameters(&function.signature.parameters)
                    .map(|(_, ty)| descriptor(ty, module))
                    .collect::<Vec<_>>(),
                descriptor(&function.signature.result, module)
            ])
        })
        .collect();
    let records: Map<String, Value> = records(module)
        .into_iter()
        .map(|(name, ty)| {
            let (size, align) = record_layout(&ty, module);
            let fields: Vec<_> = fields(&ty, module)
                .into_iter()
                .map(|(field, offset, ty)| json!([field, offset, descriptor(&ty, module)]))
                .collect();
            (
                name,
                json!({ "size": size, "align": align, "fields": fields }),
            )
        })
        .collect();
    json!({
        "abi": ABI_VERSION,
        "hostAbi": crate::llvm::uses_host_abi(module),
        "exports": exports,
        "imports": imports,
        "records": records,
    })
}

/// The rest of the fixed declarations of a thread pool.
const THREADS_DECLARATIONS: &str = r#"export interface ImportsContext { readonly workerId: number; readonly data: unknown }
export type CreateImports = (context: ImportsContext) => Imports | Promise<Imports>;
export interface ThreadBindings {
  readonly exports: Exports;
  readonly workerCount: number;
  close(): Promise<void>;
}
"#;

/// The JavaScript module of `--emit bindings-js`: the banner, the table and the runtime.
pub fn javascript(module: &CheckedModule) -> String {
    javascript_for(module, JsFlavor::Single)
}

/// The JavaScript module of `--emit bindings-js` for one flavor.
pub fn javascript_for(module: &CheckedModule, flavor: JsFlavor) -> String {
    let tail = match flavor {
        JsFlavor::Single => RUNTIME_SINGLE,
        JsFlavor::Threads => RUNTIME_THREADS,
    };
    format!(
        "{}const TABLE = {};\n{RUNTIME_CORE}{tail}",
        banner("//"),
        table(module)
    )
}

/// The TypeScript type of `ty`. `input` is the direction from JavaScript into the module: export
/// arguments, import results and callback arguments; `borrow` admits `Borrowed` buffers for slices.
fn typescript_type(ty: &Type, module: &CheckedModule, input: bool) -> String {
    typescript_type_with(ty, module, input, true)
}

fn typescript_type_with(ty: &Type, module: &CheckedModule, input: bool, borrow: bool) -> String {
    match ty {
        Type::Integer(64, _) => "bigint".into(),
        Type::Integer(..) | Type::Binary(_) => "number".into(),
        Type::Bool => "boolean".into(),
        Type::Unit => "void".into(),
        Type::Handle(name) => handle_c_name(name),
        Type::Record(..) => record_name(ty, module),
        Type::FixedArray(element, _) => {
            format!("readonly {}[]", typescript_type(element, module, input))
        }
        Type::Function(parameters, result) => format!(
            "({}) => {}",
            host_parameters(parameters)
                .map(|(index, ty)| format!("arg{index}: {}", typescript_type(ty, module, true)))
                .collect::<Vec<_>>()
                .join(", "),
            typescript_type(result, module, false)
        ),
        Type::Reference(inner, false) => match Buffer::of(inner) {
            Some(Buffer::String | Buffer::Utf8String) => "string".into(),
            Some(buffer) if input && borrow => {
                let array = typed_array(buffer);
                format!("{array} | Borrowed<{array}>")
            }
            Some(buffer) => typed_array(buffer).into(),
            None => typescript_type(inner, module, input),
        },
        _ => match Buffer::of(ty) {
            Some(Buffer::String | Buffer::Utf8String) => "string".into(),
            Some(buffer) => typed_array(buffer).into(),
            None => unreachable!("ABI type checked"),
        },
    }
}

fn typed_array(buffer: Buffer) -> &'static str {
    match buffer {
        Buffer::I64 => "BigInt64Array",
        Buffer::F64 => "Float64Array",
        Buffer::UByte => "Uint8Array",
        Buffer::String | Buffer::Utf8String => unreachable!("strings are JavaScript strings"),
    }
}

/// A property name as TypeScript writes it: quoted unless it is an identifier.
fn typescript_property(name: &str) -> String {
    let mut characters = name.chars();
    let identifier = characters
        .next()
        .is_some_and(|first| first == '_' || first == '$' || first.is_ascii_alphabetic())
        && characters.all(|next| next == '_' || next == '$' || next.is_ascii_alphanumeric());
    if identifier {
        name.into()
    } else {
        Value::String(name.into()).to_string()
    }
}

/// The TypeScript declarations `<name>.d.mts` of `--emit bindings-js`.
pub fn declarations(module: &CheckedModule) -> String {
    declarations_for(module, JsFlavor::Single)
}

/// The TypeScript declarations of `--emit bindings-js` for one flavor.
pub fn declarations_for(module: &CheckedModule, flavor: JsFlavor) -> String {
    let threads = flavor == JsFlavor::Threads;
    let mut output = banner("//");
    for (name, ty) in records(module) {
        let fields: Vec<_> = fields(&ty, module)
            .into_iter()
            .map(|(field, _, ty)| {
                format!(
                    "{}: {}",
                    typescript_property(&field),
                    typescript_type(&ty, module, true)
                )
            })
            .collect();
        if fields.is_empty() {
            let _ = writeln!(output, "export interface {name} {{}}");
        } else {
            let _ = writeln!(
                output,
                "export interface {name} {{ {} }}",
                fields.join("; ")
            );
        }
    }
    for name in handles(module) {
        let _ = writeln!(
            output,
            "export type {name} = number & {{ readonly __tsuzuri: \"{name}\" }};"
        );
    }
    output.push_str("export interface Exports {\n");
    for function in exports(module) {
        let parameters: Vec<_> = function
            .signature
            .parameters
            .iter()
            .enumerate()
            .map(|(index, ty)| {
                format!(
                    "arg{index}: {}",
                    typescript_type_with(ty, module, true, !threads)
                )
            })
            .collect();
        let result = typescript_type(&function.signature.result, module, false);
        let _ = writeln!(
            output,
            "  {}({}): {};",
            typescript_property(&function.name),
            parameters.join(", "),
            if threads {
                format!("Promise<{result}>")
            } else {
                result
            }
        );
    }
    output.push_str("}\n");
    let imports = imports(module);
    if imports.is_empty() {
        output.push_str("export interface Imports {}\n");
    } else {
        output.push_str("export interface Imports {\n");
        for (name, (_, function)) in &imports {
            let parameters: Vec<_> = host_parameters(&function.signature.parameters)
                .map(|(index, ty)| format!("arg{index}: {}", typescript_type(ty, module, false)))
                .collect();
            let _ = writeln!(
                output,
                "  {}({}): {};",
                Value::String((*name).into()),
                parameters.join(", "),
                typescript_type(&function.signature.result, module, true)
            );
        }
        output.push_str("}\n");
    }
    output.push_str(TRAP_DECLARATIONS);
    let (options, bindings) = if threads {
        output.push_str(THREADS_DECLARATIONS);
        let pool = "importData?: unknown; workers?: number; memory?: WebAssembly.Memory; sites?: readonly TrapSite[]";
        let options = if imports.is_empty() {
            format!("options?: {{ importsModule?: string | URL; {pool} }}")
        } else {
            format!("options: {{ importsModule: string | URL; {pool} }}")
        };
        (options, "ThreadBindings")
    } else {
        output.push_str(DECLARATIONS);
        let options = if imports.is_empty() {
            "options?: { sites?: readonly TrapSite[] }".to_owned()
        } else {
            "options: { imports: Imports; sites?: readonly TrapSite[] }".to_owned()
        };
        (options, "Bindings")
    };
    let _ = writeln!(
        output,
        "export declare function load(source: ArrayBuffer | ArrayBufferView | WebAssembly.Module, {options}): Promise<{bindings}>;"
    );
    output
}
