//! `tsuzuri bindgen` (E11): Tsuzuri declarations generated from a C header.
//!
//! The driver runs Clang and passes its JSON AST and its `-E -dD` output to
//! [`generate_with`]. Everything in this module is a pure function of its input, so
//! the same Clang, header, include directories, and annotations always give the same
//! bytes. A declaration is generated only when its C ABI provably matches the Tsuzuri
//! host ABI: Clang's type spelling, with typedefs expanded, must match a fixed table
//! exactly, and only LP64 targets are accepted. Pointer-and-length buffers and
//! ownership-taking handle parameters need an explicit annotation (`--buffer`,
//! `--consume`), because a C declaration does not say either. Every other declaration
//! of the header becomes a `// skipped` line and a `W2002` warning instead of a guess.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::{OsStr, OsString};
use std::ops::Range;
use std::path::PathBuf;

use serde_json::Value;

/// The first line of every generated file; bindgen overwrites only files that start with it.
pub const MARKER: &str = "// Generated by tsuzuri bindgen. Do not edit.";
/// The most bytes bindgen reads from one Clang invocation.
pub const MAX_AST_BYTES: usize = 256 * 1024 * 1024;
const MAX_TYPEDEF_DEPTH: usize = 32;
const MAX_TYPE_NESTING: usize = 32;
const OPTIONS: &str = "bindgen accepts only -o, --include-dir, --buffer, --consume, and --json";
const BUFFER_USAGE: &str = "--buffer takes FUNCTION:POINTER:LENGTH with C names or 1-based parameter positions, such as --buffer sum:values:count";
const CONSUME_USAGE: &str = "--consume takes FUNCTION:PARAMETER with a C name or a 1-based parameter position, such as --consume close:handle";

/// `tsuzuri bindgen HEADER -o OUTPUT.tz [--include-dir DIR]... [--buffer F:P:L]...
/// [--consume F:P]... [--json]`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Arguments {
    pub header: PathBuf,
    pub output: PathBuf,
    /// Passed to Clang as `-I DIR` in this order; they only resolve includes.
    pub include_dirs: Vec<PathBuf>,
    pub buffers: Vec<BufferAnnotation>,
    pub consumes: Vec<ConsumeAnnotation>,
    pub json: bool,
}

/// A parameter that an annotation names: its C name or its position, counted from 1.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ParameterName {
    Name(String),
    Position(usize),
}

impl std::fmt::Display for ParameterName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Name(name) => formatter.write_str(name),
            Self::Position(position) => write!(formatter, "{position}"),
        }
    }
}

/// `--buffer FUNCTION:POINTER:LENGTH`: the pointer and the element count that follows
/// it are one Tsuzuri buffer parameter, `ref [T]`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BufferAnnotation {
    pub function: String,
    pub pointer: ParameterName,
    pub length: ParameterName,
}

/// `--consume FUNCTION:PARAMETER`: the function takes ownership of the opaque handle
/// passed in that parameter, so it is a move of the handle instead of a borrow.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConsumeAnnotation {
    pub function: String,
    pub parameter: ParameterName,
}

fn parameter_name(text: &str) -> Option<ParameterName> {
    if !text.is_empty() && text.bytes().all(|byte| byte.is_ascii_digit()) {
        return text
            .parse()
            .ok()
            .filter(|position| *position >= 1)
            .map(ParameterName::Position);
    }
    ascii_identifier(text).then(|| ParameterName::Name(text.to_owned()))
}

/// Splits `FUNCTION:PARAMETER...` into a C function name and parameter names.
fn annotation(
    value: Option<&OsString>,
    count: usize,
    usage: &str,
) -> Result<(String, Vec<ParameterName>), String> {
    let parts: Vec<&str> = value
        .and_then(|value| value.to_str())
        .map(|value| value.split(':').collect())
        .unwrap_or_default();
    if parts.len() != count + 1 || !ascii_identifier(parts[0]) {
        return Err(usage.into());
    }
    let parameters = parts[1..]
        .iter()
        .map(|part| parameter_name(part))
        .collect::<Option<Vec<_>>>()
        .ok_or(usage)?;
    Ok((parts[0].to_owned(), parameters))
}

/// Parses the arguments after `bindgen`. The error is an `E2000` message.
pub fn parse_arguments(arguments: &[OsString]) -> Result<Arguments, String> {
    let mut headers = Vec::new();
    let mut output = None;
    let mut include_dirs = Vec::new();
    let mut buffers: Vec<BufferAnnotation> = Vec::new();
    let mut consumes: Vec<ConsumeAnnotation> = Vec::new();
    let mut json = false;
    let mut paths_only = false;
    let mut rest = arguments.iter();
    while let Some(argument) = rest.next() {
        if !paths_only {
            match argument.to_str() {
                Some("--") => {
                    paths_only = true;
                    continue;
                }
                Some("--json") => {
                    json = true;
                    continue;
                }
                Some("-o" | "--output") => {
                    if output.is_some() {
                        return Err("output specified more than once".into());
                    }
                    output = Some(PathBuf::from(rest.next().ok_or("--output needs a value")?));
                    continue;
                }
                Some("--include-dir") => {
                    include_dirs.push(PathBuf::from(
                        rest.next().ok_or("--include-dir needs a value")?,
                    ));
                    continue;
                }
                Some("--buffer") => {
                    let (function, mut parameters) = annotation(rest.next(), 2, BUFFER_USAGE)?;
                    let length = parameters.pop().expect("two parameters");
                    let pointer = parameters.pop().expect("two parameters");
                    if buffers
                        .iter()
                        .any(|buffer| buffer.function == function && buffer.pointer == pointer)
                    {
                        return Err(format!(
                            "--buffer {function}:{pointer} is specified more than once"
                        ));
                    }
                    buffers.push(BufferAnnotation {
                        function,
                        pointer,
                        length,
                    });
                    continue;
                }
                Some("--consume") => {
                    let (function, mut parameters) = annotation(rest.next(), 1, CONSUME_USAGE)?;
                    let parameter = parameters.pop().expect("one parameter");
                    if consumes.iter().any(|consume| {
                        consume.function == function && consume.parameter == parameter
                    }) {
                        return Err(format!(
                            "--consume {function}:{parameter} is specified more than once"
                        ));
                    }
                    consumes.push(ConsumeAnnotation {
                        function,
                        parameter,
                    });
                    continue;
                }
                Some(value) if value.starts_with('-') => return Err(OPTIONS.into()),
                _ => {}
            }
        }
        headers.push(PathBuf::from(argument));
    }
    let [header] = <[PathBuf; 1]>::try_from(headers)
        .map_err(|_| "bindgen requires exactly one header path".to_owned())?;
    let output = output.ok_or("bindgen requires -o OUTPUT.tz")?;
    if output.extension() != Some(OsStr::new("tz")) {
        return Err("bindgen output must have the .tz extension".into());
    }
    let module = output.file_stem().and_then(OsStr::to_str).unwrap_or("");
    if !module.starts_with(|first: char| first.is_ascii_uppercase())
        || !module
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    {
        return Err(format!(
            "bindgen output '{}' is not a module file name; start it with an uppercase ASCII letter followed by letters, digits, or '_', as in Zlib.tz",
            output.display()
        ));
    }
    Ok(Arguments {
        header,
        output,
        include_dirs,
        buffers,
        consumes,
        json,
    })
}

/// What the generated header comment records about the input.
pub struct HeaderInfo<'a> {
    /// The absolute path passed to Clang; a declaration belongs to the header when
    /// Clang's AST places it in this file.
    pub path: &'a str,
    pub file_name: &'a str,
    /// SHA-256 of the header's bytes in lowercase hex.
    pub sha256: &'a str,
    /// The first line of `clang --version`.
    pub clang_version: &'a str,
    /// The output of `clang -dumpmachine`.
    pub target: &'a str,
}

/// A header declaration that bindgen did not convert, reported as `W2002`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Skipped {
    /// The C name.
    pub name: String,
    pub reason: String,
    /// The byte range of the declaration's name in the header.
    pub offset: usize,
    pub length: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Generated {
    pub text: String,
    pub skipped: Vec<Skipped>,
}

/// Whether bindgen accepts Clang's target triple: 64-bit x86 and ARM with 64-bit
/// `long` and pointers (LP64), which excludes Windows (LLP64) and the ILP32 ABIs.
pub fn lp64_target(triple: &str) -> bool {
    let architecture = triple.split('-').next().unwrap_or("");
    matches!(architecture, "x86_64" | "aarch64" | "arm64")
        && !["windows", "mingw", "cygwin", "uefi", "gnux32", "ilp32"]
            .iter()
            .any(|system| triple.contains(system))
}

/// Converts the JSON AST of `clang -Xclang -ast-dump=json` for the header into a
/// Tsuzuri module, without macros or annotations. `Err` means the AST does not have
/// the shape Clang writes.
pub fn generate(ast: &Value, header: &HeaderInfo) -> Result<Generated, String> {
    generate_with(ast, header, &Extras::default()).map_err(|failure| match failure {
        Failure::Ast(message) | Failure::Annotation(message) => message,
    })
}

/// What bindgen reads besides the AST.
#[derive(Clone, Copy, Debug, Default)]
pub struct Extras<'a> {
    /// The output of `clang -E -dD` for the header: the header's object-like macros
    /// whose replacement is one integer literal become constants.
    pub preprocessed: Option<&'a str>,
    /// The header's bytes, which place each macro at its line.
    pub header_text: &'a [u8],
    pub buffers: &'a [BufferAnnotation],
    pub consumes: &'a [ConsumeAnnotation],
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Failure {
    /// The AST does not have the shape Clang writes (`E2002`).
    Ast(String),
    /// An annotation names a function or a parameter that the header does not
    /// declare, or names one parameter twice (`E2000`).
    Annotation(String),
}

/// [`generate`] with macros and the `--buffer` and `--consume` annotations.
pub fn generate_with(
    ast: &Value,
    header: &HeaderInfo,
    extras: &Extras,
) -> Result<Generated, Failure> {
    let nodes = ast
        .get("inner")
        .and_then(Value::as_array)
        .ok_or_else(|| Failure::Ast("the translation unit has no 'inner' array".into()))?;
    let declarations = header_declarations(nodes, header.path).map_err(Failure::Ast)?;
    let tables = Tables::new(nodes);
    let macros = extras
        .preprocessed
        .map(|text| header_macros(text, header.path, extras.header_text))
        .unwrap_or_default();
    let mut emitter = Emitter::new(&tables, header.target, extras);
    emitter.collect_types(&declarations);
    // Declarations and macros in header order: a later name that collides is skipped.
    let mut macros = macros.into_iter().peekable();
    for (index, declaration) in declarations.iter().enumerate() {
        if !declaration.owned {
            continue;
        }
        while let Some(definition) = macros.next_if(|macro_| macro_.offset < declaration.offset) {
            emitter.definition(&definition);
        }
        emitter.declaration(index, declaration)?;
    }
    for definition in macros {
        emitter.definition(&definition);
    }
    emitter.check_annotations()?;
    Ok(emitter.finish(header))
}

// ---------------------------------------------------------------------------
// Which declarations belong to the header

/// A top-level declaration and where its name is.
struct Declaration<'a> {
    node: &'a Value,
    kind: &'a str,
    owned: bool,
    offset: usize,
    length: usize,
}

/// Clang writes a location's `file` only when it differs from the previously written
/// location, so the file of each declaration is known only by visiting every location
/// in the order Clang printed them: `loc` (spelling, then expansion), `range` (begin,
/// then end), then the children. `serde_json` objects do not keep key order, so the
/// order is fixed here rather than taken from the map.
fn header_declarations<'a>(nodes: &'a [Value], path: &str) -> Result<Vec<Declaration<'a>>, String> {
    let mut tracker = Tracker::default();
    let mut declarations = Vec::with_capacity(nodes.len());
    for node in nodes {
        let kind = node
            .get("kind")
            .and_then(Value::as_str)
            .ok_or("a declaration of the translation unit has no 'kind'")?;
        tracker.location(node.get("loc"));
        // A declaration expanded from a macro belongs to the file of the expansion.
        let file = tracker.current;
        tracker.range(node.get("range"));
        tracker.children(node);
        let (offset, length) = position(node);
        declarations.push(Declaration {
            node,
            kind,
            owned: file == Some(path) && !flag(node, "isImplicit"),
            offset,
            length,
        });
    }
    Ok(declarations)
}

#[derive(Default)]
struct Tracker<'a> {
    current: Option<&'a str>,
}

impl<'a> Tracker<'a> {
    fn location(&mut self, location: Option<&'a Value>) {
        let Some(location) = location else {
            return;
        };
        let spelling = location.get("spellingLoc");
        let expansion = location.get("expansionLoc");
        if spelling.is_none() && expansion.is_none() {
            self.bare(location);
        }
        for part in [spelling, expansion].into_iter().flatten() {
            self.bare(part);
        }
    }

    fn bare(&mut self, location: &'a Value) {
        // `includedFrom` also has a `file`, but Clang does not count it as written.
        if let Some(file) = location.get("file").and_then(Value::as_str) {
            self.current = Some(file);
        }
    }

    fn range(&mut self, range: Option<&'a Value>) {
        if let Some(range) = range {
            self.location(range.get("begin"));
            self.location(range.get("end"));
        }
    }

    fn children(&mut self, node: &'a Value) {
        for key in ["array_filler", "inner"] {
            for child in node
                .get(key)
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                // serde_json limits nesting to 128, which bounds this recursion.
                self.location(child.get("loc"));
                self.range(child.get("range"));
                self.children(child);
            }
        }
    }
}

/// The byte range of a node's name: the expansion of a macro, else the location itself.
fn position(node: &Value) -> (usize, usize) {
    let Some(location) = node.get("loc") else {
        return (0, 0);
    };
    let location = location.get("expansionLoc").unwrap_or(location);
    let number = |key| {
        location
            .get(key)
            .and_then(Value::as_u64)
            .and_then(|value| usize::try_from(value).ok())
            .unwrap_or(0)
    };
    (number("offset"), number("tokLen"))
}

fn flag(node: &Value, key: &str) -> bool {
    node.get(key).and_then(Value::as_bool) == Some(true)
}

fn text<'a>(node: &'a Value, key: &str) -> Option<&'a str> {
    node.get(key).and_then(Value::as_str)
}

fn name(node: &Value) -> &str {
    text(node, "name").unwrap_or("")
}

fn kind(node: &Value) -> &str {
    text(node, "kind").unwrap_or("")
}

/// The spelled and desugared C type of a node.
fn node_type(node: &Value) -> (&str, Option<&str>) {
    let ty = node.get("type");
    let spelled = ty.and_then(|ty| text(ty, "qualType")).unwrap_or("");
    let desugared = ty.and_then(|ty| text(ty, "desugaredQualType"));
    (spelled, desugared)
}

fn children(node: &Value) -> impl Iterator<Item = &Value> {
    node.get("inner")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
}

fn has_attribute(node: &Value, kinds: &[&str]) -> bool {
    children(node).any(|child| kinds.contains(&kind(child)))
}

/// Attributes that change a struct's or a field's layout from the natural C layout.
const LAYOUT_ATTRIBUTES: &[&str] = &["AlignedAttr", "PackedAttr", "MaxFieldAlignmentAttr"];

// ---------------------------------------------------------------------------
// Macros

/// An object-like `#define` of the header, as it stands after the whole header.
#[derive(Debug, PartialEq, Eq)]
struct Definition<'p> {
    name: &'p str,
    body: &'p str,
    /// The byte range of the macro's name in the header.
    offset: usize,
    length: usize,
}

/// The header's own object-like macros from `clang -E -dD`, in header order. Line
/// markers (`# 12 "/path/x.h" 2`) name the file and line of the next output line, and
/// each following line is the next source line, so every `#define` is placed at its
/// line. A later `#undef` or redefinition (in any file) decides the final state.
fn header_macros<'p>(preprocessed: &'p str, path: &str, header_text: &[u8]) -> Vec<Definition<'p>> {
    let mut in_header = false;
    let mut line = 1usize;
    let mut last: BTreeMap<&'p str, Option<(&'p str, usize)>> = BTreeMap::new();
    for text in preprocessed.split('\n') {
        let text = text.strip_suffix('\r').unwrap_or(text);
        if let Some((number, file)) = linemarker(text) {
            in_header = file == path.as_bytes();
            line = number;
            continue;
        }
        if let Some(rest) = text.strip_prefix("#define ") {
            let end = rest
                .find(|character: char| character == '(' || character.is_ascii_whitespace())
                .unwrap_or(rest.len());
            let (name, after) = rest.split_at(end);
            // A function-like macro has `(` right after its name.
            let object_like = !after.starts_with('(');
            last.insert(
                name,
                (in_header && object_like).then(|| (after.trim(), line)),
            );
        } else if let Some(rest) = text.strip_prefix("#undef ") {
            last.insert(rest.trim(), None);
        }
        line += 1;
    }
    let starts = line_starts(header_text);
    let mut definitions: Vec<_> = last
        .into_iter()
        .filter_map(|(name, definition)| {
            let (body, line) = definition?;
            let (offset, length) = macro_position(header_text, &starts, line, name);
            Some(Definition {
                name,
                body,
                offset,
                length,
            })
        })
        .collect();
    definitions.sort_by_key(|definition| (definition.offset, definition.name));
    definitions
}

/// `# LINE "FILE" FLAGS...`, with the file name's C escapes undone.
fn linemarker(text: &str) -> Option<(usize, Vec<u8>)> {
    let rest = text.strip_prefix("# ")?;
    let digits = rest.find(|character: char| !character.is_ascii_digit())?;
    let line = rest[..digits].parse().ok()?;
    let quoted = rest[digits..].strip_prefix(" \"")?.as_bytes();
    let mut file = Vec::new();
    let mut index = 0;
    loop {
        match *quoted.get(index)? {
            b'"' => return Some((line, file)),
            b'\\' => {
                index += 1;
                match *quoted.get(index)? {
                    b'n' => file.push(b'\n'),
                    b't' => file.push(b'\t'),
                    digit @ b'0'..=b'7' => {
                        let mut value = u32::from(digit - b'0');
                        while index + 1 < quoted.len()
                            && value < 0o40
                            && (b'0'..=b'7').contains(&quoted[index + 1])
                        {
                            index += 1;
                            value = value * 8 + u32::from(quoted[index] - b'0');
                        }
                        file.push(u8::try_from(value).ok()?);
                    }
                    other => file.push(other),
                }
            }
            other => file.push(other),
        }
        index += 1;
    }
}

/// The byte offset of each line; `\r\n`, `\n`, and `\r` end a line, as in Clang.
fn line_starts(text: &[u8]) -> Vec<usize> {
    let mut starts = vec![0];
    let mut index = 0;
    while index < text.len() {
        match text[index] {
            b'\r' if text.get(index + 1) == Some(&b'\n') => {
                index += 2;
                starts.push(index);
            }
            b'\r' | b'\n' => {
                index += 1;
                starts.push(index);
            }
            _ => index += 1,
        }
    }
    starts
}

/// Where the name of the `#define` on `line` is; the start of the line when the
/// directive is spelled in a way this does not follow.
fn macro_position(text: &[u8], starts: &[usize], line: usize, name: &str) -> (usize, usize) {
    let Some(&start) = line.checked_sub(1).and_then(|index| starts.get(index)) else {
        return (0, 0);
    };
    let end = starts.get(line).copied().unwrap_or(text.len());
    let source = &text[start..end];
    if let Some(at) = source.windows(6).position(|window| window == b"define") {
        let mut index = at + 6;
        while matches!(source.get(index), Some(b' ' | b'\t')) {
            index += 1;
        }
        if source[index..].starts_with(name.as_bytes()) {
            return (start + index, name.len());
        }
    }
    (start, 0)
}

#[derive(Debug, PartialEq, Eq)]
enum MacroValue {
    /// Not one integer literal: ignored.
    NotInteger,
    Integer(i128, Scalar),
    /// An integer literal that bindgen cannot represent exactly: skipped with `W2002`.
    Invalid(String),
}

/// The value of a macro whose replacement is one integer literal with optional
/// parentheses and unary minus, typed by C's rules for integer constants on LP64.
fn macro_value(body: &str) -> MacroValue {
    let Some(tokens) = macro_tokens(body) else {
        return MacroValue::NotInteger;
    };
    let mut rest = tokens.as_slice();
    let mut negations = 0usize;
    let literal = loop {
        match rest {
            [literal]
                if literal.starts_with(|first: char| first.is_ascii_digit() || first == '.') =>
            {
                break *literal;
            }
            ["-", inner @ ..] => {
                negations += 1;
                rest = inner;
            }
            ["(", .., ")"] if closing(rest) == Some(rest.len() - 1) => {
                rest = &rest[1..rest.len() - 1]
            }
            _ => return MacroValue::NotInteger,
        }
    };
    match integer_literal(literal) {
        Ok(None) => MacroValue::NotInteger,
        Err(reason) => MacroValue::Invalid(reason),
        Ok(Some((value, scalar))) => {
            let mut value = i128::from(value);
            // Negating twice is the identity in both signed and unsigned arithmetic, and a
            // literal never exceeds its signed type's maximum, so one negation cannot overflow.
            if negations % 2 == 1 {
                value = match scalar {
                    Scalar::I32u => (-value).rem_euclid(1 << 32),
                    Scalar::I64u => (-value).rem_euclid(1 << 64),
                    _ => -value,
                };
            }
            MacroValue::Integer(value, scalar)
        }
    }
}

/// The tokens of a replacement list made only of parentheses, `-`, and preprocessing
/// numbers; `None` for anything else.
fn macro_tokens(body: &str) -> Option<Vec<&str>> {
    let bytes = body.as_bytes();
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < bytes.len() {
        let byte = bytes[index];
        if byte.is_ascii_whitespace() {
            index += 1;
        } else if byte == b'(' || byte == b')' {
            tokens.push(&body[index..index + 1]);
            index += 1;
        } else if byte == b'-' {
            // `--` is the decrement operator, not two minus signs.
            if bytes.get(index + 1) == Some(&b'-') {
                return None;
            }
            tokens.push("-");
            index += 1;
        } else if byte.is_ascii_digit()
            || (byte == b'.' && bytes.get(index + 1).is_some_and(u8::is_ascii_digit))
        {
            let start = index;
            index += 1;
            while index < bytes.len() {
                let next = bytes[index];
                let exponent_sign = matches!(next, b'+' | b'-')
                    && matches!(bytes[index - 1], b'e' | b'E' | b'p' | b'P');
                if !(next.is_ascii_alphanumeric() || next == b'_' || next == b'.' || exponent_sign)
                {
                    break;
                }
                index += 1;
            }
            tokens.push(&body[start..index]);
        } else {
            return None;
        }
        if tokens.len() > 64 {
            return None;
        }
    }
    Some(tokens)
}

/// The index of the `)` that closes the `(` at the start of `tokens`.
fn closing(tokens: &[&str]) -> Option<usize> {
    let mut depth = 0usize;
    for (index, token) in tokens.iter().enumerate() {
        match *token {
            "(" => depth += 1,
            ")" => {
                depth -= 1;
                if depth == 0 {
                    return Some(index);
                }
            }
            _ => {}
        }
    }
    None
}

/// A C integer constant (C17 6.4.4.1 with GNU binary literals) and its type on LP64:
/// `int` → `i32`, `unsigned int` → `i32u`, `long` and `long long` → `i64`,
/// `unsigned long` and `unsigned long long` → `i64u`. `Ok(None)` for a floating constant.
fn integer_literal(text: &str) -> Result<Option<(u64, Scalar)>, String> {
    let lower = text.to_ascii_lowercase();
    let bytes = text.as_bytes();
    let (radix, prefix) = if lower.starts_with("0x") {
        (16, 2)
    } else if lower.starts_with("0b") {
        (2, 2)
    } else if bytes.len() > 1 && bytes[0] == b'0' && bytes[1].is_ascii_digit() {
        (8, 1)
    } else {
        (10, 0)
    };
    let floating = text.contains('.')
        || if radix == 16 {
            lower.contains('p')
        } else {
            lower.contains('e')
        };
    if floating {
        return Ok(None);
    }
    let invalid = || format!("'{text}' is not a valid C integer literal");
    let body = &text[prefix..];
    let digits = body
        .find(|character: char| {
            !if radix == 16 {
                character.is_ascii_hexdigit()
            } else {
                character.is_ascii_digit()
            }
        })
        .unwrap_or(body.len());
    let (digits, suffix) = body.split_at(digits);
    if digits.is_empty() {
        return Err(invalid());
    }
    let mut value = 0u128;
    for character in digits.chars() {
        value =
            value * u128::from(radix) + u128::from(character.to_digit(radix).ok_or_else(invalid)?);
        if value > u128::from(u64::MAX) {
            return Err(format!("integer literal '{text}' does not fit in 64 bits"));
        }
    }
    let (unsigned, longs) = match suffix.to_ascii_lowercase().as_str() {
        "" => (false, 0),
        "u" => (true, 0),
        "l" => (false, 1),
        "ul" | "lu" => (true, 1),
        "ll" => (false, 2),
        "ull" | "llu" => (true, 2),
        _ => {
            return Err(format!(
                "integer literal '{text}' has a suffix that bindgen does not convert"
            ));
        }
    };
    if longs == 2 && !(suffix.contains("ll") || suffix.contains("LL")) {
        return Err(invalid());
    }
    let decimal = radix == 10;
    let candidates: &[Scalar] = match (unsigned, longs, decimal) {
        (false, 0, true) => &[Scalar::I32, Scalar::I64],
        (false, 0, false) => &[Scalar::I32, Scalar::I32u, Scalar::I64, Scalar::I64u],
        (true, 0, _) => &[Scalar::I32u, Scalar::I64u],
        (false, 1, true) | (false, 2, true) => &[Scalar::I64],
        (false, _, false) => &[Scalar::I64, Scalar::I64u],
        (true, _, _) => &[Scalar::I64u],
        (false, _, true) => &[Scalar::I64],
    };
    let maximum = |scalar: Scalar| match scalar {
        Scalar::I32 => u128::from(i32::MAX.unsigned_abs()),
        Scalar::I32u => u128::from(u32::MAX),
        Scalar::I64 => u128::from(i64::MAX.unsigned_abs()),
        _ => u128::from(u64::MAX),
    };
    candidates
        .iter()
        .find(|scalar| value <= maximum(**scalar))
        .map(|scalar| Some((value as u64, *scalar)))
        .ok_or_else(|| {
            format!(
                "integer literal '{text}' does not fit in a signed 64-bit type; C gives it no type without a 'u' suffix"
            )
        })
}

// ---------------------------------------------------------------------------
// C types as Clang spells them

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct Qualifiers {
    constant: bool,
    volatile: bool,
}

impl Qualifiers {
    fn union(self, other: Self) -> Self {
        Self {
            constant: self.constant || other.constant,
            volatile: self.volatile || other.volatile,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum CType {
    /// Specifiers without qualifiers: a builtin such as `unsigned long`, a tag such
    /// as `struct point`, or a typedef name.
    Named(String),
    /// A pointer and the qualifiers of what it points to.
    Pointer(Box<CType>, Qualifiers),
    /// A prototyped, non-variadic function type: its result and parameters.
    Function(Box<CType>, Vec<CType>),
    /// Anything else, including spellings this parser does not understand.
    Unsupported,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Token<'a> {
    Word(&'a str),
    Symbol(char),
}

fn tokenize(text: &str) -> Vec<(usize, Token<'_>)> {
    let bytes = text.as_bytes();
    let word = |byte: u8| byte.is_ascii_alphanumeric() || byte == b'_' || byte == b'$';
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index].is_ascii_whitespace() {
            index += 1;
        } else if word(bytes[index]) {
            let start = index;
            while index < bytes.len() && word(bytes[index]) {
                index += 1;
            }
            tokens.push((start, Token::Word(&text[start..index])));
        } else if text[index..].starts_with("...") {
            tokens.push((index, Token::Word("...")));
            index += 3;
        } else {
            let character = text[index..].chars().next().unwrap_or('?');
            tokens.push((index, Token::Symbol(character)));
            index += character.len_utf8();
        }
    }
    tokens
}

/// The index of the `)` that closes the `(` at `open`.
fn matching(tokens: &[(usize, Token<'_>)], open: usize) -> Option<usize> {
    let mut depth = 0usize;
    for (index, (_, token)) in tokens.iter().enumerate().skip(open) {
        match token {
            Token::Symbol('(') => depth += 1,
            Token::Symbol(')') => {
                depth -= 1;
                if depth == 0 {
                    return Some(index);
                }
            }
            _ => {}
        }
    }
    None
}

/// Parses a whole type spelling: specifiers, pointers with their qualifiers, and at
/// most one function-pointer declarator `R (*)(P, ...)`. The qualifiers returned
/// are those of the type itself (top level).
fn parse_type(text: &str) -> Option<(CType, Qualifiers)> {
    parse_tokens(&tokenize(text), 0)
}

fn parse_tokens(tokens: &[(usize, Token<'_>)], nesting: usize) -> Option<(CType, Qualifiers)> {
    if nesting > MAX_TYPE_NESTING {
        return None;
    }
    let mut parser = TypeParser {
        tokens,
        position: 0,
        nesting,
    };
    let parsed = parser.whole()?;
    (parser.position == tokens.len()).then_some(parsed)
}

struct TypeParser<'t, 'a> {
    tokens: &'t [(usize, Token<'a>)],
    position: usize,
    nesting: usize,
}

impl<'a> TypeParser<'_, 'a> {
    fn peek(&self) -> Option<Token<'a>> {
        self.tokens.get(self.position).map(|(_, token)| *token)
    }

    fn eat(&mut self, symbol: char) -> bool {
        let found = self.peek() == Some(Token::Symbol(symbol));
        self.position += usize::from(found);
        found
    }

    fn whole(&mut self) -> Option<(CType, Qualifiers)> {
        let (mut ty, mut qualifiers) = self.specifiers()?;
        while self.eat('*') {
            ty = CType::Pointer(Box::new(ty), qualifiers);
            qualifiers = self.qualifiers()?;
        }
        if self.eat('(') {
            // Only `(*)` with optional qualifiers: blocks `(^)` and nested
            // declarators are not supported.
            if !self.eat('*') {
                return None;
            }
            let pointer = self.qualifiers()?;
            if !self.eat(')') || !self.eat('(') {
                return None;
            }
            let parameters = self.parameters()?;
            let function = if parameters.prototype && !parameters.variadic {
                CType::Function(Box::new(ty), parameters.list)
            } else {
                CType::Unsupported
            };
            ty = CType::Pointer(Box::new(function), Qualifiers::default());
            qualifiers = pointer;
        }
        Some((ty, qualifiers))
    }

    fn specifiers(&mut self) -> Option<(CType, Qualifiers)> {
        let mut words = Vec::new();
        let mut qualifiers = Qualifiers::default();
        while let Some(Token::Word(word)) = self.peek() {
            self.position += 1;
            match word {
                "const" => qualifiers.constant = true,
                "volatile" => qualifiers.volatile = true,
                "restrict" | "__restrict" | "_Nonnull" | "_Nullable" | "_Null_unspecified"
                | "_Nullable_result" => {}
                "struct" | "union" | "enum" => {
                    // An anonymous tag is spelled `struct (unnamed struct at ...)`.
                    let Some(Token::Word(tag)) = self.peek() else {
                        return None;
                    };
                    self.position += 1;
                    words.push(format!("{word} {tag}"));
                }
                _ => words.push(word.to_owned()),
            }
        }
        (!words.is_empty()).then(|| (CType::Named(words.join(" ")), qualifiers))
    }

    /// The qualifiers after a `*`, which apply to the pointer itself.
    fn qualifiers(&mut self) -> Option<Qualifiers> {
        let mut qualifiers = Qualifiers::default();
        while let Some(Token::Word(word)) = self.peek() {
            match word {
                "const" => qualifiers.constant = true,
                "volatile" => qualifiers.volatile = true,
                "restrict" | "__restrict" | "_Nonnull" | "_Nullable" | "_Null_unspecified"
                | "_Nullable_result" => {}
                _ => return None,
            }
            self.position += 1;
        }
        Some(qualifiers)
    }

    /// The parameter list after its `(`, through the closing `)`.
    fn parameters(&mut self) -> Option<Parameters> {
        let mut depth = 0usize;
        let mut pieces = Vec::new();
        let mut start = self.position;
        loop {
            let (_, token) = *self.tokens.get(self.position)?;
            self.position += 1;
            match token {
                Token::Symbol('(' | '[') => depth += 1,
                Token::Symbol(')') if depth == 0 => {
                    pieces.push(start..self.position - 1);
                    break;
                }
                Token::Symbol(')' | ']') => depth = depth.checked_sub(1)?,
                Token::Symbol(',') if depth == 0 => {
                    pieces.push(start..self.position - 1);
                    start = self.position;
                }
                _ => {}
            }
        }
        Some(parameter_list(self.tokens, pieces, self.nesting))
    }
}

struct Parameters {
    list: Vec<CType>,
    /// `false` for `()`, which declares no prototype in C17.
    prototype: bool,
    variadic: bool,
}

fn parameter_list(
    tokens: &[(usize, Token<'_>)],
    mut pieces: Vec<Range<usize>>,
    nesting: usize,
) -> Parameters {
    let piece = |range: &Range<usize>| &tokens[range.clone()];
    if pieces.len() == 1 && pieces[0].is_empty() {
        return Parameters {
            list: Vec::new(),
            prototype: false,
            variadic: false,
        };
    }
    if pieces.len() == 1 && matches!(piece(&pieces[0]), [(_, Token::Word("void"))]) {
        pieces.clear();
    }
    let variadic = pieces
        .last()
        .is_some_and(|last| matches!(piece(last), [(_, Token::Word("..."))]));
    if variadic {
        pieces.pop();
    }
    Parameters {
        list: pieces
            .iter()
            .map(|range| {
                parse_tokens(piece(range), nesting + 1).map_or(CType::Unsupported, |(ty, _)| ty)
            })
            .collect(),
        prototype: true,
        variadic,
    }
}

/// A function declaration's type `R (P1, P2) attributes`, split into its parts.
struct FunctionShape {
    /// The spelling of the result type; `Err` holds the spelling of a function-pointer
    /// or block result, which is never supported.
    result: Result<String, String>,
    prototype: bool,
    /// The names in trailing `__attribute__((...))` groups; `?` marks other text.
    attributes: Vec<String>,
}

fn function_shape(text: &str) -> Option<FunctionShape> {
    let tokens = tokenize(text);
    let mut attributes = Vec::new();
    // Clang prints some calling conventions before the type (`__attribute__((x)) int
    // (int)`) and others after the parameter list.
    let mut result_start = 0;
    let mut open = 0;
    loop {
        match tokens.get(open)?.1 {
            Token::Word("__attribute__") => {
                let (name, end) = attribute_group(&tokens, open)?;
                attributes.push(name);
                if open == result_start {
                    result_start = end + 1;
                }
                open = end + 1;
            }
            // The parameter list is the first `(` that does not spell an anonymous tag.
            Token::Symbol('(')
                if open > 0
                    && matches!(tokens[open - 1].1, Token::Word("struct" | "union" | "enum")) =>
            {
                open = matching(&tokens, open)? + 1;
            }
            Token::Symbol('(') => break,
            _ => open += 1,
        }
    }
    let close = matching(&tokens, open)?;
    if matches!(
        tokens.get(open + 1).map(|token| token.1),
        Some(Token::Symbol('*' | '^'))
    ) {
        // `int (*(int))(void)` returns `int (*)(void)`: drop the function's own
        // parameter list, which directly follows the `*` and its qualifiers.
        let mut inner = open + 2;
        while matches!(tokens.get(inner).map(|token| token.1), Some(Token::Word(_))) {
            inner += 1;
        }
        let spelled = match tokens.get(inner) {
            Some((from, Token::Symbol('('))) => {
                let end = matching(&tokens, inner)?;
                format!("{}{}", &text[..*from], &text[tokens[end].0 + 1..])
            }
            _ => text.to_owned(),
        };
        return Some(FunctionShape {
            result: Err(spelled.trim().to_owned()),
            prototype: true,
            attributes,
        });
    }
    let mut index = close + 1;
    while index < tokens.len() {
        let Some((name, end)) = attribute_group(&tokens, index) else {
            attributes.push("?".to_owned());
            break;
        };
        attributes.push(name);
        index = end + 1;
    }
    let result_text = match tokens.get(result_start) {
        Some((from, _)) if result_start < open => &text[*from..tokens[open].0],
        _ => "",
    };
    Some(FunctionShape {
        result: Ok(result_text.trim().to_owned()),
        prototype: close != open + 1,
        attributes,
    })
}

/// The name in an `__attribute__((name...))` group at `start` and the index of its last `)`.
fn attribute_group(tokens: &[(usize, Token<'_>)], start: usize) -> Option<(String, usize)> {
    let group = matches!(tokens.get(start)?.1, Token::Word("__attribute__"))
        && tokens.get(start + 1)?.1 == Token::Symbol('(')
        && tokens.get(start + 2)?.1 == Token::Symbol('(');
    if !group {
        return None;
    }
    let end = matching(tokens, start + 1)?;
    let name = match tokens.get(start + 3)?.1 {
        Token::Word(name) => name.to_owned(),
        Token::Symbol(_) => "?".to_owned(),
    };
    Some((name, end))
}

/// Replaces Clang's `(unnamed struct at /abs/path:1:2)` with `(unnamed struct)`, so
/// generated text and warnings never contain absolute paths.
fn scrub(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = ["(unnamed ", "(anonymous "]
        .iter()
        .filter_map(|marker| rest.find(marker))
        .min()
    {
        let Some(end) = rest[start..].find(')').map(|end| start + end) else {
            break;
        };
        let inside = &rest[start..end];
        result.push_str(&rest[..start]);
        result.push_str(inside.split(" at ").next().unwrap_or(inside));
        result.push(')');
        rest = &rest[end + 1..];
    }
    result.push_str(rest);
    result
}

// ---------------------------------------------------------------------------
// Tables built from every file of the translation unit

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Scalar {
    Bool,
    I8,
    I8u,
    I16,
    I16u,
    I32,
    I32u,
    I64,
    I64u,
    F32,
    F64,
}

impl Scalar {
    /// The C builtin types bindgen converts, spelled as Clang prints them. Plain
    /// `char` is not one of them: its signedness depends on the target.
    fn of(name: &str) -> Option<Self> {
        Some(match name {
            "_Bool" => Self::Bool,
            "signed char" => Self::I8,
            "unsigned char" => Self::I8u,
            "short" => Self::I16,
            "unsigned short" => Self::I16u,
            "int" => Self::I32,
            "unsigned int" => Self::I32u,
            // LP64: `long` is 64 bits.
            "long" | "long long" => Self::I64,
            "unsigned long" | "unsigned long long" => Self::I64u,
            "float" => Self::F32,
            "double" => Self::F64,
            _ => return None,
        })
    }

    fn name(self) -> &'static str {
        match self {
            Self::Bool => "bool",
            Self::I8 => "i8",
            Self::I8u => "i8u",
            Self::I16 => "i16",
            Self::I16u => "i16u",
            Self::I32 => "i32",
            Self::I32u => "i32u",
            Self::I64 => "i64",
            Self::I64u => "i64u",
            Self::F32 => "f32",
            Self::F64 => "f64",
        }
    }

    /// The Tsuzuri type in each position. A `_Bool` that C hands to Tsuzuri (an
    /// extern's result, a callback's parameter) becomes `i8u` because C guarantees only
    /// its low 8 bits, while a Tsuzuri `bool` reads all 32 bits of the ABI value. ABI
    /// records widen `bool` and narrow integers to 32 bits, so fields take only 32- and
    /// 64-bit scalars, which C lays out the same way.
    fn in_role(self, role: Role) -> Option<&'static str> {
        match (self, role) {
            (Self::Bool, Role::Result | Role::CallbackParameter) => Some("i8u"),
            (Self::Bool | Self::I8 | Self::I8u | Self::I16 | Self::I16u, Role::Field) => None,
            _ => Some(self.name()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Role {
    Parameter,
    Result,
    Field,
    /// A parameter of a function pointer parameter: C passes it to Tsuzuri.
    CallbackParameter,
    /// The result of a function pointer parameter: Tsuzuri returns it to C.
    CallbackResult,
}

struct Typedef<'a> {
    spelled: &'a str,
    desugared: Option<&'a str>,
    /// An alignment or packing attribute changes the type's layout, which its
    /// spelling does not show.
    poisoned: bool,
}

struct Tables<'a> {
    typedefs: BTreeMap<&'a str, Typedef<'a>>,
    /// `enum TAG` (or `enum NAME` for an anonymous enum named by a typedef) → whether
    /// the enum is an `int`: every constant fits in i32, with no fixed underlying type
    /// and no packing.
    enums: BTreeMap<String, bool>,
    /// Anonymous struct, union, and enum declarations by id → the typedef that names
    /// them and where that name is.
    anonymous: BTreeMap<&'a str, (&'a str, (usize, usize))>,
    /// The ids of the implicit declarations Clang makes for library builtins.
    builtins: BTreeSet<&'a str>,
    /// Struct tags declared at file scope that no declaration of the translation unit
    /// defines: only pointers to them can exist, so they are opaque handles.
    incomplete: BTreeSet<&'a str>,
}

/// The tags of every struct definition, at any depth.
fn complete_structs<'a>(node: &'a Value, found: &mut BTreeSet<&'a str>, depth: usize) {
    if kind(node) == "RecordDecl"
        && flag(node, "completeDefinition")
        && text(node, "tagUsed") == Some("struct")
    {
        found.insert(name(node));
    }
    // serde_json limits nesting to 128.
    if depth < 128 {
        for child in children(node) {
            complete_structs(child, found, depth + 1);
        }
    }
}

impl<'a> Tables<'a> {
    fn new(nodes: &'a [Value]) -> Self {
        let mut complete = BTreeSet::new();
        for node in nodes {
            complete_structs(node, &mut complete, 0);
        }
        let mut tables = Self {
            typedefs: BTreeMap::new(),
            enums: BTreeMap::new(),
            anonymous: BTreeMap::new(),
            builtins: nodes
                .iter()
                .filter(|node| kind(node) == "FunctionDecl" && flag(node, "isImplicit"))
                .filter_map(|node| text(node, "id"))
                .collect(),
            incomplete: nodes
                .iter()
                .filter(|node| {
                    kind(node) == "RecordDecl" && text(node, "tagUsed") == Some("struct")
                })
                .map(name)
                .filter(|tag| !tag.is_empty() && !complete.contains(tag))
                .collect(),
        };
        for node in nodes.iter().filter(|node| kind(node) == "TypedefDecl") {
            let (spelled, desugared) = node_type(node);
            tables.typedefs.entry(name(node)).or_insert(Typedef {
                spelled,
                desugared,
                poisoned: has_attribute(node, LAYOUT_ATTRIBUTES),
            });
            let owned = children(node)
                .next()
                .and_then(|elaborated| elaborated.get("ownedTagDecl"));
            if let Some(tag) = owned
                && name(tag).is_empty()
                && let Some(id) = text(tag, "id")
            {
                tables
                    .anonymous
                    .entry(id)
                    .or_insert((name(node), position(node)));
            }
        }
        for node in nodes.iter().filter(|node| kind(node) == "EnumDecl") {
            let enumerators = tables.enumerators(node);
            // A forward declaration has no constants.
            let Some(key) = tables.enum_key(node).filter(|_| !enumerators.is_empty()) else {
                continue;
            };
            let int = node.get("fixedUnderlyingType").is_none()
                && !has_attribute(node, &["PackedAttr"])
                && enumerators.iter().all(|enumerator| {
                    enumerator
                        .value
                        .is_some_and(|value| i32::try_from(value).is_ok())
                });
            // Two enums spelled the same way (a tag and an anonymous enum's typedef)
            // are ambiguous, so neither converts.
            tables
                .enums
                .entry(key)
                .and_modify(|known| *known = false)
                .or_insert(int);
        }
        tables
    }

    fn enum_key(&self, node: &Value) -> Option<String> {
        let tag = match name(node) {
            "" => self.anonymous.get(text(node, "id")?)?.0,
            tag => tag,
        };
        Some(format!("enum {tag}"))
    }

    /// The constants of an enum with their values. C numbers a constant without an
    /// initializer as the previous one plus 1 (the first is 0); an initializer is a
    /// `ConstantExpr` with its value, maybe converted by an `ImplicitCastExpr` to the
    /// enumerator's type. Any other initializer leaves the value, and the values that
    /// follow from it, unknown.
    fn enumerators(&self, node: &'a Value) -> Vec<Enumerator<'a>> {
        let mut previous = Some(-1i128);
        let mut enumerators = Vec::new();
        for constant in children(node).filter(|child| kind(child) == "EnumConstantDecl") {
            let value = match children(constant).next() {
                None => previous.and_then(|value| value.checked_add(1)),
                Some(initializer) => self.constant_value(initializer, 0),
            };
            previous = value;
            enumerators.push(Enumerator {
                node: constant,
                value,
            });
        }
        enumerators
    }

    fn constant_value(&self, node: &Value, depth: usize) -> Option<i128> {
        match kind(node) {
            "ConstantExpr" => text(node, "value")?.parse().ok(),
            "ImplicitCastExpr"
                if depth < MAX_TYPE_NESTING
                    && matches!(text(node, "castKind"), Some("IntegralCast" | "NoOp")) =>
            {
                let value = self.constant_value(children(node).next()?, depth + 1)?;
                let (spelled, desugared) = node_type(node);
                let (ty, _) = self.c_type(spelled, desugared);
                let CType::Named(target) = ty else {
                    return None;
                };
                convert(value, &target)
            }
            _ => None,
        }
    }

    /// The type of a declaration with typedefs expanded: the spelling Clang printed,
    /// or its desugared spelling when this parser cannot read the printed one
    /// (`typeof`, for example).
    fn c_type(&self, spelled: &str, desugared: Option<&str>) -> (CType, Qualifiers) {
        let parsed = parse_type(spelled).or_else(|| desugared.and_then(parse_type));
        match parsed {
            Some((ty, qualifiers)) => self.resolve(ty, qualifiers, 0),
            None => (CType::Unsupported, Qualifiers::default()),
        }
    }

    /// Expands typedef names, at most `MAX_TYPEDEF_DEPTH` in a chain. The qualifiers of
    /// an expanded typedef join those of the place that names it.
    fn resolve(&self, ty: CType, qualifiers: Qualifiers, depth: usize) -> (CType, Qualifiers) {
        match ty {
            CType::Named(name) => match self.typedefs.get(name.as_str()) {
                None => (CType::Named(name), qualifiers),
                Some(typedef) if typedef.poisoned || depth >= MAX_TYPEDEF_DEPTH => {
                    (CType::Unsupported, qualifiers)
                }
                Some(typedef) => {
                    // An anonymous tag's typedef desugars to its own name.
                    let parsed = parse_type(typedef.spelled).or_else(|| {
                        typedef
                            .desugared
                            .filter(|desugared| *desugared != name)
                            .and_then(parse_type)
                    });
                    match parsed {
                        Some((inner, more)) => {
                            self.resolve(inner, qualifiers.union(more), depth + 1)
                        }
                        None => (CType::Unsupported, qualifiers),
                    }
                }
            },
            CType::Pointer(pointee, pointee_qualifiers) => {
                let (pointee, pointee_qualifiers) =
                    self.resolve(*pointee, pointee_qualifiers, depth);
                (
                    CType::Pointer(Box::new(pointee), pointee_qualifiers),
                    qualifiers,
                )
            }
            CType::Function(result, parameters) => {
                let result = self.resolve(*result, Qualifiers::default(), depth).0;
                let parameters = parameters
                    .into_iter()
                    .map(|parameter| self.resolve(parameter, Qualifiers::default(), depth).0)
                    .collect();
                (CType::Function(Box::new(result), parameters), qualifiers)
            }
            CType::Unsupported => (CType::Unsupported, qualifiers),
        }
    }

    /// The Tsuzuri scalar for a builtin or an `int` enum.
    fn scalar(&self, ty: &CType, role: Role) -> Option<&'static str> {
        let CType::Named(name) = ty else {
            return None;
        };
        if let Some(scalar) = Scalar::of(name) {
            return scalar.in_role(role);
        }
        (name.starts_with("enum ") && self.enums.get(name.as_str()) == Some(&true)).then_some("i32")
    }
}

struct Enumerator<'a> {
    node: &'a Value,
    value: Option<i128>,
}

/// C's conversion of an integer constant to an integer type (wrapping, as Clang does).
fn convert(value: i128, target: &str) -> Option<i128> {
    let (bits, signed) = match target {
        "signed char" => (8, true),
        "unsigned char" | "_Bool" => (8, false),
        "short" => (16, true),
        "unsigned short" => (16, false),
        "int" => (32, true),
        "unsigned int" => (32, false),
        "long" | "long long" => (64, true),
        "unsigned long" | "unsigned long long" => (64, false),
        _ => return None,
    };
    let modulus = 1i128 << bits;
    let wrapped = value.rem_euclid(modulus);
    Some(if signed && wrapped >= modulus / 2 {
        wrapped - modulus
    } else {
        wrapped
    })
}

// ---------------------------------------------------------------------------
// Names

fn ascii_identifier(name: &str) -> bool {
    let mut bytes = name.bytes();
    bytes
        .next()
        .is_some_and(|first| first == b'_' || first.is_ascii_alphabetic())
        && bytes.all(|byte| byte == b'_' || byte.is_ascii_alphanumeric())
}

/// `glClearColor` → `gl_clear_color`: an underscore before each uppercase letter that
/// follows a lowercase letter or a digit, then ASCII lowercase.
fn snake_case(name: &str) -> String {
    let mut result = String::with_capacity(name.len() + 4);
    let mut previous: Option<char> = None;
    for character in name.chars() {
        if character.is_ascii_uppercase()
            && previous
                .is_some_and(|previous| previous.is_ascii_lowercase() || previous.is_ascii_digit())
        {
            result.push('_');
        }
        result.push(character.to_ascii_lowercase());
        previous = Some(character);
    }
    result
}

/// `point_t` → `PointT`, `SDL_Rect` → `SDLRect`; a `C` prefix when the result would
/// not start with an uppercase letter.
fn pascal_case(name: &str) -> String {
    let mut result: String = name
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            let first = characters.next().map(|first| first.to_ascii_uppercase());
            first.into_iter().chain(characters).collect::<String>()
        })
        .collect();
    if !result.starts_with(|first: char| first.is_ascii_uppercase()) {
        result.insert(0, 'C');
    }
    result
}

/// Whether the lexer reads `name` as a plain identifier rather than a keyword.
fn plain_identifier(name: &str) -> bool {
    crate::lexer::lex(name).is_ok_and(|tokens| {
        matches!(
            tokens.as_slice(),
            [first, ..] if first.kind == crate::syntax::TokenKind::Ident(name.to_owned())
        ) && tokens.len() == 2
    })
}

/// A function or constant name the checker accepts: keywords, `_`, and the
/// unqualified builtins (`sqrt`, `abs`, ...) get a trailing `_`.
fn value_name(name: String) -> String {
    if !plain_identifier(&name)
        || name == "_"
        || crate::check::Builtin::ALL
            .iter()
            .any(|builtin| builtin.name() == name)
    {
        name + "_"
    } else {
        name
    }
}

/// A record, alias, or extern type name the checker accepts.
fn type_name(name: String) -> String {
    if !plain_identifier(&name) || crate::check::reserved_type_name(&name) {
        name + "_"
    } else {
        name
    }
}

fn field_name(name: &str) -> String {
    value_name(snake_case(name))
}

/// Comment text with every character outside 0x20–0x7E replaced by `?`, so a file name,
/// a type, or a version cannot start a new line of generated code.
fn sanitize(text: &str) -> String {
    text.chars()
        .map(|character| {
            if (' '..='~').contains(&character) {
                character
            } else {
                '?'
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Output

/// The decision for a declaration that defines a Tsuzuri type, made before any line
/// is written because functions may name a struct declared after them.
enum TypeDecision {
    Line(String),
    /// The C name, the reason, and where to report it when not at the declaration.
    Skip(String, String, Option<(usize, usize)>),
}

/// What the annotations ask of one parameter of a function.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Annotated {
    Plain,
    /// `--consume`: the handle moves into the call.
    Consumed,
    /// `--buffer`: the pointer of a buffer whose length is the parameter at this index.
    Pointer(usize),
    /// `--buffer`: the length, passed with its pointer.
    Length,
}

struct Emitter<'t, 'a> {
    tables: &'t Tables<'a>,
    /// The prefix the object format adds to C symbols (`_` on Mach-O).
    symbol_prefix: &'static str,
    buffers: &'t [BufferAnnotation],
    consumes: &'t [ConsumeAnnotation],
    values: BTreeSet<String>,
    types: BTreeSet<String>,
    /// `TAG` → the generated record of `struct TAG`.
    records: BTreeMap<&'a str, String>,
    /// `TAG` → the generated `extern type` of the opaque `struct TAG`.
    handles: BTreeMap<&'a str, String>,
    decisions: BTreeMap<usize, TypeDecision>,
    /// The functions of the header, for checking that each annotation names one.
    functions: BTreeSet<&'a str>,
    lines: Vec<String>,
    skipped: Vec<Skipped>,
}

impl<'t, 'a> Emitter<'t, 'a> {
    fn new(tables: &'t Tables<'a>, target: &str, extras: &Extras<'t>) -> Self {
        Self {
            tables,
            symbol_prefix: if target.contains("apple") || target.contains("darwin") {
                "_"
            } else {
                ""
            },
            buffers: extras.buffers,
            consumes: extras.consumes,
            values: BTreeSet::new(),
            types: BTreeSet::new(),
            records: BTreeMap::new(),
            handles: BTreeMap::new(),
            decisions: BTreeMap::new(),
            functions: BTreeSet::new(),
            lines: Vec::new(),
            skipped: Vec::new(),
        }
    }

    /// Names the types of the header in header order: records, extern types, and type
    /// aliases share one namespace, and a later declaration that collides is skipped.
    fn collect_types(&mut self, declarations: &[Declaration<'a>]) {
        for (index, declaration) in declarations.iter().enumerate() {
            if !declaration.owned {
                continue;
            }
            let decision = match declaration.kind {
                "RecordDecl" if flag(declaration.node, "completeDefinition") => {
                    self.record(declaration.node)
                }
                "RecordDecl" => self.handle(declaration.node),
                "TypedefDecl" => self.alias(declaration.node),
                _ => None,
            };
            if let Some(decision) = decision {
                self.decisions.insert(index, decision);
            }
        }
    }

    /// An `extern type` for a struct that the header declares first and that no
    /// declaration of the translation unit defines. C code can hold such a struct only
    /// through pointers, which the library allocates, so a pointer to it is exactly an
    /// E12 handle: one pointer-sized value that Tsuzuri never dereferences.
    fn handle(&mut self, node: &'a Value) -> Option<TypeDecision> {
        let tag = name(node);
        if text(node, "tagUsed") != Some("struct")
            || node.get("previousDecl").is_some()
            || !self.tables.incomplete.contains(tag)
        {
            return None;
        }
        let skip = |reason: String| Some(TypeDecision::Skip(tag.to_owned(), reason, None));
        if !ascii_identifier(tag) {
            return skip("name is not an ASCII C identifier".into());
        }
        let handle = type_name(pascal_case(tag));
        if !self.types.insert(handle.clone()) {
            return skip(format!(
                "name '{handle}' collides with an earlier declaration"
            ));
        }
        self.handles.insert(tag, handle.clone());
        Some(TypeDecision::Line(format!("extern type {handle}")))
    }

    fn record(&mut self, node: &'a Value) -> Option<TypeDecision> {
        let tag = name(node);
        let skip = |name: &str, reason: &str| {
            Some(TypeDecision::Skip(name.to_owned(), reason.to_owned(), None))
        };
        if text(node, "tagUsed") == Some("union") {
            let shown = if tag.is_empty() {
                "(anonymous union)"
            } else {
                tag
            };
            return skip(shown, "C union");
        }
        if text(node, "tagUsed") != Some("struct") {
            return None;
        }
        if tag.is_empty() {
            // Reported at the typedef that names it, if any.
            let named = text(node, "id").and_then(|id| self.tables.anonymous.get(id));
            return Some(TypeDecision::Skip(
                named
                    .map_or("(anonymous struct)", |(name, _)| name)
                    .to_owned(),
                "anonymous struct; give the struct a tag".to_owned(),
                named.map(|(_, at)| *at),
            ));
        }
        if !ascii_identifier(tag) {
            return skip(tag, "name is not an ASCII C identifier");
        }
        if has_attribute(node, LAYOUT_ATTRIBUTES) {
            return skip(tag, "struct has a packing or alignment attribute");
        }
        let fields: Vec<_> = children(node)
            .filter(|child| kind(child) == "FieldDecl")
            .collect();
        if fields.is_empty() {
            return skip(tag, "struct has no fields");
        }
        let field_label = |field: &Value| match name(field) {
            "" => "(anonymous)".to_owned(),
            name => name.to_owned(),
        };
        if let Some(field) = fields.iter().find(|field| flag(field, "isBitfield")) {
            return skip(tag, &format!("bit-field '{}'", field_label(field)));
        }
        if let Some(field) = fields
            .iter()
            .find(|field| has_attribute(field, LAYOUT_ATTRIBUTES))
        {
            return skip(
                tag,
                &format!(
                    "field '{}' has an alignment or packing attribute",
                    field_label(field)
                ),
            );
        }
        let mut converted = Vec::new();
        for field in &fields {
            let (spelled, desugared) = node_type(field);
            let (ty, _) = self.tables.c_type(spelled, desugared);
            let Some(scalar) = self.tables.scalar(&ty, Role::Field) else {
                return skip(
                    tag,
                    &format!(
                        "field '{}' has unsupported type '{}'",
                        field_label(field),
                        scrub(spelled)
                    ),
                );
            };
            converted.push((name(field), scalar));
        }
        let mut names = BTreeSet::new();
        let mut rendered = Vec::new();
        for (field, scalar) in converted {
            if !ascii_identifier(field) {
                return skip(
                    tag,
                    &format!("field '{field}' is not an ASCII C identifier"),
                );
            }
            let converted = field_name(field);
            if !names.insert(converted.clone()) {
                return skip(
                    tag,
                    &format!("field '{field}' collides with an earlier field as '{converted}'"),
                );
            }
            rendered.push(format!("{converted}: {scalar}"));
        }
        let record = type_name(pascal_case(tag));
        if !self.types.insert(record.clone()) {
            return skip(
                tag,
                &format!("name '{record}' collides with an earlier declaration"),
            );
        }
        self.records.insert(tag, record.clone());
        Some(TypeDecision::Line(format!(
            "record {record} {{ {} }}",
            rendered.join(", ")
        )))
    }

    /// A type alias for a typedef that resolves to a scalar; other typedefs produce
    /// nothing, because signatures use the resolved types.
    fn alias(&mut self, node: &'a Value) -> Option<TypeDecision> {
        let typedef = name(node);
        let (ty, _) = self.tables.c_type(typedef, None);
        let CType::Named(resolved) = ty else {
            return None;
        };
        let scalar = Scalar::of(&resolved)?.name();
        if !ascii_identifier(typedef) {
            return Some(TypeDecision::Skip(
                typedef.to_owned(),
                "name is not an ASCII C identifier".to_owned(),
                None,
            ));
        }
        let alias = type_name(pascal_case(typedef));
        if !self.types.insert(alias.clone()) {
            return Some(TypeDecision::Skip(
                typedef.to_owned(),
                format!("name '{alias}' collides with an earlier declaration"),
                None,
            ));
        }
        Some(TypeDecision::Line(format!("type {alias} = {scalar}")))
    }

    fn declaration(&mut self, index: usize, declaration: &Declaration<'a>) -> Result<(), Failure> {
        let node = declaration.node;
        let at = (declaration.offset, declaration.length);
        match declaration.kind {
            "RecordDecl" | "TypedefDecl" => match self.decisions.remove(&index) {
                Some(TypeDecision::Line(line)) => self.lines.push(line),
                Some(TypeDecision::Skip(name, reason, place)) => {
                    self.skip(&name, reason, place.unwrap_or(at))
                }
                None => {}
            },
            "EnumDecl" => self.constants(node),
            "FunctionDecl" => self.function(node, at)?,
            "VarDecl" => self.skip(name(node), "global variable".into(), at),
            _ => {}
        }
        Ok(())
    }

    /// A constant for an object-like macro whose replacement is one integer literal.
    fn definition(&mut self, definition: &Definition) {
        let at = (definition.offset, definition.length);
        let (value, scalar) = match macro_value(definition.body) {
            MacroValue::NotInteger => return,
            MacroValue::Invalid(reason) => return self.skip(definition.name, reason, at),
            MacroValue::Integer(value, scalar) => (value, scalar),
        };
        if !ascii_identifier(definition.name) {
            return self.skip(
                definition.name,
                "name is not an ASCII C identifier".into(),
                at,
            );
        }
        let tsuzuri = value_name(definition.name.to_owned());
        if !self.values.insert(tsuzuri.clone()) {
            return self.skip(
                definition.name,
                format!("name '{tsuzuri}' collides with an earlier declaration"),
                at,
            );
        }
        self.lines
            .push(format!("const {tsuzuri}: {} = {value}", scalar.name()));
    }

    fn constants(&mut self, node: &'a Value) {
        for enumerator in self.tables.enumerators(node) {
            let constant = name(enumerator.node);
            let at = position(enumerator.node);
            if !ascii_identifier(constant) {
                self.skip(constant, "name is not an ASCII C identifier".into(), at);
                continue;
            }
            let Some(value) = enumerator.value else {
                self.skip(
                    constant,
                    "enumerator value is not an integer constant in the clang AST".into(),
                    at,
                );
                continue;
            };
            if i32::try_from(value).is_err() {
                self.skip(
                    constant,
                    format!("enumerator value {value} does not fit in i32"),
                    at,
                );
                continue;
            }
            let tsuzuri = value_name(constant.to_owned());
            if !self.values.insert(tsuzuri.clone()) {
                self.skip(
                    constant,
                    format!("name '{tsuzuri}' collides with an earlier declaration"),
                    at,
                );
                continue;
            }
            self.lines.push(format!("const {tsuzuri}: i32 = {value}"));
        }
    }

    fn function(&mut self, node: &'a Value, at: (usize, usize)) -> Result<(), Failure> {
        // A redeclaration produces nothing. Clang declares library builtins such as
        // `sqrt` implicitly at their first mention, so a header's own declaration of
        // one names that implicit declaration as its previous one and still counts.
        if text(node, "previousDecl")
            .is_some_and(|previous| !self.tables.builtins.contains(previous))
        {
            return Ok(());
        }
        let symbol = name(node);
        self.functions.insert(symbol);
        let parameters: Vec<&Value> = children(node)
            .filter(|child| kind(child) == "ParmVarDecl")
            .collect();
        let plan = self.annotation_plan(symbol, &parameters)?;
        match self.function_line(node, symbol, &parameters, &plan) {
            Ok(line) => self.lines.push(line),
            Err(reason) => self.skip(symbol, reason, at),
        }
        Ok(())
    }

    /// What the `--buffer` and `--consume` annotations ask of each parameter.
    fn annotation_plan(
        &self,
        symbol: &str,
        parameters: &[&Value],
    ) -> Result<Vec<Annotated>, Failure> {
        let mut plan = vec![Annotated::Plain; parameters.len()];
        let index_of = |option: &str, parameter: &ParameterName| match parameter {
            ParameterName::Position(position) if *position <= parameters.len() => Ok(position - 1),
            ParameterName::Position(position) => Err(Failure::Annotation(format!(
                "{option} names parameter {position} of '{symbol}', which has {} parameter{}",
                parameters.len(),
                if parameters.len() == 1 { "" } else { "s" }
            ))),
            ParameterName::Name(wanted) => parameters
                .iter()
                .position(|parameter| name(parameter) == wanted)
                .ok_or_else(|| {
                    Failure::Annotation(format!(
                        "{option} names parameter '{wanted}', which '{symbol}' does not have"
                    ))
                }),
        };
        let twice = |option: &str| {
            Failure::Annotation(format!(
                "{option} names a parameter of '{symbol}' that another annotation already names"
            ))
        };
        for consume in self
            .consumes
            .iter()
            .filter(|consume| consume.function == symbol)
        {
            let index = index_of("--consume", &consume.parameter)?;
            if plan[index] != Annotated::Plain {
                return Err(twice("--consume"));
            }
            plan[index] = Annotated::Consumed;
        }
        for buffer in self
            .buffers
            .iter()
            .filter(|buffer| buffer.function == symbol)
        {
            let pointer = index_of("--buffer", &buffer.pointer)?;
            let length = index_of("--buffer", &buffer.length)?;
            if pointer == length
                || plan[pointer] != Annotated::Plain
                || plan[length] != Annotated::Plain
            {
                return Err(twice("--buffer"));
            }
            plan[pointer] = Annotated::Pointer(length);
            plan[length] = Annotated::Length;
        }
        Ok(plan)
    }

    /// Every annotation must name a function of the header.
    fn check_annotations(&self) -> Result<(), Failure> {
        let names = self
            .buffers
            .iter()
            .map(|buffer| ("--buffer", buffer.function.as_str()))
            .chain(
                self.consumes
                    .iter()
                    .map(|consume| ("--consume", consume.function.as_str())),
            );
        for (option, function) in names {
            if !self.functions.contains(function) {
                return Err(Failure::Annotation(format!(
                    "{option} names '{function}', which the header does not declare as a function"
                )));
            }
        }
        Ok(())
    }

    /// The `extern` line for a function, or why it cannot have one. The checks run in
    /// the order of the `W2002` reasons in the language reference.
    fn function_line(
        &mut self,
        node: &'a Value,
        symbol: &str,
        parameters: &[&Value],
        plan: &[Annotated],
    ) -> Result<String, String> {
        if text(node, "storageClass") == Some("static") {
            return Err("function has internal linkage (static)".into());
        }
        if flag(node, "inline") {
            return Err("inline function has no guaranteed external definition".into());
        }
        if flag(node, "variadic") {
            return Err("variadic function".into());
        }
        let (spelled, _) = node_type(node);
        let shape = function_shape(spelled)
            .ok_or_else(|| format!("function type '{}' is not understood", scrub(spelled)))?;
        if !shape.prototype {
            return Err("function has no prototype".into());
        }
        if !ascii_identifier(symbol) {
            return Err("name is not an ASCII C identifier".into());
        }
        if crate::abi::RESERVED_SYMBOL_PREFIXES
            .iter()
            .any(|prefix| symbol.starts_with(prefix))
        {
            return Err("symbol uses the reserved tz_, tsuzuri, or __ prefix".into());
        }
        if crate::abi::RESERVED_HOST_SYMBOLS.contains(&symbol) {
            return Err("symbol is reserved by the Tsuzuri runtime".into());
        }
        if symbol.len() > 255 {
            return Err("symbol is longer than 255 bytes".into());
        }
        // An asm label or `overloadable` gives the function another symbol.
        let renamed =
            match text(node, "mangledName") {
                Some(mangled) => (mangled != format!("{}{symbol}", self.symbol_prefix))
                    .then(|| mangled.to_owned()),
                None => has_attribute(node, &["AsmLabelAttr", "OverloadableAttr"])
                    .then(|| "?".to_owned()),
            };
        if let Some(mangled) = renamed {
            return Err(format!(
                "symbol is renamed to '{}' by an asm label or overloading",
                sanitize(&mangled)
            ));
        }
        if let Some(attribute) = shape
            .attributes
            .iter()
            .find(|attribute| !matches!(attribute.as_str(), "noreturn" | "__noreturn__"))
        {
            return Err(format!(
                "function type has the attribute '{attribute}', which may change its calling convention"
            ));
        }
        let mut converted = Vec::new();
        for (index, parameter) in parameters.iter().enumerate() {
            let number = index + 1;
            if has_attribute(parameter, &["PassObjectSizeAttr"]) {
                return Err(format!(
                    "parameter {number} has the pass_object_size attribute, which adds a hidden argument"
                ));
            }
            let (spelled, desugared) = node_type(parameter);
            let unsupported = || {
                format!(
                    "parameter {number} has unsupported type '{}'",
                    scrub(spelled)
                )
            };
            match plan[index] {
                Annotated::Plain => converted.push(
                    self.value_type(&self.tables.c_type(spelled, desugared).0, Role::Parameter)
                        .ok_or_else(unsupported)?,
                ),
                Annotated::Consumed => converted.push(self.consumed(spelled, desugared).ok_or_else(
                    || format!("--consume names parameter {number}, which is not a pointer to an opaque struct of the header"),
                )?),
                Annotated::Pointer(length) => converted.push(self.buffer(parameters, index, length)?),
                // Passed together with its pointer.
                Annotated::Length => {}
            }
        }
        let result = match &shape.result {
            Ok(spelled) => self.value_type(&self.tables.c_type(spelled, None).0, Role::Result),
            Err(_) => None,
        }
        .ok_or_else(|| {
            let (Ok(spelled) | Err(spelled)) = &shape.result;
            format!("result has unsupported type '{}'", scrub(spelled))
        })?;
        let tsuzuri = value_name(snake_case(symbol));
        if !self.values.insert(tsuzuri.clone()) {
            return Err(format!(
                "name '{tsuzuri}' collides with an earlier declaration"
            ));
        }
        Ok(render_function(symbol, &tsuzuri, &converted, &result))
    }

    /// The Tsuzuri type of a resolved C type in a position, or `None` when the ABI
    /// does not match exactly.
    fn value_type(&self, ty: &CType, role: Role) -> Option<String> {
        if let Some(scalar) = self.tables.scalar(ty, role) {
            return Some(scalar.to_owned());
        }
        match ty {
            CType::Named(name) if name == "void" => {
                matches!(role, Role::Result | Role::CallbackResult).then(|| "unit".to_owned())
            }
            CType::Pointer(pointee, qualifiers) if !qualifiers.volatile => match pointee.as_ref() {
                CType::Named(pointee) => {
                    let tag = pointee.strip_prefix("struct ")?;
                    if let Some(handle) = self.handles.get(tag) {
                        // Parameters borrow the handle: the call neither consumes nor
                        // copies it, and what C does behind the pointer is invisible to
                        // Tsuzuri. A result is a new handle that the caller owns, except
                        // a pointer to const, which can only be borrowed.
                        return match role {
                            Role::Parameter | Role::CallbackParameter => {
                                Some(format!("ref {handle}"))
                            }
                            Role::Result if !qualifiers.constant => Some(handle.clone()),
                            _ => None,
                        };
                    }
                    // `const struct TAG *` borrows a generated record. Without `const` the
                    // host could write into the temporary copy the ABI passes.
                    (role == Role::Parameter && qualifiers.constant)
                        .then(|| self.records.get(tag).map(|record| format!("ref {record}")))
                        .flatten()
                }
                CType::Function(result, parameters) if role == Role::Parameter => {
                    self.callback(result, parameters)
                }
                _ => None,
            },
            _ => None,
        }
    }

    /// A function pointer parameter as an E12 callback: its parameters are scalars or
    /// opaque handles that C passes to Tsuzuri, and its result is a scalar or `void`.
    fn callback(&self, result: &CType, parameters: &[CType]) -> Option<String> {
        let mut signature = parameters
            .iter()
            .map(|parameter| self.value_type(parameter, Role::CallbackParameter))
            .collect::<Option<Vec<_>>>()?;
        if signature.is_empty() {
            signature.push("unit".into());
        }
        signature.push(self.value_type(result, Role::CallbackResult)?);
        Some(format!("({})", signature.join(" -> ")))
    }

    /// A parameter that `--consume` names: the handle moves into the call.
    fn consumed(&self, spelled: &str, desugared: Option<&str>) -> Option<String> {
        let (CType::Pointer(pointee, qualifiers), _) = self.tables.c_type(spelled, desugared)
        else {
            return None;
        };
        let CType::Named(pointee) = *pointee else {
            return None;
        };
        let tag = pointee.strip_prefix("struct ")?;
        (!qualifiers.volatile)
            .then(|| self.handles.get(tag).cloned())
            .flatten()
    }

    /// The pointer and the length that `--buffer` names, as one `ref [T]` parameter.
    /// The E05 buffer ABI passes exactly a pointer to the elements and an `int64_t`
    /// element count, so the C parameters must be a pointer to const elements of the
    /// same representation, followed directly by a 64-bit integer count.
    fn buffer(
        &self,
        parameters: &[&Value],
        pointer: usize,
        length: usize,
    ) -> Result<String, String> {
        let number = pointer + 1;
        if length != pointer + 1 {
            return Err(format!(
                "--buffer pairs parameter {number} with parameter {}, but the buffer ABI passes the length right after the pointer",
                length + 1
            ));
        }
        let (spelled, desugared) = node_type(parameters[pointer]);
        let (ty, _) = self.tables.c_type(spelled, desugared);
        let CType::Pointer(pointee, qualifiers) = ty else {
            return Err(format!(
                "--buffer names parameter {number}, which has type '{}', not a pointer",
                scrub(spelled)
            ));
        };
        if !qualifiers.constant || qualifiers.volatile {
            return Err(format!(
                "buffer parameter {number} has type '{}', not a pointer to const; the host could write into a shared Tsuzuri array",
                scrub(spelled)
            ));
        }
        let element = match *pointee {
            CType::Named(element) => match element.as_str() {
                "long" | "long long" => "i64",
                "double" => "f64",
                // Bytes: `void` buffers are counted in bytes.
                "unsigned char" | "char" | "void" => "ubyte",
                _ => "",
            },
            _ => "",
        };
        if element.is_empty() {
            return Err(format!(
                "buffer parameter {number} has type '{}'; Tsuzuri buffers hold 64-bit integers, doubles, or bytes",
                scrub(spelled)
            ));
        }
        let (spelled, desugared) = node_type(parameters[length]);
        let count = self.tables.c_type(spelled, desugared).0;
        let wide = matches!(&count, CType::Named(name) if matches!(name.as_str(), "long" | "long long" | "unsigned long" | "unsigned long long"));
        if !wide {
            return Err(format!(
                "buffer length parameter {} has type '{}', not a 64-bit integer",
                length + 1,
                scrub(spelled)
            ));
        }
        Ok(format!("ref [{element}]"))
    }

    fn skip(&mut self, name: &str, reason: String, (offset, length): (usize, usize)) {
        self.lines.push(format!(
            "// skipped {}: {}",
            sanitize(name),
            sanitize(&reason)
        ));
        self.skipped.push(Skipped {
            name: name.to_owned(),
            reason,
            offset,
            length,
        });
    }

    fn finish(self, header: &HeaderInfo) -> Generated {
        let mut text = format!(
            "{MARKER}\n// header: {} sha256={}\n// clang: {}\n// target: {}\n",
            sanitize(header.file_name),
            sanitize(header.sha256),
            sanitize(header.clang_version),
            sanitize(header.target),
        );
        // The annotations change the output, so it records them to be regenerated.
        let options: Vec<String> = self
            .buffers
            .iter()
            .map(|buffer| {
                format!(
                    "--buffer {}:{}:{}",
                    buffer.function, buffer.pointer, buffer.length
                )
            })
            .chain(
                self.consumes
                    .iter()
                    .map(|consume| format!("--consume {}:{}", consume.function, consume.parameter)),
            )
            .collect();
        if !options.is_empty() {
            text.push_str(&format!("// options: {}\n", sanitize(&options.join(" "))));
        }
        if !self.lines.is_empty() {
            text.push('\n');
            for line in &self.lines {
                text.push_str(line);
                text.push('\n');
            }
        }
        Generated {
            text,
            skipped: self.skipped,
        }
    }
}

/// The one place that spells an E12 link-named extern declaration.
fn render_function(symbol: &str, name: &str, parameters: &[String], result: &str) -> String {
    let mut signature: Vec<&str> = if parameters.is_empty() {
        vec!["unit"]
    } else {
        parameters.iter().map(String::as_str).collect()
    };
    signature.push(result);
    format!(
        "extern \"{symbol}\" def {name} :: {}",
        signature.join(" -> ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parsed(text: &str) -> CType {
        parse_type(text).map_or(CType::Unsupported, |(ty, _)| ty)
    }

    #[test]
    fn parses_clang_type_spellings() {
        let named = |name: &str| CType::Named(name.into());
        let constant = Qualifiers {
            constant: true,
            volatile: false,
        };
        assert_eq!(parsed("unsigned long"), named("unsigned long"));
        assert_eq!(parse_type("const int"), Some((named("int"), constant)));
        assert_eq!(
            parsed("const struct point *const"),
            CType::Pointer(Box::new(named("struct point")), constant)
        );
        assert_eq!(
            parsed("int * _Nonnull"),
            CType::Pointer(Box::new(named("int")), Qualifiers::default())
        );
        assert_eq!(
            parsed("int (*)(int, const char *)"),
            CType::Pointer(
                Box::new(CType::Function(
                    Box::new(named("int")),
                    vec![
                        named("int"),
                        CType::Pointer(Box::new(named("char")), constant)
                    ]
                )),
                Qualifiers::default()
            )
        );
        for unsupported in [
            "int (^)(int)",
            "int [4]",
            "struct (unnamed struct at /h/a.h:1:1)",
            "__attribute__((__vector_size__(4 * sizeof(int)))) int",
            "typeof (sizeof (0))",
        ] {
            assert!(parse_type(unsupported).is_none(), "{unsupported}");
        }
        assert_eq!(
            parsed("int (*)(int, ...)"),
            CType::Pointer(Box::new(CType::Unsupported), Qualifiers::default())
        );
    }

    #[test]
    fn splits_function_types() {
        let shape = function_shape("struct opaque *(void)").unwrap();
        assert_eq!(shape.result, Ok("struct opaque *".into()));
        assert!(shape.prototype && shape.attributes.is_empty());
        let shape = function_shape("void (int) __attribute__((noreturn))").unwrap();
        assert_eq!(shape.attributes, ["noreturn"]);
        let shape = function_shape("__attribute__((preserve_most)) int (int)").unwrap();
        assert_eq!(shape.result, Ok("int".into()));
        assert_eq!(shape.attributes, ["preserve_most"]);
        assert!(!function_shape("int ()").unwrap().prototype);
        assert_eq!(
            function_shape("int (*(int))(void)").unwrap().result,
            Err("int (*)(void)".into())
        );
        let anonymous = function_shape("struct (unnamed struct at /h/a.h:1:1) (void)").unwrap();
        assert_eq!(
            anonymous.result,
            Ok("struct (unnamed struct at /h/a.h:1:1)".into())
        );
        assert_eq!(
            scrub("struct (unnamed struct at /h/a.h:1:1) *"),
            "struct (unnamed struct) *"
        );
    }

    #[test]
    fn converts_enum_initializer_values_like_c() {
        assert_eq!(convert(4294967295, "int"), Some(-1));
        assert_eq!(convert(-1, "unsigned int"), Some(4294967295));
        assert_eq!(convert(5, "long double"), None);
    }

    #[test]
    fn reads_line_markers_and_lines_like_clang() {
        assert_eq!(
            linemarker("# 3 \"/h/a\\\\b\\\"c\\303\\251\\t.h\" 2 3"),
            Some((3, b"/h/a\\b\"c\xc3\xa9\t.h".to_vec()))
        );
        assert_eq!(
            linemarker("# 1 \"<built-in>\""),
            Some((1, b"<built-in>".to_vec()))
        );
        for other in [
            "#define X 1",
            "# x \"a\"",
            "#pragma once",
            "# 3 \"unterminated",
        ] {
            assert_eq!(linemarker(other), None, "{other}");
        }
        assert_eq!(line_starts(b"a\r\nb\nc\rd"), [0, 3, 5, 7]);
        let text = b"int a;\r\n  #  define  LIMIT 4\n";
        assert_eq!(
            macro_position(text, &line_starts(text), 2, "LIMIT"),
            (21, 5)
        );
        assert_eq!(macro_position(text, &line_starts(text), 9, "LIMIT"), (0, 0));
    }

    #[test]
    fn reads_only_single_integer_literals_from_macros() {
        assert_eq!(macro_value("(-(7))"), MacroValue::Integer(-7, Scalar::I32));
        assert_eq!(macro_value("-0u"), MacroValue::Integer(0, Scalar::I32u));
        assert_eq!(macro_value(".5"), MacroValue::NotInteger);
        assert_eq!(macro_value("1e+5"), MacroValue::NotInteger);
        assert_eq!(macro_value("0x1.8p1"), MacroValue::NotInteger);
        assert_eq!(macro_value("1 2"), MacroValue::NotInteger);
        assert_eq!(macro_value(""), MacroValue::NotInteger);
        assert_eq!(macro_value(&"(".repeat(100)), MacroValue::NotInteger);
    }
}
