use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::check::{
    Builtin, CheckedFunction, CheckedModule, FunctionRef, Local, Type, TypedExpr, TypedExprKind,
};
use crate::diagnostic::{Diagnostic, Span};
use crate::syntax::{BinaryOp, UnaryOp};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Entry {
    Library,
    Console,
}

pub fn emit(module: &CheckedModule, entry: Entry) -> Result<String, Diagnostic> {
    emit_target(module, entry, false)
}

pub fn emit_target(module: &CheckedModule, entry: Entry, wasm: bool) -> Result<String, Diagnostic> {
    if entry == Entry::Console {
        validate_main(module)?;
    }
    let mut output = String::from(
        "; Tsuzuri - deterministic LLVM IR\nsource_filename = \"tsuzuri\"\n%tz.string = type { ptr, i64 }\n",
    );
    for record in &module.records {
        let _ = writeln!(
            output,
            "%tz.record.{} = type {{ {} }}",
            record.name,
            record
                .fields
                .iter()
                .map(|(_, ty)| llvm_type(ty, module))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    output.push_str("\ndeclare void @llvm.trap()\n\n");
    let mut builtins = BTreeSet::new();
    let mut globals = Vec::new();
    for (id, function) in module.functions.iter().enumerate() {
        let emitter = FunctionEmitter {
            module,
            function,
            function_id: id,
            builtins: &mut builtins,
            lines: Vec::new(),
            allocas: Vec::new(),
            locals: BTreeMap::new(),
            next_value: 0,
            next_block: 0,
            block: "loop".into(),
            back_edges: Vec::new(),
            scopes: vec![Vec::new()],
            globals: &mut globals,
        };
        output.push_str(&emitter.emit());
        if function.exported {
            output.push_str(&export_wrapper(function, module));
        }
    }
    for builtin in builtins {
        output.push_str(&emit_builtin(builtin));
    }
    if entry == Entry::Console {
        output.push_str(&console_main(module));
    }
    for global in globals {
        output.push_str(&global);
        output.push('\n');
    }
    if output.contains("@tz_soft_") {
        output = output.replace("declare void @llvm.trap()\n", "");
        output.push_str(include_str!("runtime/numeric.ll"));
    }
    if output.contains("@tz.string.") || output.contains("@tz.free") {
        output.push_str(include_str!("runtime/string.ll"));
        output.push_str(if wasm {
            include_str!("runtime/heap-wasm.ll")
        } else {
            include_str!("runtime/heap-native.ll")
        });
    }
    Ok(output)
}

pub fn header(module: &CheckedModule) -> String {
    let mut output = String::from(
        "/* Generated by Tsuzuri. bool uses int32_t. Narrow integers use normalized 32-bit ABI values. */\n\
         #pragma once\n\
         #include <stdint.h>\n\n\
         #ifdef __cplusplus\n\
         extern \"C\" {\n\
         #endif\n\n",
    );
    for function in &module.functions {
        if !function.exported {
            continue;
        }
        let parameters = if function.signature.parameters.is_empty() {
            "void".into()
        } else {
            function
                .signature
                .parameters
                .iter()
                .enumerate()
                .map(|(id, ty)| format!("{} arg{id}", c_type(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            output,
            "{} tz_{}({parameters});",
            c_type(&function.signature.result),
            function.name
        );
    }
    output.push_str("\n#ifdef __cplusplus\n}\n#endif\n");
    output
}

fn c_type(ty: &Type) -> String {
    match ty {
        Type::Integer(bits, signed) => {
            format!("{}int{}_t", if *signed { "" } else { "u" }, (*bits).max(32))
        }
        Type::Binary(32) => "float".into(),
        Type::Binary(64) => "double".into(),
        Type::Bool => "int32_t".into(),
        Type::Unit => "void".into(),
        _ => unreachable!("the type checker enforces scalar exports"),
    }
}

fn llvm_type(ty: &Type, module: &CheckedModule) -> String {
    match ty {
        Type::Integer(bits, _) | Type::Decimal(bits) | Type::Binary(bits @ (16 | 128)) => {
            format!("i{bits}")
        }
        Type::Binary(32) => "float".into(),
        Type::Binary(64) => "double".into(),
        Type::Binary(_) => unreachable!("binary widths checked"),
        Type::Bool => "i1".into(),
        Type::Unit => "i8".into(),
        Type::String => "%tz.string".into(),
        Type::Record(id) => format!("%tz.record.{}", module.records[*id].name),
        Type::Array(element, length) => {
            format!("[{length} x {}]", llvm_type(element, module))
        }
        Type::Function(_, _) | Type::Reference(..) => "ptr".into(),
    }
}

fn abi_type(ty: &Type) -> String {
    match ty {
        Type::Integer(8 | 16 | 32, _) | Type::Bool => "i32".into(),
        Type::Integer(64, _) => "i64".into(),
        Type::Binary(32) => "float".into(),
        Type::Binary(64) => "double".into(),
        Type::Unit => "void".into(),
        _ => unreachable!("the type checker enforces scalar exports"),
    }
}

fn validate_main(module: &CheckedModule) -> Result<(), Diagnostic> {
    let main = module
        .entry
        .map(|id| &module.functions[id])
        .ok_or_else(|| {
            Diagnostic::new(
                "E2004",
                "an executable requires top-level entry-point code or 'fn main' in Main.tzr; use '--emit object' for a library",
                Span::default(),
            )
        })?;
    if !main.parameters.is_empty()
        || (!main.signature.result.is_scalar()
            && !matches!(main.signature.result, Type::Unit | Type::String))
    {
        return Err(Diagnostic::new(
            "E2004",
            "the Main.tzr entry point must take no arguments and return a number, bool, unit, or string",
            main.span,
        ));
    }
    Ok(())
}

struct FunctionEmitter<'a, 'b> {
    module: &'a CheckedModule,
    function: &'a CheckedFunction,
    function_id: usize,
    builtins: &'b mut BTreeSet<Builtin>,
    lines: Vec<String>,
    allocas: Vec<String>,
    locals: BTreeMap<usize, String>,
    next_value: usize,
    next_block: usize,
    block: String,
    back_edges: Vec<(String, Vec<String>)>,
    scopes: Vec<Vec<(String, Type)>>,
    globals: &'b mut Vec<String>,
}

impl FunctionEmitter<'_, '_> {
    fn emit(mut self) -> String {
        for (index, parameter) in self.function.parameters.iter().enumerate() {
            self.bind_local(parameter, &format!("%p{index}"));
        }
        self.tail(&self.function.body);
        let parameters = self
            .function
            .parameters
            .iter()
            .enumerate()
            .map(|(index, parameter)| format!("{} %arg{index}", self.ty(&parameter.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let mut output = format!(
            "define internal {} @tz.fn.{}({parameters}) nounwind {{\nentry:\n",
            self.ty(&self.function.signature.result),
            self.function.qualified_name()
        );
        for alloca in self.allocas {
            let _ = writeln!(output, "  {alloca}");
        }
        output.push_str("  br label %loop\nloop:\n");
        for (index, parameter) in self.function.parameters.iter().enumerate() {
            let mut incoming = format!("[ %arg{index}, %entry ]");
            for (block, values) in &self.back_edges {
                let _ = write!(incoming, ", [ {}, %{block} ]", values[index]);
            }
            let _ = writeln!(
                output,
                "  %p{index} = phi {} {incoming}",
                llvm_type(&parameter.ty, self.module)
            );
        }
        for line in self.lines {
            output.push_str(&line);
            output.push('\n');
        }
        output.push_str("}\n\n");
        output
    }

    fn ty(&self, ty: &Type) -> String {
        llvm_type(ty, self.module)
    }

    fn fresh(&mut self) -> String {
        let value = format!("%v{}", self.next_value);
        self.next_value += 1;
        value
    }

    fn instruction(&mut self, text: impl Into<String>) {
        self.lines.push(format!("  {}", text.into()));
    }

    fn value(&mut self, instruction: impl Into<String>) -> String {
        let value = self.fresh();
        self.instruction(format!("{value} = {}", instruction.into()));
        value
    }

    fn label(&mut self) -> String {
        let block = format!("b{}", self.next_block);
        self.next_block += 1;
        block
    }

    fn begin(&mut self, block: &str) {
        self.lines.push(format!("{block}:"));
        self.block = block.to_owned();
    }

    fn jump(&mut self, block: &str) {
        self.instruction(format!("br label %{block}"));
    }

    fn branch(&mut self, condition: &str, yes: &str, no: &str) {
        self.instruction(format!("br i1 {condition}, label %{yes}, label %{no}"));
    }

    fn guard(&mut self, valid: &str) {
        let success = self.label();
        let failure = self.label();
        self.branch(valid, &success, &failure);
        self.begin(&failure);
        self.instruction("call void @llvm.trap()");
        self.instruction("unreachable");
        self.begin(&success);
    }

    fn slot(&mut self, ty: &Type) -> String {
        let slot = self.fresh();
        self.allocas
            .push(format!("{slot} = alloca {}, align 16", self.ty(ty)));
        slot
    }

    fn bind_local(&mut self, local: &Local, value: &str) {
        let slot = self.slot(&local.ty);
        self.instruction(format!("store {} {value}, ptr {slot}", self.ty(&local.ty)));
        self.locals.insert(local.id, slot.clone());
        if local.ty.needs_drop(&self.module.records) {
            self.scopes
                .last_mut()
                .unwrap()
                .push((slot, local.ty.clone()));
        }
    }

    fn bind(&mut self, bindings: &[(Local, TypedExpr)]) {
        for (local, expression) in bindings {
            let value = self.expression(expression);
            self.bind_local(local, &value);
        }
    }

    fn is_self(&self, callee: &TypedExpr) -> bool {
        matches!(callee.kind, TypedExprKind::Function(FunctionRef::User(id)) if id == self.function_id)
            && !self
                .function
                .signature
                .parameters
                .iter()
                .any(Type::contains_reference)
    }

    fn tail(&mut self, expression: &TypedExpr) {
        match &expression.kind {
            TypedExprKind::Block { bindings, result } => {
                self.scopes.push(Vec::new());
                self.bind(bindings);
                self.tail(result);
                self.scopes.pop();
            }
            TypedExprKind::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.expression(condition);
                let yes = self.label();
                let no = self.label();
                self.branch(&condition, &yes, &no);
                self.begin(&yes);
                self.tail(then_branch);
                self.begin(&no);
                self.tail(else_branch);
            }
            TypedExprKind::Call(callee, arguments) if self.is_self(callee) => {
                let values = arguments
                    .iter()
                    .map(|argument| self.expression(argument))
                    .collect();
                self.drop_all();
                self.back_edges.push((self.block.clone(), values));
                self.jump("loop");
            }
            TypedExprKind::Binary(BinaryOp::Pipe, argument, callee) if self.is_self(callee) => {
                let value = self.expression(argument);
                self.drop_all();
                self.back_edges.push((self.block.clone(), vec![value]));
                self.jump("loop");
            }
            _ => {
                let value = self.expression(expression);
                self.drop_all();
                self.instruction(format!("ret {} {value}", self.ty(&expression.ty)));
            }
        }
    }

    fn expression(&mut self, expression: &TypedExpr) -> String {
        self.expression_mode(expression, true)
    }

    fn expression_mode(&mut self, expression: &TypedExpr, take: bool) -> String {
        if Self::is_place(expression) {
            let slot = self.place(expression);
            let value = self.value(format!("load {}, ptr {slot}", self.ty(&expression.ty)));
            if take && expression.ty.needs_drop(&self.module.records) {
                self.instruction(format!(
                    "store {} zeroinitializer, ptr {slot}",
                    self.ty(&expression.ty)
                ));
            }
            return value;
        }
        match &expression.kind {
            TypedExprKind::Int(value) => value.to_string(),
            TypedExprKind::Float(value) => value.clone(),
            TypedExprKind::Bool(value) => if *value { "1" } else { "0" }.into(),
            TypedExprKind::Unit => "0".into(),
            TypedExprKind::String(text) => {
                let name = format!("@tz.literal.{}", self.globals.len());
                let escaped = text
                    .bytes()
                    .map(|byte| format!("\\{byte:02X}"))
                    .collect::<String>();
                self.globals.push(format!(
                    "{name} = private unnamed_addr constant [{} x i8] c\"{escaped}\"",
                    text.len()
                ));
                self.value(format!(
                    "call %tz.string @tz.string.new(ptr {name}, i64 {})",
                    text.len()
                ))
            }
            TypedExprKind::Local(_) | TypedExprKind::Dereference(_) => {
                unreachable!("places handled above")
            }
            TypedExprKind::Borrow(value, _) => self.place(value),
            TypedExprKind::Assign(place, value) => {
                let value = self.expression(value);
                let slot = self.place(place);
                self.drop_slot(&slot, &place.ty);
                self.instruction(format!("store {} {value}, ptr {slot}", self.ty(&place.ty)));
                "0".into()
            }
            TypedExprKind::Cast(value) => self.cast(value, &expression.ty),
            TypedExprKind::Function(reference) => match reference {
                FunctionRef::User(id) => {
                    format!("@tz.fn.{}", self.module.functions[*id].qualified_name())
                }
                FunctionRef::Builtin(builtin) => {
                    self.builtins.insert(*builtin);
                    format!("@tz.builtin.{}", builtin.name())
                }
            },
            TypedExprKind::Unary(operator, operand) => {
                let value = self.expression(operand);
                let ty = self.ty(&operand.ty);
                self.value(match operator {
                    UnaryOp::Negate if matches!(operand.ty, Type::Binary(32 | 64)) => {
                        format!("fneg {ty} {value}")
                    }
                    UnaryOp::Negate if operand.ty.is_float() => {
                        let bits = match operand.ty {
                            Type::Binary(bits) | Type::Decimal(bits) => bits,
                            _ => unreachable!(),
                        };
                        format!("xor {ty} {value}, {}", 1u128 << (bits - 1))
                    }
                    UnaryOp::Negate => format!("sub {ty} 0, {value}"),
                    UnaryOp::Not => format!("xor i1 {value}, 1"),
                    UnaryOp::BitNot => format!("xor {ty} {value}, -1"),
                })
            }
            TypedExprKind::Binary(BinaryOp::And | BinaryOp::Or, left, right) => {
                let TypedExprKind::Binary(operator, _, _) = expression.kind else {
                    unreachable!()
                };
                self.short_circuit(operator, left, right)
            }
            TypedExprKind::Binary(BinaryOp::Pipe, argument, callee) => {
                let value = self.expression(argument);
                let function = self.expression(callee);
                self.value(format!(
                    "call {} {function}({} {value})",
                    self.ty(&expression.ty),
                    self.ty(&argument.ty)
                ))
            }
            TypedExprKind::Binary(operator, left, right) => self.binary(*operator, left, right),
            TypedExprKind::Call(callee, arguments) => {
                let callee = self.expression(callee);
                let arguments = arguments
                    .iter()
                    .map(|argument| {
                        let value = self.expression(argument);
                        format!("{} {value}", self.ty(&argument.ty))
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                self.value(format!(
                    "call {} {callee}({arguments})",
                    self.ty(&expression.ty)
                ))
            }
            TypedExprKind::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.expression(condition);
                let yes = self.label();
                let no = self.label();
                let merge = self.label();
                self.branch(&condition, &yes, &no);
                self.begin(&yes);
                let then_value = self.expression(then_branch);
                let then_end = self.block.clone();
                self.jump(&merge);
                self.begin(&no);
                let else_value = self.expression(else_branch);
                let else_end = self.block.clone();
                self.jump(&merge);
                self.begin(&merge);
                self.value(format!(
                    "phi {} [ {then_value}, %{then_end} ], [ {else_value}, %{else_end} ]",
                    self.ty(&expression.ty),
                ))
            }
            TypedExprKind::Block { bindings, result } => {
                self.scopes.push(Vec::new());
                self.bind(bindings);
                let value = self.expression(result);
                let scope = self.scopes.pop().unwrap();
                self.drop_scope(&scope);
                value
            }
            TypedExprKind::Record(fields) => {
                let mut record = "zeroinitializer".into();
                for (index, field) in fields {
                    let value = self.expression(field);
                    record = self.value(format!(
                        "insertvalue {} {record}, {} {value}, {index}",
                        self.ty(&expression.ty),
                        self.ty(&field.ty)
                    ));
                }
                record
            }
            TypedExprKind::Array(elements) => {
                let mut array = "zeroinitializer".into();
                for (index, element) in elements.iter().enumerate() {
                    let value = self.expression(element);
                    array = self.value(format!(
                        "insertvalue {} {array}, {} {value}, {index}",
                        self.ty(&expression.ty),
                        self.ty(&element.ty)
                    ));
                }
                array
            }
            TypedExprKind::Field(record, index) => {
                let value = self.expression(record);
                let field = self.value(format!(
                    "extractvalue {} {value}, {index}",
                    self.ty(&record.ty)
                ));
                if record.ty.needs_drop(&self.module.records) {
                    let remainder = self.value(format!(
                        "insertvalue {} {value}, {} zeroinitializer, {index}",
                        self.ty(&record.ty),
                        self.ty(&expression.ty)
                    ));
                    self.drop_value(&record.ty, &remainder);
                }
                field
            }
            TypedExprKind::Index(string, index) if string.ty == Type::String => {
                let value = self.expression_mode(string, false);
                let index = self.expression(index);
                let data = self.value(format!("extractvalue %tz.string {value}, 0"));
                let length = self.value(format!("extractvalue %tz.string {value}, 1"));
                let valid = self.value(format!("icmp ult i64 {index}, {length}"));
                self.guard(&valid);
                let pointer = self.value(format!(
                    "getelementptr inbounds i8, ptr {data}, i64 {index}"
                ));
                let byte = self.value(format!("load i8, ptr {pointer}"));
                self.drop_temporary(string, &value);
                byte
            }
            TypedExprKind::Index(array, index) => {
                let value = self.expression(array);
                let index = self.expression(index);
                let Type::Array(element, length) = &array.ty else {
                    unreachable!()
                };
                let valid = self.value(format!("icmp ult i64 {index}, {length}"));
                self.guard(&valid);
                let slot = self.fresh();
                let array_type = self.ty(&array.ty);
                // All storage is in entry, so tail-recursive loops never grow the stack.
                self.allocas
                    .push(format!("{slot} = alloca {array_type}, align 8"));
                self.instruction(format!("store {array_type} {value}, ptr {slot}"));
                let pointer = self.value(format!(
                    "getelementptr inbounds {array_type}, ptr {slot}, i32 0, i64 {index}"
                ));
                self.value(format!("load {}, ptr {pointer}", self.ty(element)))
            }
            TypedExprKind::Length(array, length) => {
                let value = self.expression_mode(array, false);
                self.drop_temporary(array, &value);
                length.to_string()
            }
            TypedExprKind::StringLength(string) => {
                let value = self.expression_mode(string, false);
                let length = self.value(format!("extractvalue %tz.string {value}, 1"));
                self.drop_temporary(string, &value);
                length
            }
        }
    }

    fn is_place(expression: &TypedExpr) -> bool {
        match &expression.kind {
            TypedExprKind::Local(_) | TypedExprKind::Dereference(_) => true,
            TypedExprKind::Field(value, _) => Self::is_place(value),
            TypedExprKind::Index(value, _) => {
                matches!(value.ty, Type::Array(..)) && Self::is_place(value)
            }
            _ => false,
        }
    }

    fn place(&mut self, expression: &TypedExpr) -> String {
        match &expression.kind {
            TypedExprKind::Local(id) => self.locals[id].clone(),
            TypedExprKind::Dereference(value) => self.expression_mode(value, false),
            TypedExprKind::Field(value, index) => {
                let slot = self.place(value);
                self.value(format!(
                    "getelementptr inbounds {}, ptr {slot}, i32 0, i32 {index}",
                    self.ty(&value.ty)
                ))
            }
            TypedExprKind::Index(value, index) => {
                let slot = self.place(value);
                let index = self.expression(index);
                let Type::Array(_, length) = value.ty else {
                    unreachable!()
                };
                let valid = self.value(format!("icmp ult i64 {index}, {length}"));
                self.guard(&valid);
                self.value(format!(
                    "getelementptr inbounds {}, ptr {slot}, i32 0, i64 {index}",
                    self.ty(&value.ty)
                ))
            }
            _ => unreachable!("borrow checker requires an addressable place"),
        }
    }

    fn drop_value(&mut self, ty: &Type, value: &str) {
        match ty {
            Type::String => {
                let pointer = self.value(format!("extractvalue %tz.string {value}, 0"));
                self.instruction(format!("call void @tz.free(ptr {pointer})"));
            }
            Type::Record(id) => {
                for (index, (_, field)) in self.module.records[*id].fields.iter().enumerate() {
                    if field.needs_drop(&self.module.records) {
                        let extracted =
                            self.value(format!("extractvalue {} {value}, {index}", self.ty(ty)));
                        self.drop_value(field, &extracted);
                    }
                }
            }
            Type::Array(element, length) if element.needs_drop(&self.module.records) => {
                for index in 0..*length {
                    let extracted =
                        self.value(format!("extractvalue {} {value}, {index}", self.ty(ty)));
                    self.drop_value(element, &extracted);
                }
            }
            _ => {}
        }
    }

    fn drop_slot(&mut self, slot: &str, ty: &Type) {
        if ty.needs_drop(&self.module.records) {
            let value = self.value(format!("load {}, ptr {slot}", self.ty(ty)));
            self.drop_value(ty, &value);
            self.instruction(format!("store {} zeroinitializer, ptr {slot}", self.ty(ty)));
        }
    }

    fn drop_temporary(&mut self, expression: &TypedExpr, value: &str) {
        if !Self::is_place(expression) {
            self.drop_value(&expression.ty, value);
        }
    }

    fn drop_scope(&mut self, scope: &[(String, Type)]) {
        for (slot, ty) in scope.iter().rev() {
            self.drop_slot(slot, ty);
        }
    }

    fn drop_all(&mut self) {
        for scope in self.scopes.clone().iter().rev() {
            self.drop_scope(scope);
        }
    }

    fn spill(&mut self, ty: &Type, value: &str) -> String {
        let slot = self.slot(ty);
        self.instruction(format!("store {} {value}, ptr {slot}", self.ty(ty)));
        slot
    }

    fn cast(&mut self, expression: &TypedExpr, to: &Type) -> String {
        let value = self.expression(expression);
        if expression.ty == *to {
            return value;
        }
        if let (Type::Integer(from, signed), Type::Integer(bits, _)) = (&expression.ty, to) {
            if from == bits {
                return value;
            }
            let instruction = if bits < from {
                "trunc"
            } else if *signed {
                "sext"
            } else {
                "zext"
            };
            return self.value(format!(
                "{instruction} {} {value} to {}",
                self.ty(&expression.ty),
                self.ty(to)
            ));
        }
        let input = self.spill(&expression.ty, &value);
        let output = self.slot(to);
        self.instruction(format!(
            "call void @tz_soft_cast(ptr {output}, ptr {input}, i32 {}, i32 {})",
            numeric_kind(&expression.ty),
            numeric_kind(to)
        ));
        self.value(format!("load {}, ptr {output}", self.ty(to)))
    }

    fn short_circuit(&mut self, operator: BinaryOp, left: &TypedExpr, right: &TypedExpr) -> String {
        let left = self.expression(left);
        let left_end = self.block.clone();
        let evaluate_right = self.label();
        let merge = self.label();
        let shortcut = if operator == BinaryOp::And {
            self.branch(&left, &evaluate_right, &merge);
            "0"
        } else {
            self.branch(&left, &merge, &evaluate_right);
            "1"
        };
        self.begin(&evaluate_right);
        let right = self.expression(right);
        let right_end = self.block.clone();
        self.jump(&merge);
        self.begin(&merge);
        self.value(format!(
            "phi i1 [ {shortcut}, %{left_end} ], [ {right}, %{right_end} ]"
        ))
    }

    fn binary(&mut self, operator: BinaryOp, left: &TypedExpr, right: &TypedExpr) -> String {
        use BinaryOp::*;
        if left.ty == Type::String {
            let take = operator == Add;
            let lhs = self.expression_mode(left, take);
            let rhs = self.expression_mode(right, take);
            let result = if take {
                self.value(format!(
                    "call %tz.string @tz.string.concat(%tz.string {lhs}, %tz.string {rhs})"
                ))
            } else {
                self.value(format!(
                    "call i1 @tz.string.equal(%tz.string {lhs}, %tz.string {rhs})"
                ))
            };
            if take {
                self.drop_value(&left.ty, &lhs);
                self.drop_value(&right.ty, &rhs);
            } else {
                self.drop_temporary(left, &lhs);
                self.drop_temporary(right, &rhs);
            }
            return if operator == NotEqual {
                self.value(format!("xor i1 {result}, 1"))
            } else {
                result
            };
        }
        let lhs = self.expression(left);
        let mut rhs = self.expression(right);
        let ty = self.ty(&left.ty);
        if matches!(left.ty, Type::Decimal(_) | Type::Binary(16 | 128)) {
            let a = self.spill(&left.ty, &lhs);
            let b = self.spill(&right.ty, &rhs);
            let kind = numeric_kind(&left.ty);
            if matches!(operator, Add | Subtract | Multiply | Divide) {
                let op = match operator {
                    Add => 0,
                    Subtract => 1,
                    Multiply => 2,
                    _ => 3,
                };
                let output = self.slot(&left.ty);
                self.instruction(format!(
                    "call void @tz_soft_op(ptr {output}, ptr {a}, ptr {b}, i32 {kind}, i32 {op})"
                ));
                return self.value(format!("load {ty}, ptr {output}"));
            }
            let order = self.value(format!(
                "call i32 @tz_soft_cmp(ptr {a}, ptr {b}, i32 {kind})"
            ));
            let (predicate, value) = match operator {
                Equal => ("eq", 0),
                NotEqual => ("ne", 0),
                Less => ("slt", 0),
                LessEqual => ("sle", 0),
                Greater => ("eq", 1),
                GreaterEqual => ("ule", 1),
                _ => unreachable!("software float operator checked"),
            };
            return self.value(format!("icmp {predicate} i32 {order}, {value}"));
        }
        if matches!(operator, Divide | Remainder) && left.ty.is_integer() {
            let mut valid = self.value(format!("icmp ne {ty} {rhs}, 0"));
            if let Type::Integer(bits, true) = left.ty {
                let minimum = self.value(format!("icmp eq {ty} {lhs}, {}", 1u128 << (bits - 1)));
                let negative_one = self.value(format!("icmp eq {ty} {rhs}, -1"));
                let overflow = self.value(format!("and i1 {minimum}, {negative_one}"));
                let no_overflow = self.value(format!("xor i1 {overflow}, 1"));
                valid = self.value(format!("and i1 {valid}, {no_overflow}"));
            }
            self.guard(&valid);
        }
        if matches!(operator, ShiftLeft | ShiftRight | ShiftRightUnsigned) {
            let Type::Integer(bits, _) = left.ty else {
                unreachable!()
            };
            rhs = self.value(format!("and {ty} {rhs}, {}", bits - 1));
        }
        let unsigned = matches!(left.ty, Type::Integer(_, false));
        let instruction = if left.ty.is_float() {
            match operator {
                Add => "fadd",
                Subtract => "fsub",
                Multiply => "fmul",
                Divide => "fdiv",
                Equal => "fcmp oeq",
                NotEqual => "fcmp une",
                Less => "fcmp olt",
                LessEqual => "fcmp ole",
                Greater => "fcmp ogt",
                GreaterEqual => "fcmp oge",
                _ => unreachable!("float operator checked"),
            }
        } else {
            match operator {
                Add => "add",
                Subtract => "sub",
                Multiply => "mul",
                Divide => {
                    if unsigned {
                        "udiv"
                    } else {
                        "sdiv"
                    }
                }
                Remainder => {
                    if unsigned {
                        "urem"
                    } else {
                        "srem"
                    }
                }
                Equal => "icmp eq",
                NotEqual => "icmp ne",
                Less => {
                    if unsigned {
                        "icmp ult"
                    } else {
                        "icmp slt"
                    }
                }
                LessEqual => {
                    if unsigned {
                        "icmp ule"
                    } else {
                        "icmp sle"
                    }
                }
                Greater => {
                    if unsigned {
                        "icmp ugt"
                    } else {
                        "icmp sgt"
                    }
                }
                GreaterEqual => {
                    if unsigned {
                        "icmp uge"
                    } else {
                        "icmp sge"
                    }
                }
                BitAnd => "and",
                BitOr => "or",
                BitXor => "xor",
                ShiftLeft => "shl",
                ShiftRight => {
                    if unsigned {
                        "lshr"
                    } else {
                        "ashr"
                    }
                }
                ShiftRightUnsigned => "lshr",
                _ => unreachable!("operator checked or handled separately"),
            }
        };
        self.value(format!("{instruction} {} {lhs}, {rhs}", self.ty(&left.ty)))
    }
}

fn numeric_kind(ty: &Type) -> u16 {
    match ty {
        Type::Binary(16) => 0,
        Type::Binary(32) => 1,
        Type::Binary(64) => 2,
        Type::Binary(128) => 3,
        Type::Decimal(32) => 4,
        Type::Decimal(64) => 5,
        Type::Decimal(128) => 6,
        Type::Integer(bits, signed) => 16 + (bits / 8).ilog2() as u16 + if *signed { 0 } else { 8 },
        _ => unreachable!("numeric type checked"),
    }
}

fn export_wrapper(function: &CheckedFunction, module: &CheckedModule) -> String {
    let parameters = function
        .signature
        .parameters
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("{} %arg{index}", abi_type(ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let result = &function.signature.result;
    let mut output = format!(
        "define {} @tz_{}({parameters}) nounwind {{\nentry:\n",
        abi_type(result),
        function.name
    );
    let mut arguments = Vec::new();
    for (index, ty) in function.signature.parameters.iter().enumerate() {
        if *ty == Type::Bool {
            let _ = writeln!(output, "  %b{index} = icmp ne i32 %arg{index}, 0");
            arguments.push(format!("i1 %b{index}"));
        } else if let Type::Integer(bits @ (8 | 16), _) = ty {
            let _ = writeln!(output, "  %n{index} = trunc i32 %arg{index} to i{bits}");
            arguments.push(format!("i{bits} %n{index}"));
        } else {
            arguments.push(format!("{} %arg{index}", llvm_type(ty, module)));
        }
    }
    let _ = writeln!(
        output,
        "  %result = call {} @tz.fn.{}({})",
        llvm_type(result, module),
        function.qualified_name(),
        arguments.join(", ")
    );
    match result {
        Type::Bool => output.push_str("  %bool = zext i1 %result to i32\n  ret i32 %bool\n"),
        Type::Unit => output.push_str("  ret void\n"),
        Type::Integer(bits @ (8 | 16), signed) => {
            let _ = writeln!(
                output,
                "  %wide = {} i{bits} %result to i32\n  ret i32 %wide",
                if *signed { "sext" } else { "zext" }
            );
        }
        _ => {
            let _ = writeln!(output, "  ret {} %result", llvm_type(result, module));
        }
    }
    output.push_str("}\n\n");
    output
}

fn emit_builtin(builtin: Builtin) -> String {
    let name = builtin.name();
    match builtin {
        Builtin::ToFloat => format!(
            "define internal double @tz.builtin.{name}(i64 %x) nounwind {{\n\
             entry:\n  %r = sitofp i64 %x to double\n  ret double %r\n}}\n\n"
        ),
        Builtin::ToInt => format!(
            "declare i64 @llvm.fptosi.sat.i64.f64(double)\n\
             define internal i64 @tz.builtin.{name}(double %x) nounwind {{\n\
             entry:\n  %r = call i64 @llvm.fptosi.sat.i64.f64(double %x)\n  ret i64 %r\n}}\n\n"
        ),
        Builtin::Assert => format!(
            "define internal i8 @tz.builtin.{name}(i1 %x) nounwind {{\n\
             entry:\n  br i1 %x, label %ok, label %fail\n\
             fail:\n  call void @llvm.trap()\n  unreachable\n\
             ok:\n  ret i8 0\n}}\n\n"
        ),
        Builtin::CloneString => format!(
            "define internal %tz.string @tz.builtin.{name}(ptr %x) nounwind {{\n\
             entry:\n  %s = load %tz.string, ptr %x\n\
             %p = extractvalue %tz.string %s, 0\n  %n = extractvalue %tz.string %s, 1\n\
             %r = call %tz.string @tz.string.new(ptr %p, i64 %n)\n  ret %tz.string %r\n}}\n\n"
        ),
        _ => {
            let intrinsic = match builtin {
                Builtin::Sqrt => "sqrt",
                Builtin::Floor => "floor",
                Builtin::Ceil => "ceil",
                Builtin::Abs => "fabs",
                _ => unreachable!(),
            };
            format!(
                "declare double @llvm.{intrinsic}.f64(double)\n\
                 define internal double @tz.builtin.{name}(double %x) nounwind {{\n\
                 entry:\n  %r = call double @llvm.{intrinsic}.f64(double %x)\n\
                 ret double %r\n}}\n\n"
            )
        }
    }
}

fn console_main(module: &CheckedModule) -> String {
    let main = &module.functions[module.entry.unwrap()];
    let ty = &main.signature.result;
    let buffered = matches!(
        ty,
        Type::String | Type::Integer(128, _) | Type::Binary(16 | 128) | Type::Decimal(_)
    );
    let mut output = match ty {
        Type::Integer(8 | 16 | 32 | 64, signed) => format!(
            "@tz.fmt = private unnamed_addr constant [6 x i8] c\"%ll{}\\0A\\00\"\n",
            if *signed { "d" } else { "u" }
        ),
        Type::Binary(64) => {
            "@tz.fmt = private unnamed_addr constant [7 x i8] c\"%.17g\\0A\\00\"\n".into()
        }
        Type::Binary(32) => {
            "@tz.fmt = private unnamed_addr constant [6 x i8] c\"%.9g\\0A\\00\"\n".into()
        }
        Type::Bool => String::from(
            "@tz.fmt = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n\
             @tz.true = private unnamed_addr constant [5 x i8] c\"true\\00\"\n\
             @tz.false = private unnamed_addr constant [6 x i8] c\"false\\00\"\n",
        ),
        _ => String::new(),
    };
    if buffered {
        output.push_str(include_str!("runtime/console.ll"));
    } else if *ty != Type::Unit {
        output.push_str("declare i32 @printf(ptr, ...)\n\n");
    }
    let _ = writeln!(
        output,
        "define i32 @main() {{\nentry:\n  %result = call {} @tz.fn.{}()",
        llvm_type(ty, module),
        main.qualified_name()
    );
    match ty {
        Type::Integer(bits @ (8 | 16 | 32 | 64), signed) => {
            let value = if *bits < 64 {
                let _ = writeln!(
                    output,
                    "  %wide = {} i{bits} %result to i64",
                    if *signed { "sext" } else { "zext" }
                );
                "%wide"
            } else {
                "%result"
            };
            let _ = writeln!(
                output,
                "  %printed = call i32 (ptr, ...) @printf(ptr @tz.fmt, i64 {value})"
            );
        }
        Type::Binary(32 | 64) => {
            let value = if *ty == Type::Binary(32) {
                output.push_str("  %wide = fpext float %result to double\n");
                "%wide"
            } else {
                "%result"
            };
            let _ = writeln!(
                output,
                "  %printed = call i32 (ptr, ...) @printf(ptr @tz.fmt, double {value})"
            );
        }
        Type::Bool => {
            output.push_str(
                "  %text = select i1 %result, ptr @tz.true, ptr @tz.false\n\
                   %printed = call i32 (ptr, ...) @printf(ptr @tz.fmt, ptr %text)\n",
            );
        }
        Type::String => {
            output.push_str("  %data = extractvalue %tz.string %result, 0\n  %length = extractvalue %tz.string %result, 1\n  %printed = call i32 @tz.console.write(ptr %data, i64 %length)\n  call void @tz.free(ptr %data)\n");
        }
        Type::Unit => {}
        _ if ty.is_numeric() => {
            let _ = writeln!(
                output,
                "  %slot = alloca {}, align 16\n  %buffer = alloca [64 x i8], align 16\n  store {} %result, ptr %slot\n  %count = call i32 @tz_soft_format(ptr %buffer, ptr %slot, i32 {})\n  %length = zext i32 %count to i64\n  %printed = call i32 @tz.console.write(ptr %buffer, i64 %length)",
                llvm_type(ty, module),
                llvm_type(ty, module),
                numeric_kind(ty)
            );
        }
        _ => unreachable!("main validated"),
    }
    if *ty == Type::Unit {
        output.push_str("  ret i32 0\n");
    } else {
        output.push_str(
            "  %failed = icmp slt i32 %printed, 0\n  %exit = zext i1 %failed to i32\n  ret i32 %exit\n",
        );
    }
    output.push_str("}\n");
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyze;

    #[test]
    fn emits_explicit_tail_loop_and_checked_arithmetic() {
        let module = analyze(
            "fn sum(n: i64, acc: i64) -> i64 {
                if n == 0 { acc / 2 } else { sum(n - 1, acc + n) }
             }
             export fn main() -> i64 { sum(100, 0) }",
        )
        .unwrap();
        let ir = emit(&module, Entry::Console).unwrap();
        assert_eq!(ir.matches("call i64 @tz.fn.Main.sum").count(), 1);
        assert!(ir.contains("phi i64"));
        assert!(ir.contains("call void @llvm.trap()"));
        assert!(ir.contains("define i64 @tz_main()"));
        assert!(ir.contains("define i32 @main()"));
        assert!(!ir.contains(" nsw "));
        assert_eq!(ir, emit(&module, Entry::Console).unwrap());
    }

    #[test]
    fn puts_array_storage_before_the_tail_loop() {
        let module = analyze(
            "fn f(n: i64, a: [i64; 2]) -> i64 {
                let first = a[n & 1];
                if n == 0 { first } else { f(n - 1, [first, 2]) }
             }",
        )
        .unwrap();
        let ir = emit(&module, Entry::Library).unwrap();
        assert!(ir.find("alloca").unwrap() < ir.find("br label %loop").unwrap());
        assert_eq!(ir.matches("call i64 @tz.fn.Main.f").count(), 0);
    }

    #[test]
    fn emits_portable_bool_abi_and_c_header() {
        let module = analyze("export fn not(x: bool) -> bool { !x }").unwrap();
        let ir = emit(&module, Entry::Library).unwrap();
        assert!(ir.contains("define i32 @tz_not(i32 %arg0)"));
        assert!(ir.contains("icmp ne i32 %arg0, 0"));
        assert!(header(&module).contains("int32_t tz_not(int32_t arg0);"));
        assert!(emit(&module, Entry::Console).is_err());
    }
}
