use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::check::{
    Builtin, CheckedFunction, CheckedModule, FunctionRef, Local, Type, TypedExpr, TypedExprKind,
};
use crate::diagnostic::{Diagnostic, Span};
use crate::syntax::{BinaryOp, UnaryOp};

#[path = "call_specialization.rs"]
mod call_specialization;
#[path = "llvm_control.rs"]
mod control;
use call_specialization::{ClosureTarget, Specialization, Specializations};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Entry {
    Library,
    Console,
}

pub fn emit(module: &CheckedModule, entry: Entry) -> Result<String, Diagnostic> {
    emit_target(module, entry, false)
}

pub fn emit_target(module: &CheckedModule, entry: Entry, wasm: bool) -> Result<String, Diagnostic> {
    if entry == Entry::Console {
        validate_main(module)?;
    }
    let mut output = String::from(
        "; Tsuzuri - deterministic LLVM IR\nsource_filename = \"tsuzuri\"\n%tz.string = type { ptr, i64 }\n%tz.array = type { ptr, i64 }\n%tz.list = type { ptr, i64 }\n%tz.closure = type { ptr, ptr, ptr, ptr }\n",
    );
    for record in &module.records {
        let _ = writeln!(
            output,
            "%tz.record.{} = type {{ {} }}",
            record.name,
            record
                .fields
                .iter()
                .map(|(_, ty)| llvm_type(ty, module))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    output.push_str("\ndeclare void @llvm.trap()\n\n");
    let mut builtins = BTreeSet::new();
    let mut intrinsics = BTreeSet::new();
    let mut globals = Globals::default();
    let mut specializations = Specializations::new(module);
    for (id, function) in module.functions.iter().enumerate() {
        let emitter = FunctionEmitter::new(
            module,
            function,
            id,
            &mut builtins,
            &mut intrinsics,
            &mut globals,
            &mut specializations,
        );
        output.push_str(&emitter.emit());
        output.push_str(&closure_wrappers(
            module,
            function,
            id,
            &mut builtins,
            &mut intrinsics,
            &mut globals,
            &mut specializations,
        ));
        if function.exported {
            output.push_str(&export_wrapper(function, module));
        }
    }
    let mut next = 0;
    while let Some(key) = specializations.requests.get(next).cloned() {
        let emitter = FunctionEmitter::new(
            module,
            &module.functions[key.function],
            key.function,
            &mut builtins,
            &mut intrinsics,
            &mut globals,
            &mut specializations,
        )
        .specialized(next, &key);
        output.push_str(&emitter.emit());
        next += 1;
    }
    for builtin in builtins {
        output.push_str(&emit_builtin(builtin, &mut intrinsics));
    }
    for intrinsic in intrinsics {
        let _ = writeln!(output, "{intrinsic}");
    }
    if entry == Entry::Console {
        output.push_str(&console_main(module));
    }
    for global in globals.definitions {
        output.push_str(&global);
        output.push('\n');
    }
    if output.contains("@tsuzuri_task_parallel(") {
        output.push_str(if wasm {
            include_str!("runtime/task-wasm.ll")
        } else {
            "declare void @tsuzuri_task_parallel(ptr, ptr, i64)\n"
        });
    }
    if output.contains("@tz_soft_") {
        output = output.replace("declare void @llvm.trap()\n", "");
        output.push_str(include_str!("runtime/numeric.ll"));
    }
    if output.contains("@tz.closure.") {
        output.push_str(include_str!("runtime/closure.ll"));
    }
    if output.contains("@tz.string.") || output.contains("@tz.free") || output.contains("@tz.alloc")
    {
        output.push_str(include_str!("runtime/string.ll"));
        output.push_str(if wasm {
            include_str!("runtime/heap-wasm.ll")
        } else {
            include_str!("runtime/heap-native.ll")
        });
    }
    Ok(output)
}

pub fn header(module: &CheckedModule) -> String {
    let mut output = String::from(
        "/* Generated by Tsuzuri. bool uses int32_t. Narrow integers use normalized 32-bit ABI values. */\n\
         #pragma once\n\
         #include <stdint.h>\n\n\
         #ifdef __cplusplus\n\
         extern \"C\" {\n\
         #endif\n\n",
    );
    for function in &module.functions {
        if !function.exported {
            continue;
        }
        let parameters = if function.signature.parameters.is_empty() {
            "void".into()
        } else {
            function
                .signature
                .parameters
                .iter()
                .enumerate()
                .map(|(id, ty)| format!("{} arg{id}", c_type(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            output,
            "{} tz_{}({parameters});",
            c_type(&function.signature.result),
            function.name
        );
    }
    output.push_str("\n#ifdef __cplusplus\n}\n#endif\n");
    output
}

struct Globals {
    definitions: Vec<String>,
    next_metadata: usize,
}

impl Default for Globals {
    fn default() -> Self {
        static FIRST_METADATA: std::sync::OnceLock<usize> = std::sync::OnceLock::new();
        let next_metadata = *FIRST_METADATA.get_or_init(|| {
            include_str!("runtime/numeric.ll")
                .lines()
                .filter_map(|line| {
                    line.strip_prefix('!')?
                        .split_once('=')?
                        .0
                        .trim()
                        .parse::<usize>()
                        .ok()
                })
                .max()
                .map_or(0, |id| id + 1)
        });
        Self {
            definitions: Vec::new(),
            next_metadata,
        }
    }
}

fn environment_type(function: &CheckedFunction, count: usize, module: &CheckedModule) -> String {
    format!(
        "{{ {} }}",
        function.signature.parameters[..count]
            .iter()
            .map(|ty| llvm_type(ty, module))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn closure_wrappers(
    module: &CheckedModule,
    function: &CheckedFunction,
    id: usize,
    builtins: &mut BTreeSet<Builtin>,
    intrinsics: &mut BTreeSet<String>,
    globals: &mut Globals,
    specializations: &mut Specializations,
) -> String {
    let mut output = String::new();
    let name = function.qualified_name();
    let arity = function.parameters.len();
    for count in function.capture_count..arity.max(function.capture_count + 1) {
        let environment = environment_type(function, count, module);
        if count != 0 {
            if !function.is_task
                && function.signature.parameters[..count]
                    .iter()
                    .all(|ty| ty.can_capture(&module.records))
            {
                let mut clone = FunctionEmitter::new(
                    module,
                    function,
                    id,
                    builtins,
                    intrinsics,
                    globals,
                    specializations,
                );
                let allocation = clone.value(format!("call ptr @tz.alloc(i64 ptrtoint (ptr getelementptr ({environment}, ptr null, i32 1) to i64))"));
                for (index, ty) in function.signature.parameters[..count].iter().enumerate() {
                    let pointer = clone.value(format!(
                        "getelementptr inbounds {environment}, ptr %env, i32 0, i32 {index}"
                    ));
                    let value = clone.value(format!("load {}, ptr {pointer}", clone.ty(ty)));
                    let value = clone.clone_value(ty, &value);
                    let target = clone.value(format!(
                        "getelementptr inbounds {environment}, ptr {allocation}, i32 0, i32 {index}"
                    ));
                    clone.instruction(format!("store {} {value}, ptr {target}", clone.ty(ty)));
                }
                clone.instruction(format!("ret ptr {allocation}"));
                output.push_str(
                    &clone.auxiliary(&format!("ptr @tz.env.clone.{name}.{count}(ptr %env)")),
                );
            }

            let mut drop = FunctionEmitter::new(
                module,
                function,
                id,
                builtins,
                intrinsics,
                globals,
                specializations,
            );
            for (index, ty) in function.signature.parameters[..count].iter().enumerate() {
                if ty.needs_drop(&module.records) {
                    let pointer = drop.value(format!(
                        "getelementptr inbounds {environment}, ptr %env, i32 0, i32 {index}"
                    ));
                    let value = drop.value(format!("load {}, ptr {pointer}", drop.ty(ty)));
                    drop.drop_value(ty, &value);
                }
            }
            drop.instruction("call void @tz.free(ptr %env)");
            drop.instruction("ret void");
            output
                .push_str(&drop.auxiliary(&format!("void @tz.env.drop.{name}.{count}(ptr %env)")));
        }
        let mut apply = FunctionEmitter::new(
            module,
            function,
            id,
            builtins,
            intrinsics,
            globals,
            specializations,
        );
        let mut values = Vec::new();
        for (index, ty) in function.signature.parameters[..count].iter().enumerate() {
            let pointer = apply.value(format!(
                "getelementptr inbounds {environment}, ptr %env, i32 0, i32 {index}"
            ));
            values.push(apply.value(format!("load {}, ptr {pointer}", apply.ty(ty))));
        }
        if count < arity {
            values.push("%argument".into());
        }
        if count != 0 {
            apply.instruction("call void @tz.free(ptr %env)");
        }
        let (value, result) = if values.len() == arity {
            let arguments = values
                .iter()
                .zip(&function.signature.parameters)
                .map(|(value, ty)| format!("{} {value}", apply.ty(ty)))
                .collect::<Vec<_>>()
                .join(", ");
            let value = apply.value(format!(
                "call {} @tz.fn.{name}({arguments})",
                apply.ty(&function.signature.result)
            ));
            (value, function.signature.result.clone())
        } else {
            let value = apply.make_closure(id, &values);
            let result = Type::function(
                function.signature.parameters[values.len()..].to_vec(),
                function.signature.result.clone(),
            );
            (value, result)
        };
        apply.instruction(format!("ret {} {value}", apply.ty(&result)));
        let argument = if count < arity {
            format!(
                ", {} %argument",
                apply.ty(&function.signature.parameters[count])
            )
        } else {
            String::new()
        };
        output.push_str(&apply.auxiliary(&format!(
            "{} @tz.apply.{name}.{count}(ptr %env{argument})",
            llvm_type(&result, module)
        )));
    }
    output
}

fn c_type(ty: &Type) -> String {
    match ty {
        Type::Integer(bits, signed) => {
            format!("{}int{}_t", if *signed { "" } else { "u" }, (*bits).max(32))
        }
        Type::Binary(32) => "float".into(),
        Type::Binary(64) => "double".into(),
        Type::Bool => "int32_t".into(),
        Type::Unit => "void".into(),
        _ => unreachable!("the type checker enforces scalar exports"),
    }
}

fn llvm_type(ty: &Type, module: &CheckedModule) -> String {
    match ty {
        Type::Integer(bits, _) | Type::Decimal(bits) | Type::Binary(bits @ (16 | 128)) => {
            format!("i{bits}")
        }
        Type::Binary(32) => "float".into(),
        Type::Binary(64) => "double".into(),
        Type::Binary(_) => unreachable!("binary widths checked"),
        Type::Bool => "i1".into(),
        Type::Unit => "i8".into(),
        Type::String => "%tz.string".into(),
        Type::Record(id) => format!("%tz.record.{}", module.records[*id].name),
        Type::Array(_) => "%tz.array".into(),
        Type::List(_) => "%tz.list".into(),
        Type::Tuple(elements) => format!(
            "{{ {} }}",
            elements
                .iter()
                .map(|ty| llvm_type(ty, module))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Type::Function(..) | Type::Task(_) => "%tz.closure".into(),
        Type::Reference(..) => "ptr".into(),
        Type::Variable(_) | Type::Infer(_) => unreachable!("polymorphism is resolved before LLVM"),
    }
}

fn abi_type(ty: &Type) -> String {
    match ty {
        Type::Integer(8 | 16 | 32, _) | Type::Bool => "i32".into(),
        Type::Integer(64, _) => "i64".into(),
        Type::Binary(32) => "float".into(),
        Type::Binary(64) => "double".into(),
        Type::Unit => "void".into(),
        _ => unreachable!("the type checker enforces scalar exports"),
    }
}

fn validate_main(module: &CheckedModule) -> Result<(), Diagnostic> {
    let main = module
        .entry
        .map(|id| &module.functions[id])
        .ok_or_else(|| {
            Diagnostic::new(
                "E2004",
                "an executable requires top-level entry-point code or 'fn main' in Main.tz; use '--emit object' for a library",
                Span::default(),
            )
        })?;
    if !main.parameters.is_empty()
        || (!main.signature.result.is_scalar()
            && !matches!(main.signature.result, Type::Unit | Type::String))
    {
        return Err(Diagnostic::new(
            "E2004",
            "the Main.tz entry point must take no arguments and return a number, bool, unit, or string",
            main.span,
        ));
    }
    Ok(())
}

struct FunctionEmitter<'a, 'b> {
    module: &'a CheckedModule,
    function: &'a CheckedFunction,
    function_id: usize,
    symbol: String,
    specializations: &'b mut Specializations,
    known_closures: BTreeMap<usize, ClosureTarget>,
    borrowed_locals: BTreeSet<usize>,
    single_use: BTreeSet<usize>,
    borrowed_worker: bool,
    builtins: &'b mut BTreeSet<Builtin>,
    intrinsics: &'b mut BTreeSet<String>,
    lines: Vec<String>,
    allocas: Vec<String>,
    locals: BTreeMap<usize, String>,
    next_value: usize,
    next_block: usize,
    block: String,
    back_edges: Vec<(String, Vec<String>)>,
    scopes: Vec<Vec<(String, Type)>>,
    globals: &'b mut Globals,
}

struct BorrowedCall {
    target: ClosureTarget,
    symbol: String,
    captures: Vec<String>,
    cleanup: Vec<(Type, String)>,
}

impl<'a, 'b> FunctionEmitter<'a, 'b> {
    fn new(
        module: &'a CheckedModule,
        function: &'a CheckedFunction,
        function_id: usize,
        builtins: &'b mut BTreeSet<Builtin>,
        intrinsics: &'b mut BTreeSet<String>,
        globals: &'b mut Globals,
        specializations: &'b mut Specializations,
    ) -> Self {
        Self {
            module,
            function,
            function_id,
            symbol: format!("@tz.fn.{}", function.qualified_name()),
            specializations,
            known_closures: BTreeMap::new(),
            borrowed_locals: BTreeSet::new(),
            single_use: BTreeSet::new(),
            borrowed_worker: false,
            builtins,
            intrinsics,
            globals,
            lines: Vec::new(),
            allocas: Vec::new(),
            locals: BTreeMap::new(),
            next_value: 0,
            next_block: 0,
            block: "entry".into(),
            back_edges: Vec::new(),
            scopes: vec![Vec::new()],
        }
    }

    fn specialized(mut self, id: usize, key: &Specialization) -> Self {
        self.symbol = format!("@tz.specialized.{id}");
        self.borrowed_worker = key.borrowed != 0;
        // The caller retains these immutable payloads; owning temporaries still use normal drops.
        for parameter in &self.function.parameters[..key.borrowed] {
            self.borrowed_locals.insert(parameter.id);
        }
        for (index, target) in &key.callbacks {
            let local = self.function.parameters[*index].id;
            self.borrowed_locals.insert(local);
            self.known_closures.insert(local, *target);
        }
        self
    }

    fn auxiliary(self, signature: &str) -> String {
        let mut output = format!("define internal {signature} nounwind {{\nentry:\n");
        for line in self.allocas {
            let _ = writeln!(output, "  {line}");
        }
        for line in self.lines {
            let _ = writeln!(output, "{line}");
        }
        output.push_str("}\n\n");
        output
    }

    fn emit(mut self) -> String {
        self.single_use = call_specialization::single_use_locals(&self.function.body);
        self.block = "loop".into();
        for (index, parameter) in self.function.parameters.iter().enumerate() {
            self.bind_local(parameter, &format!("%p{index}"));
        }
        self.tail(&self.function.body);
        let parameters = self
            .function
            .parameters
            .iter()
            .enumerate()
            .map(|(index, parameter)| format!("{} %arg{index}", self.ty(&parameter.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let mut output = format!(
            "define internal {} {}({parameters}) nounwind {{\nentry:\n",
            self.ty(&self.function.signature.result),
            self.symbol
        );
        for alloca in self.allocas {
            let _ = writeln!(output, "  {alloca}");
        }
        output.push_str("  br label %loop\nloop:\n");
        for (index, parameter) in self.function.parameters.iter().enumerate() {
            let mut incoming = format!("[ %arg{index}, %entry ]");
            for (block, values) in &self.back_edges {
                let _ = write!(incoming, ", [ {}, %{block} ]", values[index]);
            }
            let _ = writeln!(
                output,
                "  %p{index} = phi {} {incoming}",
                llvm_type(&parameter.ty, self.module)
            );
        }
        for line in self.lines {
            output.push_str(&line);
            output.push('\n');
        }
        output.push_str("}\n\n");
        output
    }

    fn ty(&self, ty: &Type) -> String {
        llvm_type(ty, self.module)
    }

    fn fresh(&mut self) -> String {
        let value = format!("%v{}", self.next_value);
        self.next_value += 1;
        value
    }

    fn instruction(&mut self, text: impl Into<String>) {
        self.lines.push(format!("  {}", text.into()));
    }

    fn value(&mut self, instruction: impl Into<String>) -> String {
        let value = self.fresh();
        self.instruction(format!("{value} = {}", instruction.into()));
        value
    }

    fn label(&mut self) -> String {
        let block = format!("b{}", self.next_block);
        self.next_block += 1;
        block
    }

    fn begin(&mut self, block: &str) {
        self.lines.push(format!("{block}:"));
        self.block = block.to_owned();
    }

    fn jump(&mut self, block: &str) {
        self.instruction(format!("br label %{block}"));
    }

    fn branch(&mut self, condition: &str, yes: &str, no: &str) {
        self.instruction(format!("br i1 {condition}, label %{yes}, label %{no}"));
    }

    fn hint_loop(&mut self, body: &TypedExpr) {
        fn uses(expression: &TypedExpr, id: usize) -> bool {
            matches!(expression.kind, TypedExprKind::Local(local) if local == id)
                || expression
                    .children()
                    .into_iter()
                    .any(|child| uses(child, id))
        }
        fn operands<'a>(
            expression: &'a TypedExpr,
            module: &'a CheckedModule,
        ) -> Option<(BinaryOp, &'a TypedExpr, &'a TypedExpr)> {
            match &expression.kind {
                TypedExprKind::Binary(operator, left, right) => Some((*operator, left, right)),
                TypedExprKind::Call(callee, arguments) if arguments.len() == 2 => {
                    let TypedExprKind::Function(FunctionRef::User(id)) = callee.kind else {
                        return None;
                    };
                    let function = &module.functions[id];
                    if function.parameters.len() != 2 {
                        return None;
                    }
                    let TypedExprKind::Binary(operator, left, right) = &function.body.kind else {
                        return None;
                    };
                    if !matches!(left.kind, TypedExprKind::Local(id) if id == function.parameters[0].id)
                        || !matches!(right.kind, TypedExprKind::Local(id) if id == function.parameters[1].id)
                    {
                        return None;
                    }
                    Some((*operator, &arguments[0], &arguments[1]))
                }
                _ => None,
            }
        }
        fn reduction(expression: &TypedExpr, module: &CheckedModule) -> bool {
            if let TypedExprKind::Assign(place, value) = &expression.kind {
                if let (TypedExprKind::Local(id), Some((operator, left, right))) =
                    (&place.kind, operands(value, module))
                {
                    if matches!(
                        operator,
                        BinaryOp::Add
                            | BinaryOp::Multiply
                            | BinaryOp::BitAnd
                            | BinaryOp::BitOr
                            | BinaryOp::BitXor
                    ) && value.ty.is_integer()
                        && ((matches!(left.kind, TypedExprKind::Local(local) if local == *id)
                            && !uses(right, *id))
                            || (matches!(right.kind, TypedExprKind::Local(local) if local == *id)
                                && !uses(left, *id)))
                    {
                        return true;
                    }
                }
            }
            expression
                .children()
                .into_iter()
                .any(|child| reduction(child, module))
        }
        fn assignments(expression: &TypedExpr) -> usize {
            usize::from(matches!(expression.kind, TypedExprKind::Assign(..)))
                + expression
                    .children()
                    .into_iter()
                    .map(assignments)
                    .sum::<usize>()
        }
        fn small(expression: &TypedExpr, remaining: &mut usize) -> bool {
            if *remaining == 0 {
                return false;
            }
            *remaining -= 1;
            expression
                .children()
                .into_iter()
                .all(|child| small(child, remaining))
        }
        if !small(body, &mut 64) || assignments(body) != 1 || !reduction(body, self.module) {
            return;
        }
        let id = self.globals.next_metadata;
        self.globals.next_metadata += 2;
        self.globals.definitions.push(format!(
            "!{id} = distinct !{{!{id}, !{}}}\n!{} = !{{!\"llvm.loop.unroll.enable\"}}",
            id + 1,
            id + 1
        ));
        let branch = self.lines.last_mut().expect("loop back edge");
        debug_assert!(branch.trim_start().starts_with("br "));
        let _ = write!(branch, ", !llvm.loop !{id}");
    }

    fn guard(&mut self, valid: &str) {
        let success = self.label();
        let failure = self.label();
        self.branch(valid, &success, &failure);
        self.begin(&failure);
        self.instruction("call void @llvm.trap()");
        self.instruction("unreachable");
        self.begin(&success);
    }

    fn slot(&mut self, ty: &Type) -> String {
        let slot = self.fresh();
        self.allocas
            .push(format!("{slot} = alloca {}, align 16", self.ty(ty)));
        slot
    }

    fn bind_local(&mut self, local: &Local, value: &str) {
        let slot = self.slot(&local.ty);
        self.instruction(format!("store {} {value}, ptr {slot}", self.ty(&local.ty)));
        self.locals.insert(local.id, slot.clone());
        if local.ty.needs_drop(&self.module.records) && !self.borrowed_locals.contains(&local.id) {
            self.scopes
                .last_mut()
                .unwrap()
                .push((slot, local.ty.clone()));
        }
    }

    fn bind(&mut self, bindings: &[(Local, TypedExpr)]) {
        for (local, expression) in bindings {
            let target = (!local.mutable)
                .then(|| call_specialization::target(expression, &self.known_closures, self.module))
                .flatten();
            let value = self.expression(expression);
            self.bind_local(local, &value);
            if let Some(target) = target {
                self.known_closures.insert(local.id, target);
            }
        }
    }

    fn is_self(&self, callee: &TypedExpr) -> bool {
        matches!(callee.kind, TypedExprKind::Function(FunctionRef::User(id)) if id == self.function_id)
            && !self.borrowed_worker
            && !self
                .function
                .signature
                .parameters
                .iter()
                .any(|ty| ty.carries_loans(&self.module.records))
    }

    fn tail(&mut self, expression: &TypedExpr) {
        match &expression.kind {
            TypedExprKind::Match { local, value, arms } => {
                self.match_expression(local, value, arms, &expression.ty, true);
            }
            TypedExprKind::Block { bindings, result } => {
                self.scopes.push(Vec::new());
                self.bind(bindings);
                self.tail(result);
                self.scopes.pop();
            }
            TypedExprKind::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.expression(condition);
                let yes = self.label();
                let no = self.label();
                self.branch(&condition, &yes, &no);
                self.begin(&yes);
                self.tail(then_branch);
                self.begin(&no);
                self.tail(else_branch);
            }
            TypedExprKind::Call(callee, arguments)
                if self.is_self(callee) && arguments.len() == self.function.parameters.len() =>
            {
                let values = arguments
                    .iter()
                    .map(|argument| self.expression(argument))
                    .collect();
                self.drop_all();
                self.back_edges.push((self.block.clone(), values));
                self.jump("loop");
                self.hint_loop(&self.function.body);
            }
            TypedExprKind::Binary(BinaryOp::Pipe, argument, callee)
                if self.is_self(callee) && self.function.parameters.len() == 1 =>
            {
                let value = self.expression(argument);
                self.drop_all();
                self.back_edges.push((self.block.clone(), vec![value]));
                self.jump("loop");
                self.hint_loop(&self.function.body);
            }
            _ => {
                let value = self.expression(expression);
                self.drop_all();
                self.instruction(format!("ret {} {value}", self.ty(&expression.ty)));
            }
        }
    }

    fn expression(&mut self, expression: &TypedExpr) -> String {
        self.expression_mode(expression, true)
    }

    fn expression_mode(&mut self, expression: &TypedExpr, take: bool) -> String {
        if Self::is_place(expression) {
            let slot = self.place(expression);
            let value = self.value(format!("load {}, ptr {slot}", self.ty(&expression.ty)));
            if take && expression.ty.needs_drop(&self.module.records) {
                let last_use = matches!(expression.kind, TypedExprKind::Local(id)
                    if self.single_use.contains(&id) && !self.borrowed_locals.contains(&id));
                if expression.ty.is_copy(&self.module.records) && !last_use {
                    return self.clone_value(&expression.ty, &value);
                }
                self.instruction(format!(
                    "store {} zeroinitializer, ptr {slot}",
                    self.ty(&expression.ty)
                ));
            }
            return value;
        }
        match &expression.kind {
            TypedExprKind::Int(value) => value.to_string(),
            TypedExprKind::GenericFunction(..)
            | TypedExprKind::Method(..)
            | TypedExprKind::GenericInteger(..)
            | TypedExprKind::GenericFloat(_)
            | TypedExprKind::Lambda { .. } => {
                unreachable!("polymorphism is resolved before LLVM")
            }
            TypedExprKind::Float(value) => value.clone(),
            TypedExprKind::Bool(value) => if *value { "1" } else { "0" }.into(),
            TypedExprKind::Unit => "0".into(),
            TypedExprKind::While { condition, body } => {
                self.while_loop(condition, body);
                "0".into()
            }
            TypedExprKind::ForRange {
                local,
                start,
                step,
                finish,
                body,
            } => {
                self.range_loop(local, start, step, finish, body);
                "0".into()
            }
            TypedExprKind::ForEach {
                local,
                source,
                body,
                ..
            } => {
                self.for_each(local, source, body);
                "0".into()
            }
            TypedExprKind::Match { local, value, arms } => {
                self.match_expression(local, value, arms, &expression.ty, false)
            }
            TypedExprKind::String(text) => {
                let name = format!("@tz.literal.{}", self.globals.definitions.len());
                let escaped = text
                    .bytes()
                    .map(|byte| format!("\\{byte:02X}"))
                    .collect::<String>();
                self.globals.definitions.push(format!(
                    "{name} = private unnamed_addr constant [{} x i8] c\"{escaped}\"",
                    text.len()
                ));
                self.value(format!(
                    "call %tz.string @tz.string.new(ptr {name}, i64 {})",
                    text.len()
                ))
            }
            TypedExprKind::Local(_)
            | TypedExprKind::Dereference(_)
            | TypedExprKind::ListTail(..) => {
                unreachable!("places handled above")
            }
            TypedExprKind::Borrow(value, _) => self.place(value),
            TypedExprKind::Assign(place, value) => {
                let value = self.expression(value);
                let slot = self.place(place);
                self.drop_slot(&slot, &place.ty);
                self.instruction(format!("store {} {value}, ptr {slot}", self.ty(&place.ty)));
                "0".into()
            }
            TypedExprKind::Cast(value) => self.cast(value, &expression.ty),
            TypedExprKind::Function(reference) => match reference {
                FunctionRef::User(id) => self.make_closure(*id, &[]),
                FunctionRef::Builtin(_) => unreachable!("builtin values are lifted before LLVM"),
            },
            TypedExprKind::Closure(id, captures) => {
                let values: Vec<_> = captures
                    .iter()
                    .map(|capture| self.expression(capture))
                    .collect();
                self.make_closure(*id, &values)
            }
            TypedExprKind::Unary(operator, operand) => {
                let value = self.expression(operand);
                let ty = self.ty(&operand.ty);
                self.value(match operator {
                    UnaryOp::Negate if matches!(operand.ty, Type::Binary(32 | 64)) => {
                        format!("fneg {ty} {value}")
                    }
                    UnaryOp::Negate if operand.ty.is_float() => {
                        let bits = match operand.ty {
                            Type::Binary(bits) | Type::Decimal(bits) => bits,
                            _ => unreachable!(),
                        };
                        format!("xor {ty} {value}, {}", 1u128 << (bits - 1))
                    }
                    UnaryOp::Negate => format!("sub {ty} 0, {value}"),
                    UnaryOp::Not => format!("xor i1 {value}, 1"),
                    UnaryOp::BitNot => format!("xor {ty} {value}, -1"),
                })
            }
            TypedExprKind::Binary(BinaryOp::And | BinaryOp::Or, left, right) => {
                let TypedExprKind::Binary(operator, _, _) = expression.kind else {
                    unreachable!()
                };
                self.short_circuit(operator, left, right)
            }
            TypedExprKind::Binary(BinaryOp::Pipe, argument, callee) => {
                if matches!(callee.kind, TypedExprKind::Function(_)) {
                    return self.call(callee, std::slice::from_ref(argument.as_ref()));
                }
                let value = self.expression(argument);
                if let Some(call) = self.prepare_known_call(callee, 1) {
                    let result = self.emit_borrowed_call(&call, &[value]);
                    self.finish_borrowed_call(&call);
                    return result;
                }
                let function = self.expression(callee);
                self.apply_value(&function, &callee.ty, Some((&argument.ty, &value)))
                    .0
            }
            TypedExprKind::Binary(operator, left, right) => self.binary(*operator, left, right),
            TypedExprKind::Call(callee, arguments) => self.call(callee, arguments),
            TypedExprKind::TaskRun(task) => {
                let task = self.expression(task);
                let code = self.value(format!("extractvalue %tz.closure {task}, 0"));
                let environment = self.value(format!("extractvalue %tz.closure {task}, 1"));
                self.value(format!(
                    "call {} {code}(ptr {environment})",
                    self.ty(&expression.ty)
                ))
            }
            TypedExprKind::TaskParallel(tasks) => self.parallel_tasks(tasks, &expression.ty),
            TypedExprKind::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.expression(condition);
                let yes = self.label();
                let no = self.label();
                let merge = self.label();
                self.branch(&condition, &yes, &no);
                self.begin(&yes);
                let then_value = self.expression(then_branch);
                let then_end = self.block.clone();
                self.jump(&merge);
                self.begin(&no);
                let else_value = self.expression(else_branch);
                let else_end = self.block.clone();
                self.jump(&merge);
                self.begin(&merge);
                self.value(format!(
                    "phi {} [ {then_value}, %{then_end} ], [ {else_value}, %{else_end} ]",
                    self.ty(&expression.ty),
                ))
            }
            TypedExprKind::Block { bindings, result } => {
                self.scopes.push(Vec::new());
                self.bind(bindings);
                let value = self.expression(result);
                let scope = self.scopes.pop().unwrap();
                self.drop_scope(&scope);
                value
            }
            TypedExprKind::Record(fields) => {
                let mut record = "zeroinitializer".into();
                for (index, field) in fields {
                    let value = self.expression(field);
                    record = self.value(format!(
                        "insertvalue {} {record}, {} {value}, {index}",
                        self.ty(&expression.ty),
                        self.ty(&field.ty)
                    ));
                }
                record
            }
            TypedExprKind::Tuple(elements) => {
                let mut tuple = "zeroinitializer".into();
                for (index, element) in elements.iter().enumerate() {
                    let value = self.expression(element);
                    tuple = self.value(format!(
                        "insertvalue {} {tuple}, {} {value}, {index}",
                        self.ty(&expression.ty),
                        self.ty(&element.ty)
                    ));
                }
                tuple
            }
            TypedExprKind::Array(elements) => {
                let Type::Array(element) = &expression.ty else {
                    unreachable!()
                };
                let (array, data) = self.allocate_array(element, &elements.len().to_string());
                for (index, value) in elements.iter().enumerate() {
                    let value = self.expression(value);
                    let pointer = self.element_pointer(element, &data, &index.to_string());
                    self.instruction(format!("store {} {value}, ptr {pointer}", self.ty(element)));
                }
                array
            }
            TypedExprKind::NewArray(length, initializer) => {
                let length = self.expression(length);
                let direct = self.prepare_known_call(initializer, 1);
                let callee = direct.is_none().then(|| self.expression(initializer));
                let Type::Array(element) = &expression.ty else {
                    unreachable!()
                };
                let (array, data) = self.allocate_array(element, &length);
                self.array_loop(&length, |emitter, index| {
                    let value = if let Some(call) = &direct {
                        emitter.emit_borrowed_call(call, &[index.to_owned()])
                    } else {
                        let function =
                            emitter.clone_value(&initializer.ty, callee.as_ref().unwrap());
                        emitter
                            .apply_value(&function, &initializer.ty, Some((&Type::I64, index)))
                            .0
                    };
                    let pointer = emitter.element_pointer(element, &data, index);
                    emitter.instruction(format!(
                        "store {} {value}, ptr {pointer}",
                        emitter.ty(element)
                    ));
                });
                if let Some(call) = &direct {
                    self.finish_borrowed_call(call);
                } else {
                    self.drop_value(&initializer.ty, callee.as_ref().unwrap());
                }
                array
            }
            TypedExprKind::List(elements) => {
                let Type::List(element) = &expression.ty else {
                    unreachable!()
                };
                let (head, tail) = self.list_builder();
                for value in elements {
                    let value = self.expression(value);
                    self.append_list(element, &tail, &value);
                }
                self.finish_list(&head, &elements.len().to_string())
            }
            TypedExprKind::NewList(length, initializer) => {
                let length = self.expression(length);
                let direct = self.prepare_known_call(initializer, 1);
                let callee = direct.is_none().then(|| self.expression(initializer));
                let Type::List(element) = &expression.ty else {
                    unreachable!()
                };
                self.allocation_size(&self.list_node_type(element), &length);
                let (head, tail) = self.list_builder();
                self.array_loop(&length, |emitter, index| {
                    let value = if let Some(call) = &direct {
                        emitter.emit_borrowed_call(call, &[index.to_owned()])
                    } else {
                        let function =
                            emitter.clone_value(&initializer.ty, callee.as_ref().unwrap());
                        emitter
                            .apply_value(&function, &initializer.ty, Some((&Type::I64, index)))
                            .0
                    };
                    emitter.append_list(element, &tail, &value);
                });
                if let Some(call) = &direct {
                    self.finish_borrowed_call(call);
                } else {
                    self.drop_value(&initializer.ty, callee.as_ref().unwrap());
                }
                self.finish_list(&head, &length)
            }
            TypedExprKind::Field(record, index) => {
                let value = self.expression(record);
                let field = self.value(format!(
                    "extractvalue {} {value}, {index}",
                    self.ty(&record.ty)
                ));
                if record.ty.needs_drop(&self.module.records) {
                    let remainder = self.value(format!(
                        "insertvalue {} {value}, {} zeroinitializer, {index}",
                        self.ty(&record.ty),
                        self.ty(&expression.ty)
                    ));
                    self.drop_value(&record.ty, &remainder);
                }
                field
            }
            TypedExprKind::Index(string, index) if string.ty == Type::String => {
                let value = self.expression_mode(string, false);
                let index = self.expression(index);
                let data = self.value(format!("extractvalue %tz.string {value}, 0"));
                let length = self.value(format!("extractvalue %tz.string {value}, 1"));
                let valid = self.value(format!("icmp ult i64 {index}, {length}"));
                self.guard(&valid);
                let pointer = self.value(format!(
                    "getelementptr inbounds i8, ptr {data}, i64 {index}"
                ));
                let byte = self.value(format!("load i8, ptr {pointer}"));
                self.drop_temporary(string, &value);
                byte
            }
            TypedExprKind::Index(array, index) => {
                let value = self.expression_mode(array, false);
                let index = self.expression(index);
                let (Type::Array(element) | Type::List(element)) = &array.ty else {
                    unreachable!()
                };
                let pointer = self.checked_element_pointer(&array.ty, &value, &index);
                let extracted = self.value(format!("load {}, ptr {pointer}", self.ty(element)));
                let result = self.clone_value(element, &extracted);
                self.drop_temporary(array, &value);
                result
            }
            TypedExprKind::Length(array) => {
                let value = self.expression_mode(array, false);
                let length = self.value(format!("extractvalue {} {value}, 1", self.ty(&array.ty)));
                self.drop_temporary(array, &value);
                length
            }
            TypedExprKind::StringLength(string) => {
                let value = self.expression_mode(string, false);
                let length = self.value(format!("extractvalue %tz.string {value}, 1"));
                self.drop_temporary(string, &value);
                length
            }
        }
    }

    fn is_place(expression: &TypedExpr) -> bool {
        match &expression.kind {
            TypedExprKind::Local(_) | TypedExprKind::Dereference(_) => true,
            TypedExprKind::Field(value, _) | TypedExprKind::ListTail(value, _) => {
                Self::is_place(value)
            }
            TypedExprKind::Index(value, _) => {
                matches!(value.ty, Type::Array(_) | Type::List(_)) && Self::is_place(value)
            }
            _ => false,
        }
    }

    fn place(&mut self, expression: &TypedExpr) -> String {
        match &expression.kind {
            TypedExprKind::Local(id) => self.locals[id].clone(),
            TypedExprKind::Dereference(value) => self.expression_mode(value, false),
            TypedExprKind::Field(value, index) => {
                let slot = self.place(value);
                self.value(format!(
                    "getelementptr inbounds {}, ptr {slot}, i32 0, i32 {index}",
                    self.ty(&value.ty)
                ))
            }
            TypedExprKind::ListTail(value, count) => {
                let slot = self.place(value);
                let list = self.value(format!("load %tz.list, ptr {slot}"));
                let length = self.value(format!("extractvalue %tz.list {list}, 1"));
                let valid = self.value(format!("icmp uge i64 {length}, {count}"));
                self.guard(&valid);
                let head = self.value(format!("extractvalue %tz.list {list}, 0"));
                let tail = self.list_loop(&head, &count.to_string(), |_, _| {});
                let length = self.value(format!("sub i64 {length}, {count}"));
                let descriptor = self.value(format!(
                    "insertvalue %tz.list zeroinitializer, ptr {tail}, 0"
                ));
                let descriptor = self.value(format!(
                    "insertvalue %tz.list {descriptor}, i64 {length}, 1"
                ));
                let slot = self.slot(&value.ty);
                self.instruction(format!("store %tz.list {descriptor}, ptr {slot}"));
                slot
            }
            TypedExprKind::Index(value, index) => {
                let slot = self.place(value);
                let array = self.value(format!("load {}, ptr {slot}", self.ty(&value.ty)));
                let index = self.expression(index);
                self.checked_element_pointer(&value.ty, &array, &index)
            }
            _ => unreachable!("borrow checker requires an addressable place"),
        }
    }

    fn drop_value(&mut self, ty: &Type, value: &str) {
        match ty {
            Type::Function(..) | Type::Task(_) => {
                self.instruction(format!("call void @tz.closure.drop(%tz.closure {value})"))
            }
            Type::String => {
                let pointer = self.value(format!("extractvalue %tz.string {value}, 0"));
                self.instruction(format!("call void @tz.free(ptr {pointer})"));
            }
            Type::Record(id) => {
                for (index, (_, field)) in self.module.records[*id].fields.iter().enumerate() {
                    if field.needs_drop(&self.module.records) {
                        let extracted =
                            self.value(format!("extractvalue {} {value}, {index}", self.ty(ty)));
                        self.drop_value(field, &extracted);
                    }
                }
            }
            Type::Tuple(elements) => {
                for (index, field) in elements.iter().enumerate() {
                    if field.needs_drop(&self.module.records) {
                        let extracted =
                            self.value(format!("extractvalue {} {value}, {index}", self.ty(ty)));
                        self.drop_value(field, &extracted);
                    }
                }
            }
            Type::Array(element) => {
                let data = self.value(format!("extractvalue %tz.array {value}, 0"));
                if element.needs_drop(&self.module.records) {
                    let length = self.value(format!("extractvalue %tz.array {value}, 1"));
                    self.array_loop(&length, |emitter, index| {
                        let pointer = emitter.element_pointer(element, &data, index);
                        let extracted =
                            emitter.value(format!("load {}, ptr {pointer}", emitter.ty(element)));
                        emitter.drop_value(element, &extracted);
                    });
                }
                self.instruction(format!("call void @tz.free(ptr {data})"));
            }
            Type::List(element) => {
                let head = self.value(format!("extractvalue %tz.list {value}, 0"));
                let length = self.value(format!("extractvalue %tz.list {value}, 1"));
                self.list_loop(&head, &length, |emitter, node| {
                    if element.needs_drop(&emitter.module.records) {
                        let pointer = emitter.list_element_pointer(element, node);
                        let value =
                            emitter.value(format!("load {}, ptr {pointer}", emitter.ty(element)));
                        emitter.drop_value(element, &value);
                    }
                    emitter.instruction(format!("call void @tz.free(ptr {node})"));
                });
            }
            _ => {}
        }
    }
    fn clone_value(&mut self, ty: &Type, value: &str) -> String {
        match ty {
            Type::Task(_) => unreachable!("single-use tasks cannot be cloned"),
            Type::String => {
                let pointer = self.value(format!("extractvalue %tz.string {value}, 0"));
                let length = self.value(format!("extractvalue %tz.string {value}, 1"));
                self.value(format!(
                    "call %tz.string @tz.string.new(ptr {pointer}, i64 {length})"
                ))
            }
            Type::Function(..) => self.value(format!(
                "call %tz.closure @tz.closure.clone(%tz.closure {value})"
            )),
            Type::Record(id) => {
                let mut result = value.to_owned();
                for (index, (_, field)) in self.module.records[*id].fields.iter().enumerate() {
                    if field.needs_drop(&self.module.records) {
                        let field_value =
                            self.value(format!("extractvalue {} {value}, {index}", self.ty(ty)));
                        let copy = self.clone_value(field, &field_value);
                        result = self.value(format!(
                            "insertvalue {} {result}, {} {copy}, {index}",
                            self.ty(ty),
                            self.ty(field)
                        ));
                    }
                }
                result
            }
            Type::Tuple(elements) => {
                let mut result = value.to_owned();
                for (index, field) in elements.iter().enumerate() {
                    if field.needs_drop(&self.module.records) {
                        let extracted =
                            self.value(format!("extractvalue {} {value}, {index}", self.ty(ty)));
                        let copy = self.clone_value(field, &extracted);
                        result = self.value(format!(
                            "insertvalue {} {result}, {} {copy}, {index}",
                            self.ty(ty),
                            self.ty(field)
                        ));
                    }
                }
                result
            }
            Type::Array(element) => {
                let data = self.value(format!("extractvalue %tz.array {value}, 0"));
                let length = self.value(format!("extractvalue %tz.array {value}, 1"));
                let (result, target) = self.allocate_array(element, &length);
                self.array_loop(&length, |emitter, index| {
                    let source = emitter.element_pointer(element, &data, index);
                    let element_value =
                        emitter.value(format!("load {}, ptr {source}", emitter.ty(element)));
                    let copy = emitter.clone_value(element, &element_value);
                    let destination = emitter.element_pointer(element, &target, index);
                    emitter.instruction(format!(
                        "store {} {copy}, ptr {destination}",
                        emitter.ty(element)
                    ));
                });
                result
            }
            Type::List(element) => {
                let source = self.value(format!("extractvalue %tz.list {value}, 0"));
                let length = self.value(format!("extractvalue %tz.list {value}, 1"));
                let (head, tail) = self.list_builder();
                self.list_loop(&source, &length, |emitter, node| {
                    let pointer = emitter.list_element_pointer(element, node);
                    let value =
                        emitter.value(format!("load {}, ptr {pointer}", emitter.ty(element)));
                    let copy = emitter.clone_value(element, &value);
                    emitter.append_list(element, &tail, &copy);
                });
                self.finish_list(&head, &length)
            }
            _ => value.to_owned(),
        }
    }

    fn allocate_array(&mut self, element: &Type, length: &str) -> (String, String) {
        let bytes = self.allocation_size(&self.ty(element), length);
        let empty = self.value(format!("icmp eq i64 {length}, 0"));
        let bytes = self.value(format!("select i1 {empty}, i64 1, i64 {bytes}"));
        let data = self.value(format!("call ptr @tz.alloc(i64 {bytes})"));
        let array = self.value(format!(
            "insertvalue %tz.array zeroinitializer, ptr {data}, 0"
        ));
        let array = self.value(format!("insertvalue %tz.array {array}, i64 {length}, 1"));
        (array, data)
    }

    fn allocation_size(&mut self, ty: &str, length: &str) -> String {
        let size = format!("ptrtoint (ptr getelementptr ({ty}, ptr null, i32 1) to i64)");
        let zero = self.value(format!("icmp eq i64 {size}, 0"));
        let stride = self.value(format!("select i1 {zero}, i64 1, i64 {size}"));
        let limit = self.value(format!("udiv i64 {}, {stride}", i64::MAX));
        // Unsigned comparison rejects negative lengths as well as byte-size overflow.
        let valid = self.value(format!("icmp ule i64 {length}, {limit}"));
        self.guard(&valid);
        self.value(format!("mul i64 {length}, {stride}"))
    }

    fn element_pointer(&mut self, element: &Type, data: &str, index: &str) -> String {
        self.value(format!(
            "getelementptr inbounds {}, ptr {data}, i64 {index}",
            self.ty(element)
        ))
    }

    fn checked_element_pointer(&mut self, ty: &Type, collection: &str, index: &str) -> String {
        let length = self.value(format!("extractvalue {} {collection}, 1", self.ty(ty)));
        let valid = self.value(format!("icmp ult i64 {index}, {length}"));
        self.guard(&valid);
        let data = self.value(format!("extractvalue {} {collection}, 0", self.ty(ty)));
        match ty {
            Type::Array(element) => self.element_pointer(element, &data, index),
            Type::List(element) => {
                let node = self.list_loop(&data, index, |_, _| {});
                self.list_element_pointer(element, &node)
            }
            _ => unreachable!("indexing requires a collection"),
        }
    }

    fn list_node_type(&self, element: &Type) -> String {
        format!("{{ ptr, {} }}", self.ty(element))
    }

    fn list_element_pointer(&mut self, element: &Type, node: &str) -> String {
        self.value(format!(
            "getelementptr inbounds {}, ptr {node}, i32 0, i32 1",
            self.list_node_type(element)
        ))
    }

    fn list_builder(&mut self) -> (String, String) {
        let pointer = Type::Reference(Box::new(Type::Unit), false);
        let head = self.slot(&pointer);
        let tail = self.slot(&pointer);
        self.instruction(format!("store ptr null, ptr {head}"));
        self.instruction(format!("store ptr {head}, ptr {tail}"));
        (head, tail)
    }

    fn append_list(&mut self, element: &Type, tail: &str, value: &str) {
        let node = self.value(format!(
            "call ptr @tz.alloc(i64 ptrtoint (ptr getelementptr ({}, ptr null, i32 1) to i64))",
            self.list_node_type(element)
        ));
        self.instruction(format!("store ptr null, ptr {node}"));
        let pointer = self.list_element_pointer(element, &node);
        self.instruction(format!("store {} {value}, ptr {pointer}", self.ty(element)));
        let previous = self.value(format!("load ptr, ptr {tail}"));
        self.instruction(format!("store ptr {node}, ptr {previous}"));
        // The first field of each node is the next pointer, also used as the builder's tail slot.
        self.instruction(format!("store ptr {node}, ptr {tail}"));
    }

    fn finish_list(&mut self, head: &str, length: &str) -> String {
        let head = self.value(format!("load ptr, ptr {head}"));
        let list = self.value(format!(
            "insertvalue %tz.list zeroinitializer, ptr {head}, 0"
        ));
        self.value(format!("insertvalue %tz.list {list}, i64 {length}, 1"))
    }

    fn list_loop(
        &mut self,
        head: &str,
        length: &str,
        body: impl FnOnce(&mut Self, &str),
    ) -> String {
        let entry = self.block.clone();
        let condition = self.label();
        let element = self.label();
        let advance = self.label();
        let exit = self.label();
        let index = self.fresh();
        let next_index = self.fresh();
        let node = self.fresh();
        let next_node = self.fresh();
        self.jump(&condition);
        self.begin(&condition);
        self.instruction(format!(
            "{index} = phi i64 [ 0, %{entry} ], [ {next_index}, %{advance} ]"
        ));
        self.instruction(format!(
            "{node} = phi ptr [ {head}, %{entry} ], [ {next_node}, %{advance} ]"
        ));
        let more = self.value(format!("icmp ult i64 {index}, {length}"));
        self.branch(&more, &element, &exit);
        self.begin(&element);
        // Read the link before the callback, which may free this node.
        self.instruction(format!("{next_node} = load ptr, ptr {node}"));
        body(self, &node);
        self.jump(&advance);
        self.begin(&advance);
        self.instruction(format!("{next_index} = add i64 {index}, 1"));
        self.jump(&condition);
        self.begin(&exit);
        node
    }

    fn array_loop(&mut self, length: &str, body: impl FnOnce(&mut Self, &str)) {
        let entry = self.block.clone();
        let condition = self.label();
        let element = self.label();
        let advance = self.label();
        let exit = self.label();
        let index = self.fresh();
        let next = self.fresh();
        self.jump(&condition);
        self.begin(&condition);
        self.instruction(format!(
            "{index} = phi i64 [ 0, %{entry} ], [ {next}, %{advance} ]"
        ));
        let more = self.value(format!("icmp ult i64 {index}, {length}"));
        self.branch(&more, &element, &exit);
        self.begin(&element);
        body(self, &index);
        self.jump(&advance);
        self.begin(&advance);
        self.instruction(format!("{next} = add i64 {index}, 1"));
        self.jump(&condition);
        self.begin(&exit);
    }

    fn make_closure(&mut self, id: usize, values: &[String]) -> String {
        let function = &self.module.functions[id];
        let count = values.len();
        let environment = if count == 0 {
            "null".to_owned()
        } else {
            let ty = environment_type(function, count, self.module);
            let environment = self.value(format!("call ptr @tz.alloc(i64 ptrtoint (ptr getelementptr ({ty}, ptr null, i32 1) to i64))"));
            for (index, value) in values.iter().enumerate() {
                let pointer = self.value(format!(
                    "getelementptr inbounds {ty}, ptr {environment}, i32 0, i32 {index}"
                ));
                self.instruction(format!(
                    "store {} {value}, ptr {pointer}",
                    self.ty(&function.signature.parameters[index])
                ));
            }
            environment
        };
        self.closure_descriptor(id, count, &environment)
    }

    fn closure_descriptor(&mut self, id: usize, count: usize, environment: &str) -> String {
        let function = &self.module.functions[id];
        let name = function.qualified_name();
        let value = self.value(format!(
            "insertvalue %tz.closure zeroinitializer, ptr @tz.apply.{name}.{count}, 0"
        ));
        let value = self.value(format!(
            "insertvalue %tz.closure {value}, ptr {environment}, 1"
        ));
        if count == 0 {
            return value;
        }
        let value = if !function.is_task
            && function.signature.parameters[..count]
                .iter()
                .all(|ty| ty.can_capture(&self.module.records))
        {
            self.value(format!(
                "insertvalue %tz.closure {value}, ptr @tz.env.clone.{name}.{count}, 2"
            ))
        } else {
            value
        };
        self.value(format!(
            "insertvalue %tz.closure {value}, ptr @tz.env.drop.{name}.{count}, 3"
        ))
    }

    fn stack_closure(&mut self, target: ClosureTarget, values: &[String]) -> String {
        if values.is_empty() {
            return self.closure_descriptor(target.function, 0, "null");
        }
        let function = &self.module.functions[target.function];
        let environment_ty = environment_type(function, target.bound, self.module);
        let environment = self.fresh();
        self.allocas
            .push(format!("{environment} = alloca {environment_ty}, align 16"));
        for (index, value) in values.iter().enumerate() {
            let pointer = self.value(format!(
                "getelementptr inbounds {environment_ty}, ptr {environment}, i32 0, i32 {index}"
            ));
            self.instruction(format!(
                "store {} {value}, ptr {pointer}",
                self.ty(&function.signature.parameters[index])
            ));
        }
        self.closure_descriptor(target.function, target.bound, &environment)
    }

    fn parallel_tasks(&mut self, tasks: &TypedExpr, result: &Type) -> String {
        let tasks = self.expression(tasks);
        let source = self.value(format!("extractvalue %tz.array {tasks}, 0"));
        let length = self.value(format!("extractvalue %tz.array {tasks}, 1"));
        let Type::Array(element) = result else {
            unreachable!()
        };
        let (array, target) = self.allocate_array(element, &length);
        let ty = self.ty(element);
        let callback = format!("@tz.task.item.{}", ty.trim_start_matches('%'));
        self.intrinsics.insert(format!(
            "define internal void {callback}(ptr %context, i64 %index) nounwind {{\n\
             entry:\n\
               %source = load ptr, ptr %context\n\
               %target.slot = getelementptr inbounds {{ ptr, ptr }}, ptr %context, i32 0, i32 1\n\
               %target = load ptr, ptr %target.slot\n\
               %slot = getelementptr inbounds %tz.closure, ptr %source, i64 %index\n\
               %task = load %tz.closure, ptr %slot\n\
               %code = extractvalue %tz.closure %task, 0\n\
               %env = extractvalue %tz.closure %task, 1\n\
               %result = call {ty} %code(ptr %env)\n\
               %destination = getelementptr inbounds {ty}, ptr %target, i64 %index\n\
               store {ty} %result, ptr %destination\n\
               ret void\n\
             }}\n"
        ));
        let context = self.fresh();
        self.allocas
            .push(format!("{context} = alloca {{ ptr, ptr }}, align 16"));
        self.instruction(format!("store ptr {source}, ptr {context}"));
        let slot = self.value(format!(
            "getelementptr inbounds {{ ptr, ptr }}, ptr {context}, i32 0, i32 1"
        ));
        self.instruction(format!("store ptr {target}, ptr {slot}"));
        self.instruction(format!(
            "call void @tsuzuri_task_parallel(ptr {callback}, ptr {context}, i64 {length})"
        ));
        self.instruction(format!("call void @tz.free(ptr {source})"));
        array
    }

    fn apply_value(
        &mut self,
        callee: &str,
        ty: &Type,
        argument: Option<(&Type, &str)>,
    ) -> (String, Type) {
        let code = self.value(format!("extractvalue %tz.closure {callee}, 0"));
        let environment = self.value(format!("extractvalue %tz.closure {callee}, 1"));
        let result = ty.after_arguments(usize::from(argument.is_some()));
        let argument = argument.map_or_else(String::new, |(ty, value)| {
            format!(", {} {value}", self.ty(ty))
        });
        let value = self.value(format!(
            "call {} {code}(ptr {environment}{argument})",
            self.ty(&result)
        ));
        (value, result)
    }

    fn call(&mut self, callee: &TypedExpr, arguments: &[TypedExpr]) -> String {
        if let TypedExprKind::Function(FunctionRef::User(id)) = callee.kind {
            let function = &self.module.functions[id];
            if arguments.len() == 1 && call_specialization::is_identity(function) {
                return self.expression(&arguments[0]);
            }
        }
        if !matches!(callee.kind, TypedExprKind::Function(_)) {
            if let Some(target) =
                call_specialization::target(callee, &self.known_closures, self.module)
            {
                if target.bound + arguments.len()
                    == self.module.functions[target.function].parameters.len()
                    && !arguments
                        .iter()
                        .any(|argument| call_specialization::may_mutate(argument, self.module))
                    && self.specializations.can_borrow(target, self.module)
                {
                    if let Some(value) = self.borrowed_call(callee, target, arguments) {
                        return value;
                    }
                }
            }
        }
        let known = match callee.kind {
            TypedExprKind::Function(FunctionRef::User(id)) => {
                let function = &self.module.functions[id];
                if arguments.len() < function.parameters.len() {
                    let values: Vec<_> = arguments
                        .iter()
                        .map(|argument| self.expression(argument))
                        .collect();
                    return self.make_closure(id, &values);
                }
                let mut callbacks = Vec::new();
                if arguments.len() == function.parameters.len() {
                    for index in self.specializations.eligible[id].clone() {
                        if arguments[index + 1..]
                            .iter()
                            .any(|argument| call_specialization::may_mutate(argument, self.module))
                        {
                            continue;
                        }
                        if let Some(target) = call_specialization::target(
                            &arguments[index],
                            &self.known_closures,
                            self.module,
                        ) {
                            if self.specializations.can_borrow(target, self.module) {
                                callbacks.push((index, target));
                            }
                        }
                    }
                }
                let symbol = if callbacks.is_empty() {
                    format!("@tz.fn.{}", function.qualified_name())
                } else if let Some(variant) = self.specializations.request(Specialization {
                    function: id,
                    callbacks: callbacks.clone(),
                    borrowed: 0,
                }) {
                    format!("@tz.specialized.{variant}")
                } else {
                    callbacks.clear();
                    format!("@tz.fn.{}", function.qualified_name())
                };
                Some((symbol, function.signature.clone(), callbacks))
            }
            TypedExprKind::Function(FunctionRef::Builtin(builtin)) => {
                self.builtins.insert(builtin);
                Some((
                    format!("@tz.builtin.{}", builtin.name()),
                    builtin.signature(),
                    Vec::new(),
                ))
            }
            _ => None,
        };
        let (mut value, mut ty, consumed) = if let Some((symbol, signature, callbacks)) = known {
            let count = signature.parameters.len();
            let mut values = Vec::new();
            let mut cleanup = Vec::new();
            for (index, argument) in arguments[..count].iter().enumerate() {
                let value =
                    if let Some((_, target)) = callbacks.iter().find(|(slot, _)| *slot == index) {
                        let argument = call_specialization::transparent(argument, self.module);
                        if Self::is_place(argument) {
                            self.expression_mode(argument, false)
                        } else {
                            let captures = self.capture_values(argument);
                            self.capture_cleanup(*target, &captures, &mut cleanup);
                            self.stack_closure(*target, &captures)
                        }
                    } else {
                        self.expression(argument)
                    };
                values.push(format!("{} {value}", self.ty(&argument.ty)));
            }
            let values = values.join(", ");
            let value = self.value(format!(
                "call {} {symbol}({values})",
                self.ty(&signature.result)
            ));
            for (ty, value) in cleanup.iter().rev() {
                self.drop_value(ty, value);
            }
            (value, signature.result, count)
        } else {
            let value = self.expression(callee);
            if arguments.is_empty() {
                return self.apply_value(&value, &callee.ty, None).0;
            }
            (value, callee.ty.clone(), 0)
        };
        for argument in &arguments[consumed..] {
            let next = self.expression(argument);
            (value, ty) = self.apply_value(&value, &ty, Some((&argument.ty, &next)));
        }
        value
    }

    fn capture_values(&mut self, expression: &TypedExpr) -> Vec<String> {
        let expression = call_specialization::transparent(expression, self.module);
        match &expression.kind {
            TypedExprKind::Closure(_, values) | TypedExprKind::Call(_, values) => {
                values.iter().map(|value| self.expression(value)).collect()
            }
            TypedExprKind::Function(_) => Vec::new(),
            _ => unreachable!("known temporary closures have explicit captures"),
        }
    }

    fn capture_cleanup(
        &self,
        target: ClosureTarget,
        values: &[String],
        cleanup: &mut Vec<(Type, String)>,
    ) {
        for (value, ty) in values
            .iter()
            .zip(&self.module.functions[target.function].signature.parameters[..target.bound])
        {
            if ty.needs_drop(&self.module.records) {
                cleanup.push((ty.clone(), value.clone()));
            }
        }
    }

    fn borrowed_call(
        &mut self,
        callee: &TypedExpr,
        target: ClosureTarget,
        arguments: &[TypedExpr],
    ) -> Option<String> {
        let call = self.prepare_borrowed_call(callee, target)?;
        let arguments: Vec<_> = arguments
            .iter()
            .map(|argument| self.expression(argument))
            .collect();
        let result = self.emit_borrowed_call(&call, &arguments);
        self.finish_borrowed_call(&call);
        Some(result)
    }

    fn prepare_known_call(&mut self, expression: &TypedExpr, arity: usize) -> Option<BorrowedCall> {
        let target = call_specialization::target(expression, &self.known_closures, self.module)?;
        if target.bound + arity != self.module.functions[target.function].parameters.len()
            || !self.specializations.can_borrow(target, self.module)
        {
            return None;
        }
        self.prepare_borrowed_call(expression, target)
    }

    fn prepare_borrowed_call(
        &mut self,
        callee: &TypedExpr,
        target: ClosureTarget,
    ) -> Option<BorrowedCall> {
        let callee = call_specialization::transparent(callee, self.module);
        let function = &self.module.functions[target.function];
        let symbol = if target.bound == 0 {
            format!("@tz.fn.{}", function.qualified_name())
        } else {
            let id = self.specializations.request(Specialization {
                function: target.function,
                callbacks: Vec::new(),
                borrowed: target.bound,
            })?;
            format!("@tz.specialized.{id}")
        };
        let mut cleanup = Vec::new();
        let captures = if Self::is_place(callee) {
            let value = self.expression_mode(callee, false);
            let environment = self.value(format!("extractvalue %tz.closure {value}, 1"));
            let environment_ty = environment_type(function, target.bound, self.module);
            let mut values = Vec::new();
            for (index, ty) in function.signature.parameters[..target.bound]
                .iter()
                .enumerate()
            {
                let pointer = self.value(format!(
                    "getelementptr inbounds {environment_ty}, ptr {environment}, i32 0, i32 {index}",
                ));
                values.push(self.value(format!("load {}, ptr {pointer}", self.ty(ty))));
            }
            values
        } else {
            let values = self.capture_values(callee);
            self.capture_cleanup(target, &values, &mut cleanup);
            values
        };
        Some(BorrowedCall {
            target,
            symbol,
            captures,
            cleanup,
        })
    }

    fn emit_borrowed_call(&mut self, call: &BorrowedCall, arguments: &[String]) -> String {
        let function = &self.module.functions[call.target.function];
        let values = call
            .captures
            .iter()
            .chain(arguments)
            .zip(&function.signature.parameters)
            .map(|(value, ty)| format!("{} {value}", self.ty(ty)))
            .collect::<Vec<_>>()
            .join(", ");
        self.value(format!(
            "call {} {}({values})",
            self.ty(&function.signature.result),
            call.symbol
        ))
    }

    fn finish_borrowed_call(&mut self, call: &BorrowedCall) {
        for (ty, value) in call.cleanup.iter().rev() {
            self.drop_value(ty, value);
        }
    }

    fn drop_slot(&mut self, slot: &str, ty: &Type) {
        if ty.needs_drop(&self.module.records) {
            let value = self.value(format!("load {}, ptr {slot}", self.ty(ty)));
            self.drop_value(ty, &value);
            self.instruction(format!("store {} zeroinitializer, ptr {slot}", self.ty(ty)));
        }
    }

    fn drop_temporary(&mut self, expression: &TypedExpr, value: &str) {
        if !Self::is_place(expression) {
            self.drop_value(&expression.ty, value);
        }
    }

    fn drop_scope(&mut self, scope: &[(String, Type)]) {
        for (slot, ty) in scope.iter().rev() {
            self.drop_slot(slot, ty);
        }
    }

    fn drop_all(&mut self) {
        for scope in self.scopes.clone().iter().rev() {
            self.drop_scope(scope);
        }
    }

    fn spill(&mut self, ty: &Type, value: &str) -> String {
        let slot = self.slot(ty);
        self.instruction(format!("store {} {value}, ptr {slot}", self.ty(ty)));
        slot
    }

    fn cast(&mut self, expression: &TypedExpr, to: &Type) -> String {
        let value = self.expression(expression);
        if expression.ty == *to {
            return value;
        }
        if let (Type::Integer(from, signed), Type::Integer(bits, _)) = (&expression.ty, to) {
            if from == bits {
                return value;
            }
            let instruction = if bits < from {
                "trunc"
            } else if *signed {
                "sext"
            } else {
                "zext"
            };
            return self.value(format!(
                "{instruction} {} {value} to {}",
                self.ty(&expression.ty),
                self.ty(to)
            ));
        }
        let instruction = match (&expression.ty, to) {
            (Type::Integer(8 | 16 | 32 | 64, true), Type::Binary(32 | 64)) => Some("sitofp"),
            (Type::Integer(8 | 16 | 32 | 64, false), Type::Binary(32 | 64)) => Some("uitofp"),
            (Type::Binary(32), Type::Binary(64)) => Some("fpext"),
            (Type::Binary(64), Type::Binary(32)) => Some("fptrunc"),
            _ => None,
        };
        if let Some(instruction) = instruction {
            return self.value(format!(
                "{instruction} {} {value} to {}",
                self.ty(&expression.ty),
                self.ty(to)
            ));
        }
        if let (Type::Binary(from @ (32 | 64)), Type::Integer(bits @ (8 | 16 | 32 | 64), signed)) =
            (&expression.ty, to)
        {
            let intrinsic = saturating_cast(*from, *bits, *signed, self.intrinsics);
            return self.value(format!(
                "call {} @{intrinsic}({} {value})",
                self.ty(to),
                self.ty(&expression.ty)
            ));
        }
        let input = self.spill(&expression.ty, &value);
        let output = self.slot(to);
        self.instruction(format!(
            "call void @tz_soft_cast(ptr {output}, ptr {input}, i32 {}, i32 {})",
            numeric_kind(&expression.ty),
            numeric_kind(to)
        ));
        self.value(format!("load {}, ptr {output}", self.ty(to)))
    }

    fn short_circuit(&mut self, operator: BinaryOp, left: &TypedExpr, right: &TypedExpr) -> String {
        let left = self.expression(left);
        let left_end = self.block.clone();
        let evaluate_right = self.label();
        let merge = self.label();
        let shortcut = if operator == BinaryOp::And {
            self.branch(&left, &evaluate_right, &merge);
            "0"
        } else {
            self.branch(&left, &merge, &evaluate_right);
            "1"
        };
        self.begin(&evaluate_right);
        let right = self.expression(right);
        let right_end = self.block.clone();
        self.jump(&merge);
        self.begin(&merge);
        self.value(format!(
            "phi i1 [ {shortcut}, %{left_end} ], [ {right}, %{right_end} ]"
        ))
    }

    fn binary(&mut self, operator: BinaryOp, left: &TypedExpr, right: &TypedExpr) -> String {
        use BinaryOp::*;
        if left.ty == Type::String {
            let take = operator == Add;
            let lhs = self.expression_mode(left, take);
            let rhs = self.expression_mode(right, take);
            let result = if take {
                self.value(format!(
                    "call %tz.string @tz.string.concat(%tz.string {lhs}, %tz.string {rhs})"
                ))
            } else {
                self.value(format!(
                    "call i1 @tz.string.equal(%tz.string {lhs}, %tz.string {rhs})"
                ))
            };
            if take {
                self.drop_value(&left.ty, &lhs);
                self.drop_value(&right.ty, &rhs);
            } else {
                self.drop_temporary(left, &lhs);
                self.drop_temporary(right, &rhs);
            }
            return if operator == NotEqual {
                self.value(format!("xor i1 {result}, 1"))
            } else {
                result
            };
        }
        let lhs = self.expression(left);
        let mut rhs = self.expression(right);
        let ty = self.ty(&left.ty);
        if matches!(left.ty, Type::Decimal(_) | Type::Binary(16 | 128)) {
            let a = self.spill(&left.ty, &lhs);
            let b = self.spill(&right.ty, &rhs);
            let kind = numeric_kind(&left.ty);
            if matches!(operator, Add | Subtract | Multiply | Divide) {
                let op = match operator {
                    Add => 0,
                    Subtract => 1,
                    Multiply => 2,
                    _ => 3,
                };
                let output = self.slot(&left.ty);
                self.instruction(format!(
                    "call void @tz_soft_op(ptr {output}, ptr {a}, ptr {b}, i32 {kind}, i32 {op})"
                ));
                return self.value(format!("load {ty}, ptr {output}"));
            }
            let order = self.value(format!(
                "call i32 @tz_soft_cmp(ptr {a}, ptr {b}, i32 {kind})"
            ));
            let (predicate, value) = match operator {
                Equal => ("eq", 0),
                NotEqual => ("ne", 0),
                Less => ("slt", 0),
                LessEqual => ("sle", 0),
                Greater => ("eq", 1),
                GreaterEqual => ("ule", 1),
                _ => unreachable!("software float operator checked"),
            };
            return self.value(format!("icmp {predicate} i32 {order}, {value}"));
        }
        if matches!(operator, Divide | Remainder) && left.ty.is_integer() {
            let mut valid = self.value(format!("icmp ne {ty} {rhs}, 0"));
            if let Type::Integer(bits, true) = left.ty {
                let minimum = self.value(format!("icmp eq {ty} {lhs}, {}", 1u128 << (bits - 1)));
                let negative_one = self.value(format!("icmp eq {ty} {rhs}, -1"));
                let overflow = self.value(format!("and i1 {minimum}, {negative_one}"));
                let no_overflow = self.value(format!("xor i1 {overflow}, 1"));
                valid = self.value(format!("and i1 {valid}, {no_overflow}"));
            }
            self.guard(&valid);
        }
        if matches!(operator, ShiftLeft | ShiftRight | ShiftRightUnsigned) {
            let Type::Integer(bits, _) = left.ty else {
                unreachable!()
            };
            rhs = self.value(format!("and {ty} {rhs}, {}", bits - 1));
        }
        let unsigned = matches!(left.ty, Type::Integer(_, false));
        let instruction = if left.ty.is_float() {
            match operator {
                Add => "fadd",
                Subtract => "fsub",
                Multiply => "fmul",
                Divide => "fdiv",
                Equal => "fcmp oeq",
                NotEqual => "fcmp une",
                Less => "fcmp olt",
                LessEqual => "fcmp ole",
                Greater => "fcmp ogt",
                GreaterEqual => "fcmp oge",
                _ => unreachable!("float operator checked"),
            }
        } else {
            match operator {
                Add => "add",
                Subtract => "sub",
                Multiply => "mul",
                Divide => {
                    if unsigned {
                        "udiv"
                    } else {
                        "sdiv"
                    }
                }
                Remainder => {
                    if unsigned {
                        "urem"
                    } else {
                        "srem"
                    }
                }
                Equal => "icmp eq",
                NotEqual => "icmp ne",
                Less => {
                    if unsigned {
                        "icmp ult"
                    } else {
                        "icmp slt"
                    }
                }
                LessEqual => {
                    if unsigned {
                        "icmp ule"
                    } else {
                        "icmp sle"
                    }
                }
                Greater => {
                    if unsigned {
                        "icmp ugt"
                    } else {
                        "icmp sgt"
                    }
                }
                GreaterEqual => {
                    if unsigned {
                        "icmp uge"
                    } else {
                        "icmp sge"
                    }
                }
                BitAnd => "and",
                BitOr => "or",
                BitXor => "xor",
                ShiftLeft => "shl",
                ShiftRight => {
                    if unsigned {
                        "lshr"
                    } else {
                        "ashr"
                    }
                }
                ShiftRightUnsigned => "lshr",
                _ => unreachable!("operator checked or handled separately"),
            }
        };
        self.value(format!("{instruction} {} {lhs}, {rhs}", self.ty(&left.ty)))
    }
}

fn numeric_kind(ty: &Type) -> u16 {
    match ty {
        Type::Binary(16) => 0,
        Type::Binary(32) => 1,
        Type::Binary(64) => 2,
        Type::Binary(128) => 3,
        Type::Decimal(32) => 4,
        Type::Decimal(64) => 5,
        Type::Decimal(128) => 6,
        Type::Integer(bits, signed) => 16 + (bits / 8).ilog2() as u16 + if *signed { 0 } else { 8 },
        _ => unreachable!("numeric type checked"),
    }
}

fn export_wrapper(function: &CheckedFunction, module: &CheckedModule) -> String {
    let parameters = function
        .signature
        .parameters
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("{} %arg{index}", abi_type(ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let result = &function.signature.result;
    let mut output = format!(
        "define {} @tz_{}({parameters}) nounwind {{\nentry:\n",
        abi_type(result),
        function.name
    );
    let mut arguments = Vec::new();
    for (index, ty) in function.signature.parameters.iter().enumerate() {
        if *ty == Type::Bool {
            let _ = writeln!(output, "  %b{index} = icmp ne i32 %arg{index}, 0");
            arguments.push(format!("i1 %b{index}"));
        } else if let Type::Integer(bits @ (8 | 16), _) = ty {
            let _ = writeln!(output, "  %n{index} = trunc i32 %arg{index} to i{bits}");
            arguments.push(format!("i{bits} %n{index}"));
        } else {
            arguments.push(format!("{} %arg{index}", llvm_type(ty, module)));
        }
    }
    let _ = writeln!(
        output,
        "  %result = call {} @tz.fn.{}({})",
        llvm_type(result, module),
        function.qualified_name(),
        arguments.join(", ")
    );
    match result {
        Type::Bool => output.push_str("  %bool = zext i1 %result to i32\n  ret i32 %bool\n"),
        Type::Unit => output.push_str("  ret void\n"),
        Type::Integer(bits @ (8 | 16), signed) => {
            let _ = writeln!(
                output,
                "  %wide = {} i{bits} %result to i32\n  ret i32 %wide",
                if *signed { "sext" } else { "zext" }
            );
        }
        _ => {
            let _ = writeln!(output, "  ret {} %result", llvm_type(result, module));
        }
    }
    output.push_str("}\n\n");
    output
}

fn saturating_cast(
    from: u16,
    bits: u16,
    signed: bool,
    intrinsics: &mut BTreeSet<String>,
) -> String {
    let sign = if signed { "s" } else { "u" };
    let intrinsic = format!("llvm.fpto{sign}i.sat.i{bits}.f{from}");
    let source = if from == 32 { "float" } else { "double" };
    intrinsics.insert(format!("declare i{bits} @{intrinsic}({source})"));
    intrinsic
}

fn emit_builtin(builtin: Builtin, intrinsics: &mut BTreeSet<String>) -> String {
    let name = builtin.name();
    match builtin {
        Builtin::ToFloat => format!(
            "define internal double @tz.builtin.{name}(i64 %x) nounwind {{\n\
             entry:\n  %r = sitofp i64 %x to double\n  ret double %r\n}}\n\n"
        ),
        Builtin::ToInt => {
            let intrinsic = saturating_cast(64, 64, true, intrinsics);
            format!(
                "define internal i64 @tz.builtin.{name}(double %x) nounwind {{\n\
                 entry:\n  %r = call i64 @{intrinsic}(double %x)\n  ret i64 %r\n}}\n\n"
            )
        }
        Builtin::Assert => format!(
            "define internal i8 @tz.builtin.{name}(i1 %x) nounwind {{\n\
             entry:\n  br i1 %x, label %ok, label %fail\n\
             fail:\n  call void @llvm.trap()\n  unreachable\n\
             ok:\n  ret i8 0\n}}\n\n"
        ),
        Builtin::CloneString => format!(
            "define internal %tz.string @tz.builtin.{name}(ptr %x) nounwind {{\n\
             entry:\n  %s = load %tz.string, ptr %x\n\
             %p = extractvalue %tz.string %s, 0\n  %n = extractvalue %tz.string %s, 1\n\
             %r = call %tz.string @tz.string.new(ptr %p, i64 %n)\n  ret %tz.string %r\n}}\n\n"
        ),
        _ => {
            let intrinsic = match builtin {
                Builtin::Sqrt => "sqrt",
                Builtin::Floor => "floor",
                Builtin::Ceil => "ceil",
                Builtin::Abs => "fabs",
                _ => unreachable!(),
            };
            intrinsics.insert(format!("declare double @llvm.{intrinsic}.f64(double)"));
            format!(
                "define internal double @tz.builtin.{name}(double %x) nounwind {{\n\
                 entry:\n  %r = call double @llvm.{intrinsic}.f64(double %x)\n\
                 ret double %r\n}}\n\n"
            )
        }
    }
}

fn console_main(module: &CheckedModule) -> String {
    let main = &module.functions[module.entry.unwrap()];
    let ty = &main.signature.result;
    let buffered = matches!(
        ty,
        Type::String | Type::Integer(128, _) | Type::Binary(16 | 128) | Type::Decimal(_)
    );
    let mut output = match ty {
        Type::Integer(8 | 16 | 32 | 64, signed) => format!(
            "@tz.fmt = private unnamed_addr constant [6 x i8] c\"%ll{}\\0A\\00\"\n",
            if *signed { "d" } else { "u" }
        ),
        Type::Binary(64) => {
            "@tz.fmt = private unnamed_addr constant [7 x i8] c\"%.17g\\0A\\00\"\n".into()
        }
        Type::Binary(32) => {
            "@tz.fmt = private unnamed_addr constant [6 x i8] c\"%.9g\\0A\\00\"\n".into()
        }
        Type::Bool => String::from(
            "@tz.fmt = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n\
             @tz.true = private unnamed_addr constant [5 x i8] c\"true\\00\"\n\
             @tz.false = private unnamed_addr constant [6 x i8] c\"false\\00\"\n",
        ),
        _ => String::new(),
    };
    if buffered {
        output.push_str(include_str!("runtime/console.ll"));
    } else if *ty != Type::Unit {
        output.push_str("declare i32 @printf(ptr, ...)\n\n");
    }
    let _ = writeln!(
        output,
        "define i32 @main() {{\nentry:\n  %result = call {} @tz.fn.{}()",
        llvm_type(ty, module),
        main.qualified_name()
    );
    match ty {
        Type::Integer(bits @ (8 | 16 | 32 | 64), signed) => {
            let value = if *bits < 64 {
                let _ = writeln!(
                    output,
                    "  %wide = {} i{bits} %result to i64",
                    if *signed { "sext" } else { "zext" }
                );
                "%wide"
            } else {
                "%result"
            };
            let _ = writeln!(
                output,
                "  %printed = call i32 (ptr, ...) @printf(ptr @tz.fmt, i64 {value})"
            );
        }
        Type::Binary(32 | 64) => {
            let value = if *ty == Type::Binary(32) {
                output.push_str("  %wide = fpext float %result to double\n");
                "%wide"
            } else {
                "%result"
            };
            let _ = writeln!(
                output,
                "  %printed = call i32 (ptr, ...) @printf(ptr @tz.fmt, double {value})"
            );
        }
        Type::Bool => {
            output.push_str(
                "  %text = select i1 %result, ptr @tz.true, ptr @tz.false\n\
                   %printed = call i32 (ptr, ...) @printf(ptr @tz.fmt, ptr %text)\n",
            );
        }
        Type::String => {
            output.push_str("  %data = extractvalue %tz.string %result, 0\n  %length = extractvalue %tz.string %result, 1\n  %printed = call i32 @tz.console.write(ptr %data, i64 %length)\n  call void @tz.free(ptr %data)\n");
        }
        Type::Unit => {}
        _ if ty.is_numeric() => {
            let _ = writeln!(
                output,
                "  %slot = alloca {}, align 16\n  %buffer = alloca [64 x i8], align 16\n  store {} %result, ptr %slot\n  %count = call i32 @tz_soft_format(ptr %buffer, ptr %slot, i32 {})\n  %length = zext i32 %count to i64\n  %printed = call i32 @tz.console.write(ptr %buffer, i64 %length)",
                llvm_type(ty, module),
                llvm_type(ty, module),
                numeric_kind(ty)
            );
        }
        _ => unreachable!("main validated"),
    }
    if *ty == Type::Unit {
        output.push_str("  ret i32 0\n");
    } else {
        output.push_str(
            "  %failed = icmp slt i32 %printed, 0\n  %exit = zext i1 %failed to i32\n  ret i32 %exit\n",
        );
    }
    output.push_str("}\n");
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyze;

    #[test]
    fn emits_explicit_tail_loop_and_checked_arithmetic() {
        let module = analyze(
            "fn rec sum(n: i64, acc: i64) -> i64 {
                if n == 0 { acc / 2 } else { sum(n - 1, acc + n) }
             }
             export fn main() -> i64 { sum(100, 0) }",
        )
        .unwrap();
        let ir = emit(&module, Entry::Console).unwrap();
        let body = ir
            .split("define internal i64 @tz.fn.Main.sum(")
            .nth(1)
            .unwrap()
            .split("\n}")
            .next()
            .unwrap();
        assert!(!body.contains("call i64 @tz.fn.Main.sum"));
        assert!(ir.contains("phi i64"));
        assert!(ir.contains("call void @llvm.trap()"));
        assert!(ir.contains("define i64 @tz_main()"));
        assert!(ir.contains("define i32 @main()"));
        assert!(!ir.contains(" nsw "));
        assert_eq!(ir, emit(&module, Entry::Console).unwrap());
    }

    #[test]
    fn puts_array_storage_before_the_tail_loop() {
        let module = analyze(
            "fn rec f(n: i64, a: [i64]) -> i64 {
                let first = a[n & 1];
                if n == 0 { first } else { f(n - 1, [first, 2]) }
             }",
        )
        .unwrap();
        let ir = emit(&module, Entry::Library).unwrap();
        assert!(ir.find("alloca").unwrap() < ir.find("br label %loop").unwrap());
        let body = ir
            .split("define internal i64 @tz.fn.Main.f(")
            .nth(1)
            .unwrap()
            .split("\n}")
            .next()
            .unwrap();
        assert!(!body.contains("call i64 @tz.fn.Main.f"));
    }

    #[test]
    fn emits_portable_bool_abi_and_c_header() {
        let module = analyze("export fn not(x: bool) -> bool { !x }").unwrap();
        let ir = emit(&module, Entry::Library).unwrap();
        assert!(ir.contains("define i32 @tz_not(i32 %arg0)"));
        assert!(ir.contains("icmp ne i32 %arg0, 0"));
        assert!(header(&module).contains("int32_t tz_not(int32_t arg0);"));
        assert!(emit(&module, Entry::Console).is_err());
    }
}
